% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Augustine of Hippo
% Max depth: 1, Max related topics per node: 1

concept(augustine_of_hippo).
concept(original_sin).
related_to(original_sin, augustine_of_hippo).
concept(divine_grace).
related_to(divine_grace, augustine_of_hippo).
concept(predestination).
related_to(predestination, augustine_of_hippo).
concept(just_war_theory).
related_to(just_war_theory, augustine_of_hippo).
concept(confessions).
related_to(confessions, augustine_of_hippo).
concept(the_city_of_god).
related_to(the_city_of_god, augustine_of_hippo).
concept(free_will).
related_to(free_will, augustine_of_hippo).
concept(faith_and_reason).
related_to(faith_and_reason, augustine_of_hippo).
concept(doctrine_of_the_trinity).
related_to(doctrine_of_the_trinity, augustine_of_hippo).
concept(augustinianism).
related_to(augustinianism, augustine_of_hippo).
concept(pelagianism).
related_to(pelagianism, augustine_of_hippo).
concept(neoplatonism).
related_to(neoplatonism, augustine_of_hippo).
concept(platonism).
related_to(platonism, augustine_of_hippo).
concept(manichaeism).
related_to(manichaeism, augustine_of_hippo).
concept(catholic_christianity).
related_to(catholic_christianity, augustine_of_hippo).
related_to(augustine_of_hippo, augustine_of_hippo).
concept(pelagius).
related_to(pelagius, augustine_of_hippo).
concept(ambrose_of_milan).
related_to(ambrose_of_milan, augustine_of_hippo).
concept(plotinus).
related_to(plotinus, augustine_of_hippo).
concept(thomas_aquinas).
related_to(thomas_aquinas, augustine_of_hippo).
concept(reformation_theology).
related_to(reformation_theology, augustine_of_hippo).
concept(medieval_scholasticism).
related_to(medieval_scholasticism, augustine_of_hippo).
concept(patristic_philosophy).
related_to(patristic_philosophy, augustine_of_hippo).
concept(late_antiquity).
related_to(late_antiquity, augustine_of_hippo).
concept(x354430_ce).
related_to(x354430_ce, augustine_of_hippo).
concept(augustinian_order).
related_to(augustinian_order, augustine_of_hippo).
lived_during(augustine_of_hippo, late_antiquity).
% Explanation: Augustine lived from 354 to 430 CE, during the Late Antiquity period.
main_work(augustine_of_hippo, confessions).
% Explanation: Confessions is one of Augustine's principal works, chronicling his spiritual journey.
main_work(augustine_of_hippo, the_city_of_god).
% Explanation: The City of God is a foundational work addressing theology and philosophy of history.
developed_by(augustine_of_hippo, original_sin).
% Explanation: Augustine formalized and developed the doctrine of Original Sin.
developed_by(augustine_of_hippo, divine_grace).
% Explanation: Augustine emphasized the necessity of Divine Grace in salvation.
developed_by(augustine_of_hippo, predestination).
% Explanation: Augustine set forth early Christian doctrine of Predestination.
developed_by(augustine_of_hippo, just_war_theory).
% Explanation: Augustine formulated foundational ideas of Just War Theory.
developed_by(augustine_of_hippo, doctrine_of_the_trinity).
% Explanation: Augustine contributed significantly to the Christian Doctrine of the Trinity.
developed_by(augustine_of_hippo, faith_and_reason).
% Explanation: Augustine explored the relationship between Faith and Reason, influencing later philosophy.
response_to(doctrine_of_the_trinity, arianism).
% Explanation: Augustine's trinitarian work responds to anti-Trinitarian positions like Arianism.
developed_by(free_will, augustine_of_hippo).
% Explanation: Augustine advanced Christian understanding of Free Will.
school_of_thought(augustinianism, augustine_of_hippo).
% Explanation: Augustinianism is the theological and philosophical tradition based on Augustine's ideas.
influenced_by(augustinianism, neoplatonism).
% Explanation: Augustine's thought was influenced by Neoplatonic philosophy, mainly Plotinus.
developed_by(neoplatonism, plotinus).
% Explanation: Plotinus systematized Neoplatonism, a key influence for Augustine.
student_of(augustine_of_hippo, ambrose_of_milan).
% Explanation: Augustine was influenced and baptized by Ambrose, the Bishop of Milan.
formerly_followed(augustine_of_hippo, manichaeism).
% Explanation: Augustine was a Manichaean before converting to Christianity.
school_of_thought(augustine_of_hippo, patristic_philosophy).
% Explanation: Augustine is one of the most important Church Fathers in patristic philosophy.
school_of_thought(augustine_of_hippo, catholic_christianity).
% Explanation: Augustine is a key figure in Catholic Christian theology.
criticized_by(original_sin, pelagius).
% Explanation: Pelagius opposed Augustine's view of Original Sin and Divine Grace.
developed_by(pelagianism, pelagius).
% Explanation: Pelagius founded Pelagianism, denying original sin and emphasizing free will.
criticized_by(pelagianism, augustine_of_hippo).
% Explanation: Augustine vigorously argued against Pelagianism in his theological writings.
influenced_by(augustinianism, platonism).
% Explanation: Platonic thought, especially concepts of immaterial forms, shaped Augustine’s philosophy.
contemporary_of(augustine_of_hippo, pelagius).
% Explanation: Augustine and Pelagius were contemporaries and debated theological issues.
contemporary_of(augustine_of_hippo, ambrose_of_milan).
% Explanation: Ambrose of Milan and Augustine were contemporaries in Late Antiquity.
influenced_by(thomas_aquinas, augustine_of_hippo).
% Explanation: Thomas Aquinas's Scholasticism built on Augustine's synthesis of faith and reason.
influenced_by(reformation_theology, augustinianism).
% Explanation: Reformers like Luther and Calvin were heavily influenced by Augustinian doctrines, especially grace and predestination.
influenced_by(medieval_scholasticism, augustine_of_hippo).
% Explanation: Augustine's ideas significantly shaped medieval scholastic philosophy and theology.
school_of_thought(augustinian_order, augustinianism).
% Explanation: The Augustinian religious order follows the rule and teachings of Augustine.
developed_during(confessions, x400_ce).
% Explanation: Augustine wrote Confessions around 397–400 CE.
developed_during(the_city_of_god, x413426_ce).
% Explanation: Augustine wrote The City of God between 413 and 426 CE.
related_to(original_sin, original_sin).
concept(fall_of_man).
related_to(fall_of_man, original_sin).
concept(adam_and_eve).
related_to(adam_and_eve, original_sin).
concept(concupiscence).
related_to(concupiscence, original_sin).
concept(inheritance_of_sin).
related_to(inheritance_of_sin, original_sin).
concept(baptism).
related_to(baptism, original_sin).
concept(justification).
related_to(justification, original_sin).
related_to(free_will, original_sin).
related_to(pelagianism, original_sin).
related_to(augustinianism, original_sin).
concept(catholic_doctrine).
related_to(catholic_doctrine, original_sin).
concept(protestant_doctrine).
related_to(protestant_doctrine, original_sin).
concept(eastern_orthodox_view).
related_to(eastern_orthodox_view, original_sin).
concept(saint_augustine).
related_to(saint_augustine, original_sin).
related_to(pelagius, original_sin).
concept(saint_thomas_aquinas).
related_to(saint_thomas_aquinas, original_sin).
concept(john_calvin).
related_to(john_calvin, original_sin).
concept(martin_luther).
related_to(martin_luther, original_sin).
concept(immanuel_kant).
related_to(immanuel_kant, original_sin).
concept(enlightenment_critique).
related_to(enlightenment_critique, original_sin).
developed_by(original_sin, saint_augustine).
% Explanation: Augustine articulated and systematized the doctrine of Original Sin in the 4th-5th centuries.
lived_during(saint_augustine, late_antiquity_354430_ce).
% Explanation: Augustine lived in the late Roman Empire.
developed_by(augustinianism, saint_augustine).
% Explanation: Augustinianism as a school was based on Augustine's interpretations and arguments.
rooted_in(original_sin, fall_of_man).
% Explanation: The doctrine is based on the biblical narrative of the Fall of Adam and Eve.
narrated_in(fall_of_man, adam_and_eve).
% Explanation: The Fall is depicted through the actions of Adam and Eve in Genesis.
explains_with(original_sin, concupiscence).
% Explanation: Augustine described concupiscence as the disordered desire resulting from Original Sin.
transmitted_by(original_sin, inheritance_of_sin).
% Explanation: Original Sin is believed to be inherited by all humans from Adam and Eve.
remedied_by(original_sin, baptism).
% Explanation: Christian doctrine states that baptism cleanses original sin.
criticized_by(pelagianism, augustinianism).
% Explanation: Augustine fiercely opposed Pelagianism, which denied inherited original sin.
contemporary_of(pelagius, saint_augustine).
% Explanation: Pelagius and Augustine were contemporaries and debated the nature of Original Sin.
lived_during(saint_thomas_aquinas, high_middle_ages_12251274).
% Explanation: Aquinas lived in the 13th century and synthesized Augustine with Aristotelian thought.
interpreted_by(original_sin, saint_thomas_aquinas).
% Explanation: Aquinas refined the doctrine of original sin, differing somewhat from Augustine.
main_work(saint_thomas_aquinas, summa_theologica).
% Explanation: Aquinas presented his view of original sin in the Summa Theologica.
lived_during(john_calvin, x16th_century_reformation).
% Explanation: Calvin was a leader of the Protestant Reformation.
lived_during(martin_luther, x16th_century_reformation).
% Explanation: Luther was a seminal figure in the Protestant Reformation.
developed_by(protestant_doctrine, martin_luther).
% Explanation: Luther emphasized the total depravity resulting from original sin.
developed_by(protestant_doctrine, john_calvin).
% Explanation: Calvin deepened the concept, focusing on predestination and total depravity.
response_to(catholic_doctrine, augustinianism).
% Explanation: The Catholic doctrine is rooted in Augustine's view but refined by later theologians.
criticized_by(eastern_orthodox_view, augustinianism).
% Explanation: Orthodox theologians reject Augustine's idea of inherited guilt, focusing on inherited mortality.
lived_during(immanuel_kant, enlightenment_17241804).
% Explanation: Kant was a central figure of the Enlightenment.
developed_by(enlightenment_critique, immanuel_kant).
% Explanation: Kant reinterpreted original sin as a symbol of universal moral failing, not literal inheritance.
response_to(enlightenment_critique, augustinianism).
% Explanation: The Enlightenment reinterpreted or rejected the literal doctrine of original sin.
central_to(free_will, pelagianism).
% Explanation: Pelagius argued that humans retain complete free will despite the fall.
explained_by(justification, protestant_doctrine).
% Explanation: Luther and Calvin argued that justification is solely by grace due to original sin.
school_of_thought(school_of_thought, saint_augustine_augustinianism).
% Explanation: Augustine is the founder of the Augustinian tradition.
school_of_thought(school_of_thought, pelagius_pelagianism).
% Explanation: Pelagius is the founder of the Pelagian school.
school_of_thought(school_of_thought, saint_thomas_aquinas_scholasticism).
% Explanation: Aquinas is associated with Scholastic philosophy.
school_of_thought(school_of_thought, martin_luther_protestantism).
% Explanation: Luther is considered a founder of Protestant thought.
school_of_thought(school_of_thought, john_calvin_reformed_theology).
% Explanation: Calvin is central to Reformed or Calvinist theology.
main_work(main_work, saint_augustine_confessions).
% Explanation: Augustine outlines the nature of sin and grace in Confessions.
main_work(main_work, martin_luther_on_the_bondage_of_the_will).
% Explanation: Luther's work focuses on free will and original sin.
main_work(main_work, john_calvin_institutes_of_the_christian_religion).
% Explanation: Calvin presents his doctrine of original sin and predestination.
