% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Jorge Luis Borges
% Max depth: 1, Max related topics per node: 1

concept(jorge_luis_borges).
related_to(jorge_luis_borges, jorge_luis_borges).
concept(ficciones).
related_to(ficciones, jorge_luis_borges).
concept(el_aleph).
related_to(el_aleph, jorge_luis_borges).
concept(the_library_of_babel).
related_to(the_library_of_babel, jorge_luis_borges).
concept(pierre_menard_author_of_the_quixote).
related_to(pierre_menard_author_of_the_quixote, jorge_luis_borges).
concept(tlön_uqbar_orbis_tertius).
related_to(tlön_uqbar_orbis_tertius, jorge_luis_borges).
concept(the_garden_of_forking_paths).
related_to(the_garden_of_forking_paths, jorge_luis_borges).
concept(labyrinths).
related_to(labyrinths, jorge_luis_borges).
concept(blindness).
related_to(blindness, jorge_luis_borges).
concept(buenos_aires).
related_to(buenos_aires, jorge_luis_borges).
concept(argentina).
related_to(argentina, jorge_luis_borges).
concept(x20th_century).
related_to(x20th_century, jorge_luis_borges).
concept(short_story).
related_to(short_story, jorge_luis_borges).
concept(essay).
related_to(essay, jorge_luis_borges).
concept(surrealism).
related_to(surrealism, jorge_luis_borges).
concept(modernism).
related_to(modernism, jorge_luis_borges).
concept(magical_realism).
related_to(magical_realism, jorge_luis_borges).
concept(metafiction).
related_to(metafiction, jorge_luis_borges).
concept(philosophy).
related_to(philosophy, jorge_luis_borges).
concept(infinity).
related_to(infinity, jorge_luis_borges).
concept(mirrors).
related_to(mirrors, jorge_luis_borges).
concept(labyrinths_motif).
related_to(labyrinths_motif, jorge_luis_borges).
concept(identity).
related_to(identity, jorge_luis_borges).
concept(universal_library).
related_to(universal_library, jorge_luis_borges).
concept(gabriel_garcía_márquez).
related_to(gabriel_garcía_márquez, jorge_luis_borges).
concept(umberto_eco).
related_to(umberto_eco, jorge_luis_borges).
concept(salman_rushdie).
related_to(salman_rushdie, jorge_luis_borges).
concept(latin_american_literature).
related_to(latin_american_literature, jorge_luis_borges).
concept(spanish_language).
related_to(spanish_language, jorge_luis_borges).
concept(poetry).
related_to(poetry, jorge_luis_borges).
concept(kabbalah).
related_to(kabbalah, jorge_luis_borges).
concept(william_faulkner).
related_to(william_faulkner, jorge_luis_borges).
concept(edgar_allan_poe).
related_to(edgar_allan_poe, jorge_luis_borges).
concept(existentialism).
related_to(existentialism, jorge_luis_borges).
concept(reality_vs_fiction).
related_to(reality_vs_fiction, jorge_luis_borges).
concept(the_book_of_sand).
related_to(the_book_of_sand, jorge_luis_borges).
concept(dreams).
related_to(dreams, jorge_luis_borges).
concept(time).
related_to(time, jorge_luis_borges).
concept(death).
related_to(death, jorge_luis_borges).
concept(history).
related_to(history, jorge_luis_borges).
concept(the_aleph_character_and_motif).
related_to(the_aleph_character_and_motif, jorge_luis_borges).
concept(richard_burton_translator).
related_to(richard_burton_translator, jorge_luis_borges).
concept(argentinian_dictatorship).
related_to(argentinian_dictatorship, jorge_luis_borges).
concept(blindness_borges_condition).
related_to(blindness_borges_condition, jorge_luis_borges).
concept(labyrinths_collection).
related_to(labyrinths_collection, jorge_luis_borges).
concept(babel_biblical_allusion).
related_to(babel_biblical_allusion, jorge_luis_borges).
written_by(ficciones, jorge_luis_borges).
% Explanation: Ficciones is a collection of short stories authored by Borges.
written_by(el_aleph, jorge_luis_borges).
% Explanation: El Aleph is another seminal collection of Borges' stories.
published_in(ficciones, x1944).
% Explanation: Ficciones was originally published in 1944.
published_in(el_aleph, x1949).
% Explanation: El Aleph was published in 1949.
born_in(jorge_luis_borges, buenos_aires).
% Explanation: Borges was born in Buenos Aires, Argentina.
located_in(buenos_aires, argentina).
% Explanation: Buenos Aires is the capital city of Argentina.
active_during(jorge_luis_borges, x20th_century).
% Explanation: Borges was most active during the 20th century.
language_of(jorge_luis_borges, spanish_language).
% Explanation: Borges wrote primarily in Spanish.
genre_of(jorge_luis_borges, short_story).
% Explanation: Borges is known primarily for his short stories.
genre_of(jorge_luis_borges, essay).
% Explanation: He was also a significant essayist.
genre_of(jorge_luis_borges, poetry).
% Explanation: Borges wrote many poems as well.
movement(jorge_luis_borges, modernism).
% Explanation: His work is associated with modernist literature.
movement(jorge_luis_borges, magical_realism).
% Explanation: Borges is often cited as a precursor to magical realism.
movement(jorge_luis_borges, surrealism).
% Explanation: His work incorporates surrealistic elements.
includes(ficciones, the_library_of_babel).
% Explanation: The Library of Babel is a short story within Ficciones.
includes(ficciones, pierre_menard_author_of_the_quixote).
% Explanation: Pierre Menard, Author of the Quixote is included in Ficciones.
includes(ficciones, tlön_uqbar_orbis_tertius).
% Explanation: Tlön, Uqbar, Orbis Tertius is part of the Ficciones collection.
includes(ficciones, the_garden_of_forking_paths).
% Explanation: This story is also within Ficciones.
explores(the_library_of_babel, infinity).
% Explanation: The Library of Babel is a story about infinite space and knowledge.
features_motif(the_library_of_babel, labyrinths_motif).
% Explanation: The infinite library is a metaphorical labyrinth.
personal_experience(jorge_luis_borges, blindness).
% Explanation: Borges became blind later in life, influencing his work.
influenced(blindness, borges_late_writing_style).
% Explanation: His blindness led to more concise, lyrical works.
explores(pierre_menard_author_of_the_quixote, metafiction).
% Explanation: This story is a quintessential work of metafiction.
explores(tlön_uqbar_orbis_tertius, reality_vs_fiction).
% Explanation: Questions the boundary between fiction and reality.
explores(the_garden_of_forking_paths, time).
% Explanation: Discusses multiple timelines and parallel possibilities.
protagonist_of(the_aleph_character_and_motif, el_aleph).
% Explanation: The Aleph is both a character and a mystical object in the story.
editor_of(borges, labyrinths_collection).
% Explanation: Borges edited this influential collection.
influenced(jorge_luis_borges, gabriel_garcía_márquez).
% Explanation: Borges was a key influence on García Márquez.
influenced(jorge_luis_borges, umberto_eco).
% Explanation: Eco drew from Borges' use of labyrinths and metafiction.
influenced(jorge_luis_borges, salman_rushdie).
% Explanation: Rushdie adopted fantastical and postmodern elements inspired by Borges.
influenced_by(jorge_luis_borges, edgar_allan_poe).
% Explanation: Borges admired Poe's complexity and metaphysical themes.
influenced_by(jorge_luis_borges, william_faulkner).
% Explanation: Borges cited Faulkner as an influence, particularly regarding narrative.
explored(jorge_luis_borges, kabbalah).
% Explanation: Jewish mysticism, especially Kabbalah, influenced Borges' work.
central_to(labyrinths_motif, borges_fiction).
% Explanation: Labyrinths appear figuratively and literally throughout Borges' stories.
foundational_figure(jorge_luis_borges, latin_american_literature).
% Explanation: Borges is credited as a foundational figure in Latin American literature.
movement(ficciones, modernism).
% Explanation: The stories exemplify modernist experimentation.
genre_of(ficciones, short_story).
% Explanation: Ficciones is a collection of short stories.
set_in(the_library_of_babel, universal_library).
% Explanation: The story takes place in a library that is a metaphor for the universe.
referenced_in(babel_biblical_allusion, the_library_of_babel).
% Explanation: The story is inspired by the Tower of Babel.
influenced_by(borges_late_writing_style, blindness_borges_condition).
% Explanation: His late minimalist prose style was shaped by his blindness.
active_during(jorge_luis_borges, argentinian_dictatorship).
% Explanation: Borges published during a period of political turmoil in Argentina.
explored(jorge_luis_borges, philosophy).
% Explanation: Philosophical themes permeate Borges' works.
written_by(the_book_of_sand, jorge_luis_borges).
% Explanation: The Book of Sand is a late collection by Borges.
published_in(the_book_of_sand, x1975).
% Explanation: Published near the end of Borges' life.
explored(jorge_luis_borges, dreams).
% Explanation: Dreams and consciousness are recurring themes.
explored(jorge_luis_borges, death).
% Explanation: Mortality and the afterlife are common topics.
explored(jorge_luis_borges, identity).
% Explanation: Many stories feature themes of personal and literary identity.
movement(jorge_luis_borges, existentialism).
% Explanation: Existential themes appear frequently in Borges' work.
translated_by(jorge_luis_borges, richard_burton_translator).
% Explanation: Some of Borges’ works were translated into English by Richard Burton and others.
concept(labyrinths_in_literature).
concept(labyrinth).
related_to(labyrinth, labyrinths_in_literature).
concept(maze).
related_to(maze, labyrinths_in_literature).
concept(symbolism).
related_to(symbolism, labyrinths_in_literature).
concept(metaphor_of_journey).
related_to(metaphor_of_journey, labyrinths_in_literature).
concept(enlightenment).
related_to(enlightenment, labyrinths_in_literature).
concept(confusion).
related_to(confusion, labyrinths_in_literature).
concept(selfdiscovery).
related_to(selfdiscovery, labyrinths_in_literature).
concept(classical_labyrinth_myth).
related_to(classical_labyrinth_myth, labyrinths_in_literature).
concept(minotaur).
related_to(minotaur, labyrinths_in_literature).
concept(theseus).
related_to(theseus, labyrinths_in_literature).
concept(daedalus).
related_to(daedalus, labyrinths_in_literature).
concept(ariadne).
related_to(ariadne, labyrinths_in_literature).
concept(greek_mythology).
related_to(greek_mythology, labyrinths_in_literature).
related_to(modernism, labyrinths_in_literature).
concept(postmodern_literature).
related_to(postmodern_literature, labyrinths_in_literature).
related_to(metafiction, labyrinths_in_literature).
related_to(magical_realism, labyrinths_in_literature).
concept(borges).
related_to(borges, labyrinths_in_literature).
related_to(jorge_luis_borges, labyrinths_in_literature).
related_to(the_garden_of_forking_paths, labyrinths_in_literature).
concept(published_inthe_garden_of_forking_paths_1941).
related_to(published_inthe_garden_of_forking_paths_1941, labyrinths_in_literature).
concept(written_bythe_garden_of_forking_paths_jorge_luis_borges).
related_to(written_bythe_garden_of_forking_paths_jorge_luis_borges, labyrinths_in_literature).
concept(genre_ofthe_garden_of_forking_paths_short_story).
related_to(genre_ofthe_garden_of_forking_paths_short_story, labyrinths_in_literature).
concept(movementjorge_luis_borges_modernism).
related_to(movementjorge_luis_borges_modernism, labyrinths_in_literature).
concept(movementjorge_luis_borges_postmodernism).
related_to(movementjorge_luis_borges_postmodernism, labyrinths_in_literature).
concept(escher).
related_to(escher, labyrinths_in_literature).
concept(italo_calvino).
related_to(italo_calvino, labyrinths_in_literature).
concept(invisible_cities).
related_to(invisible_cities, labyrinths_in_literature).
concept(written_byinvisible_cities_italo_calvino).
related_to(written_byinvisible_cities_italo_calvino, labyrinths_in_literature).
concept(published_ininvisible_cities_1972).
related_to(published_ininvisible_cities_1972, labyrinths_in_literature).
related_to(umberto_eco, labyrinths_in_literature).
concept(the_name_of_the_rose).
related_to(the_name_of_the_rose, labyrinths_in_literature).
concept(written_bythe_name_of_the_rose_umberto_eco).
related_to(written_bythe_name_of_the_rose_umberto_eco, labyrinths_in_literature).
concept(published_inthe_name_of_the_rose_1980).
related_to(published_inthe_name_of_the_rose_1980, labyrinths_in_literature).
concept(genre_ofthe_name_of_the_rose_historical_novel).
related_to(genre_ofthe_name_of_the_rose_historical_novel, labyrinths_in_literature).
concept(set_inthe_name_of_the_rose_14th_century_italian_monastery).
related_to(set_inthe_name_of_the_rose_14th_century_italian_monastery, labyrinths_in_literature).
concept(labyrinthine_library).
related_to(labyrinthine_library, labyrinths_in_literature).
concept(james_joyce).
related_to(james_joyce, labyrinths_in_literature).
concept(ulysses).
related_to(ulysses, labyrinths_in_literature).
concept(written_byulysses_james_joyce).
related_to(written_byulysses_james_joyce, labyrinths_in_literature).
concept(published_inulysses_1922).
related_to(published_inulysses_1922, labyrinths_in_literature).
concept(movementjames_joyce_modernism).
related_to(movementjames_joyce_modernism, labyrinths_in_literature).
concept(genre_ofulysses_modernist_novel).
related_to(genre_ofulysses_modernist_novel, labyrinths_in_literature).
concept(kafka).
related_to(kafka, labyrinths_in_literature).
concept(the_trial).
related_to(the_trial, labyrinths_in_literature).
concept(written_bythe_trial_franz_kafka).
related_to(written_bythe_trial_franz_kafka, labyrinths_in_literature).
concept(published_inthe_trial_1925).
related_to(published_inthe_trial_1925, labyrinths_in_literature).
concept(genre_ofthe_trial_existential_novel).
related_to(genre_ofthe_trial_existential_novel, labyrinths_in_literature).
concept(labyrinth_as_narrative_structure).
related_to(labyrinth_as_narrative_structure, labyrinths_in_literature).
concept(intertextuality).
related_to(intertextuality, labyrinths_in_literature).
concept(reader_as_wanderer).
related_to(reader_as_wanderer, labyrinths_in_literature).
concept(protagonist_as_wanderer).
related_to(protagonist_as_wanderer, labyrinths_in_literature).
concept(influenced_byborges_classical_labyrinth_myth).
related_to(influenced_byborges_classical_labyrinth_myth, labyrinths_in_literature).
concept(influenced_byinvisible_cities_borges).
related_to(influenced_byinvisible_cities_borges, labyrinths_in_literature).
concept(influenced_byeco_borges).
related_to(influenced_byeco_borges, labyrinths_in_literature).
concept(influenced_byjames_joyce_labyrinth_as_narrative_structure).
related_to(influenced_byjames_joyce_labyrinth_as_narrative_structure, labyrinths_in_literature).
concept(adapted_intothe_name_of_the_rose_the_name_of_the_rose_film_1986).
related_to(adapted_intothe_name_of_the_rose_the_name_of_the_rose_film_1986, labyrinths_in_literature).
symbol_of(labyrinth, confusion).
% Explanation: Labyrinths often symbolize confusion, both literal and existential, in literature.
symbol_of(labyrinth, selfdiscovery).
% Explanation: Navigating a labyrinth is used as a metaphor for a journey into the self.
represented_by(labyrinth, maze).
% Explanation: Mazes and labyrinths are closely related, sometimes used interchangeably in texts.
originates_from(labyrinth, classical_labyrinth_myth).
% Explanation: The archetype of the labyrinth comes from Greek mythology, with Daedalus, the Minotaur, and Theseus.
includes(classical_labyrinth_myth, minotaur).
% Explanation: The Minotaur is central to the original myth of the labyrinth.
includes(classical_labyrinth_myth, daedalus).
% Explanation: Daedalus constructed the labyrinth.
includes(classical_labyrinth_myth, theseus).
% Explanation: Theseus was the hero who navigated and escaped the labyrinth.
includes(classical_labyrinth_myth, ariadne).
% Explanation: Ariadne provided the thread that helped Theseus escape.
part_of(classical_labyrinth_myth, greek_mythology).
% Explanation: The labyrinth myth is a key story in Greek myth.
used_in(labyrinth, modernism).
% Explanation: Modernist writers used labyrinths as both metaphors and structures in literature.
used_in(labyrinth, postmodern_literature).
% Explanation: Labyrinths are a recurrent motif in postmodern narratives and construction.
structural_device_in(labyrinth, metafiction).
% Explanation: Labyrinthine structure is often used in metafictional works.
device_in(labyrinth, magical_realism).
% Explanation: Labyrinths appear in magical realist texts as both literal and metaphorical spaces.
author_of(jorge_luis_borges, the_garden_of_forking_paths).
% Explanation: Borges wrote the influential story that uses the labyrinth as a metaphor and structure.
published_in(the_garden_of_forking_paths, x1941).
% Explanation: The work was published in 1941.
genre_of(the_garden_of_forking_paths, short_story).
% Explanation: The work is a short story.
exemplifies(the_garden_of_forking_paths, labyrinth_as_narrative_structure).
% Explanation: The story uses a labyrinthine, non-linear narrative.
movement(jorge_luis_borges, postmodernism).
% Explanation: Borges is a precursor to postmodern literary techniques.
influenced_by(borges, classical_labyrinth_myth).
% Explanation: Borges drew inspiration from classical myths of the labyrinth.
written_by(invisible_cities, italo_calvino).
% Explanation: Italo Calvino is the author.
published_in(invisible_cities, x1972).
% Explanation: Published in 1972.
exemplifies(invisible_cities, labyrinth_as_narrative_structure).
% Explanation: The work has a fragmented, labyrinthine composition.
influenced_by(italo_calvino, borges).
% Explanation: Calvino himself acknowledged Borges’ influence.
author_of(umberto_eco, the_name_of_the_rose).
% Explanation: Eco is the author.
published_in(the_name_of_the_rose, x1980).
% Explanation: Published in 1980.
set_in(the_name_of_the_rose, x14th_century_italian_monastery).
% Explanation: The novel’s labyrinthine library is set in a medieval monastery.
features(the_name_of_the_rose, labyrinthine_library).
% Explanation: A central symbol and plot device is the labyrinth-like library.
adapted_into(the_name_of_the_rose, the_name_of_the_rose_film_1986).
% Explanation: Adapted into a film in 1986.
influenced_by(umberto_eco, borges).
% Explanation: Eco's labyrinthine library is an homage to Borges.
written_by(ulysses, james_joyce).
% Explanation: James Joyce is the author.
published_in(ulysses, x1922).
% Explanation: Published in 1922.
genre_of(ulysses, modernist_novel).
% Explanation: Ulysses is a paradigmatic modernist novel.
movement(james_joyce, modernism).
% Explanation: Joyce is a leading figure in Modernism.
structural_device(ulysses, labyrinth_as_narrative_structure).
% Explanation: Joyce uses a complex, maze-like style.
author_of(kafka, the_trial).
% Explanation: Kafka is the author.
published_in(the_trial, x1925).
% Explanation: Published in 1925.
genre_of(the_trial, existential_novel).
% Explanation: The novel is existential in genre.
exemplifies(the_trial, labyrinth_as_narrative_structure).
% Explanation: The main character navigates a bureaucratic labyrinth.
enables(labyrinth_as_narrative_structure, protagonist_as_wanderer).
% Explanation: Characters often function as wanderers or seekers within the labyrinth.
engages(labyrinth_as_narrative_structure, reader_as_wanderer).
% Explanation: Readers, like characters, must navigate the text’s complexities.
implements(labyrinth_as_narrative_structure, intertextuality).
% Explanation: Labyrinthine literature often references or embeds other texts.
influenced_by(invisible_cities, borges).
% Explanation: Calvino’s framing and style are influenced by Borges.
influenced_by(the_name_of_the_rose, borges).
% Explanation: Eco acknowledges Borges as a major influence.
influenced_by(kafka, labyrinth_as_narrative_structure).
% Explanation: Kafka’s work uses the labyrinth metaphor for existential confusion.
