% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Dante Alighieri
% Max depth: 1, Max related topics per node: 1

concept(dante_alighieri).
related_to(dante_alighieri, dante_alighieri).
concept(the_divine_comedy).
related_to(the_divine_comedy, dante_alighieri).
concept(inferno).
related_to(inferno, dante_alighieri).
concept(purgatorio).
related_to(purgatorio, dante_alighieri).
concept(paradiso).
related_to(paradiso, dante_alighieri).
concept(vita_nuova).
related_to(vita_nuova, dante_alighieri).
concept(convivio).
related_to(convivio, dante_alighieri).
concept(de_monarchia).
related_to(de_monarchia, dante_alighieri).
concept(la_commedia).
related_to(la_commedia, dante_alighieri).
concept(florence).
related_to(florence, dante_alighieri).
concept(italy).
related_to(italy, dante_alighieri).
concept(x13th14th_centuries).
related_to(x13th14th_centuries, dante_alighieri).
concept(medieval_literature).
related_to(medieval_literature, dante_alighieri).
concept(italian_literature).
related_to(italian_literature, dante_alighieri).
concept(beatrice_portinari).
related_to(beatrice_portinari, dante_alighieri).
concept(virgil).
related_to(virgil, dante_alighieri).
concept(threepart_structure).
related_to(threepart_structure, dante_alighieri).
concept(allegory).
related_to(allegory, dante_alighieri).
concept(terza_rima).
related_to(terza_rima, dante_alighieri).
concept(exile).
related_to(exile, dante_alighieri).
concept(guelfs).
related_to(guelfs, dante_alighieri).
concept(ghibellines).
related_to(ghibellines, dante_alighieri).
concept(early_renaissance).
related_to(early_renaissance, dante_alighieri).
concept(religious_symbolism).
related_to(religious_symbolism, dante_alighieri).
concept(humanism).
related_to(humanism, dante_alighieri).
concept(francesco_petrarch).
related_to(francesco_petrarch, dante_alighieri).
concept(giovanni_boccaccio).
related_to(giovanni_boccaccio, dante_alighieri).
concept(roman_catholicism).
related_to(roman_catholicism, dante_alighieri).
concept(dantean_hell).
related_to(dantean_hell, dante_alighieri).
concept(classical_literature).
related_to(classical_literature, dante_alighieri).
concept(biblical_references).
related_to(biblical_references, dante_alighieri).
concept(adaptations_of_the_divine_comedy).
related_to(adaptations_of_the_divine_comedy, dante_alighieri).
concept(gustave_doré).
related_to(gustave_doré, dante_alighieri).
concept(ts_eliot).
related_to(ts_eliot, dante_alighieri).
concept(ezra_pound).
related_to(ezra_pound, dante_alighieri).
concept(influence_on_western_literature).
related_to(influence_on_western_literature, dante_alighieri).
written_by(the_divine_comedy, dante_alighieri).
% Explanation: The Divine Comedy is Dante's epic poem.
genre_of(the_divine_comedy, medieval_literature).
% Explanation: The Divine Comedy is a key work of medieval literature.
genre_of(the_divine_comedy, italian_literature).
% Explanation: It is one of the foundational works of Italian literature.
published_in(the_divine_comedy, x1320).
% Explanation: The Divine Comedy was completed and published around 1320.
set_in(the_divine_comedy, afterlife).
% Explanation: The poem is set in the realms of Inferno, Purgatorio, and Paradiso.
part_of(inferno, the_divine_comedy).
% Explanation: Inferno is the first cantica of The Divine Comedy.
part_of(purgatorio, the_divine_comedy).
% Explanation: Purgatorio is the second cantica of The Divine Comedy.
part_of(paradiso, the_divine_comedy).
% Explanation: Paradiso is the third cantica of The Divine Comedy.
protagonist_of(beatrice_portinari, vita_nuova).
% Explanation: Beatrice is central to Dante's collection of poems, Vita Nuova.
protagonist_of(virgil, the_divine_comedy).
% Explanation: Virgil serves as Dante's guide through Hell and Purgatory.
protagonist_of(dante_alighieri, the_divine_comedy).
% Explanation: Dante inserts himself as the protagonist in the poem.
born_in(dante_alighieri, florence).
% Explanation: Dante was born in Florence, Italy.
located_in(florence, italy).
% Explanation: Florence is a city in Italy.
lived_in(dante_alighieri, x13th14th_centuries).
% Explanation: Dante lived from 1265 to 1321, spanning the 13th and 14th centuries.
exiled_from(dante_alighieri, florence).
% Explanation: In 1302, Dante was exiled from Florence.
member_of(dante_alighieri, guelfs).
% Explanation: Dante was a member of the political faction Guelfs.
conflicted_with(dante_alighieri, ghibellines).
% Explanation: The Guelfs opposed the Ghibellines in Florence.
influenced(dante_alighieri, francesco_petrarch).
% Explanation: Dante's works influenced Petrarch, an early Renaissance poet.
influenced(dante_alighieri, giovanni_boccaccio).
% Explanation: Boccaccio wrote about Dante, was influenced by his poetry, and lectured on The Divine Comedy.
influenced(dante_alighieri, ezra_pound).
% Explanation: Modernist poet Ezra Pound drew inspiration from Dante's imagery and style.
influenced(dante_alighieri, ts_eliot).
% Explanation: T.S. Eliot frequently referenced Dante in his poetry and essays.
influenced(the_divine_comedy, dantean_hell).
% Explanation: Dante's depiction of Hell set the standard for later literary and artistic representations.
adapted_into(the_divine_comedy, gustave_dorés_illustrations).
% Explanation: Doré illustrated a famous edition of The Divine Comedy in the 19th century.
adapted_into(the_divine_comedy, opera_and_film_adaptations).
% Explanation: The Divine Comedy has inspired operas, films, novels, and visual arts.
theme(the_divine_comedy, religious_symbolism).
% Explanation: Religious symbolism is prevalent throughout The Divine Comedy.
features(the_divine_comedy, threepart_structure).
% Explanation: The poem is divided into three distinct sections: Inferno, Purgatorio, Paradiso.
written_in(the_divine_comedy, terza_rima).
% Explanation: Dante invented and popularized the terza rima rhyme scheme for this poem.
movement(the_divine_comedy, early_renaissance).
% Explanation: The Divine Comedy bridges the medieval and early Renaissance periods.
movement(dante_alighieri, early_renaissance).
% Explanation: Dante is a precursor and contributor to Renaissance humanism.
written_by(de_monarchia, dante_alighieri).
% Explanation: De Monarchia is Dante's treatise on secular and religious power.
written_by(vita_nuova, dante_alighieri).
% Explanation: Vita Nuova is Dante's early work combining prose and poetry.
written_by(convivio, dante_alighieri).
% Explanation: Convivio is a philosophical and encyclopedic work by Dante.
alternative_title_of(la_commedia, the_divine_comedy).
% Explanation: The work's original title was simply 'Commedia,' later called 'Divina Commedia.'
subject_of(dante_alighieri, giovanni_boccaccios_writings).
% Explanation: Boccaccio wrote the first biography of Dante.
influenced_by(the_divine_comedy, classical_literature).
% Explanation: The poem is heavily influenced by Virgil, Homer, Ovid, etc.
incorporates(the_divine_comedy, biblical_references).
% Explanation: Numerous biblical figures and themes are woven throughout the poem.
represents(the_divine_comedy, humanism).
% Explanation: The poem's focus on the individual's journey reflects early humanistic ideas.
legacy(the_divine_comedy, influence_on_western_literature).
% Explanation: Its structure, themes, and imagery shaped subsequent literature and art.
related_to(the_divine_comedy, the_divine_comedy).
related_to(inferno, the_divine_comedy).
related_to(purgatorio, the_divine_comedy).
related_to(paradiso, the_divine_comedy).
related_to(dante_alighieri, the_divine_comedy).
related_to(florence, the_divine_comedy).
related_to(italy, the_divine_comedy).
concept(x14th_century).
related_to(x14th_century, the_divine_comedy).
concept(beatrice).
related_to(beatrice, the_divine_comedy).
related_to(virgil, the_divine_comedy).
concept(epic_poem).
related_to(epic_poem, the_divine_comedy).
related_to(terza_rima, the_divine_comedy).
related_to(medieval_literature, the_divine_comedy).
related_to(humanism, the_divine_comedy).
related_to(early_renaissance, the_divine_comedy).
concept(christian_theology).
related_to(christian_theology, the_divine_comedy).
concept(afterlife).
related_to(afterlife, the_divine_comedy).
related_to(allegory, the_divine_comedy).
concept(pilgrimage).
related_to(pilgrimage, the_divine_comedy).
related_to(italian_literature, the_divine_comedy).
concept(moral_philosophy).
related_to(moral_philosophy, the_divine_comedy).
concept(heaven).
related_to(heaven, the_divine_comedy).
concept(hell).
related_to(hell, the_divine_comedy).
concept(purgatory).
related_to(purgatory, the_divine_comedy).
concept(canto).
related_to(canto, the_divine_comedy).
concept(divine_justice).
related_to(divine_justice, the_divine_comedy).
concept(la_vita_nuova).
related_to(la_vita_nuova, the_divine_comedy).
concept(paradise_lost).
related_to(paradise_lost, the_divine_comedy).
related_to(ts_eliot, the_divine_comedy).
related_to(gustave_doré, the_divine_comedy).
concept(dante_gabriel_rossetti).
related_to(dante_gabriel_rossetti, the_divine_comedy).
concept(film_adaptations).
related_to(film_adaptations, the_divine_comedy).
concept(opera_adaptations).
related_to(opera_adaptations, the_divine_comedy).
concept(written_by).
related_to(written_by, the_divine_comedy).
concept(published_in).
related_to(published_in, the_divine_comedy).
concept(set_in).
related_to(set_in, the_divine_comedy).
concept(protagonist_of).
related_to(protagonist_of, the_divine_comedy).
concept(genre_of).
related_to(genre_of, the_divine_comedy).
concept(movement).
related_to(movement, the_divine_comedy).
concept(influenced_by).
related_to(influenced_by, the_divine_comedy).
concept(adapted_into).
related_to(adapted_into, the_divine_comedy).
published_in(the_divine_comedy, x14th_century).
% Explanation: The Divine Comedy was composed and circulated in the early 14th century, c. 1308–1321.
consists_of(the_divine_comedy, inferno).
% Explanation: Inferno is the first cantica of The Divine Comedy.
consists_of(the_divine_comedy, purgatorio).
% Explanation: Purgatorio is the second cantica of The Divine Comedy.
consists_of(the_divine_comedy, paradiso).
% Explanation: Paradiso is the third cantica of The Divine Comedy.
part_of(florence, italy).
% Explanation: Florence is a city in Italy.
genre_of(the_divine_comedy, epic_poem).
% Explanation: The Divine Comedy is considered an epic poem.
movement(the_divine_comedy, medieval_literature).
% Explanation: The Divine Comedy is a seminal work in Medieval European literature.
form_of(the_divine_comedy, terza_rima).
% Explanation: The Divine Comedy is written in terza rima (interlocking three-line rhyme scheme).
theme_of(the_divine_comedy, christian_theology).
% Explanation: The work is deeply rooted in Christian theological concepts.
theme_of(the_divine_comedy, allegory).
% Explanation: The Divine Comedy is an allegorical journey representing spiritual salvation.
protagonist_of(dante, the_divine_comedy).
% Explanation: Dante is both the author and principal character of the poem.
character_in(virgil, the_divine_comedy).
% Explanation: Virgil is a major guide and character in the poem.
protagonist_of(virgil, inferno).
% Explanation: Virgil guides Dante through Hell (Inferno).
character_in(beatrice, the_divine_comedy).
% Explanation: Beatrice is both a character and spiritual guide through Paradise.
influenced_by(dante_alighieri, virgil_author_of_the_aeneid).
% Explanation: Dante’s style and thematic structure are influenced by Virgil’s Aeneid.
influenced(the_divine_comedy, paradise_lost).
% Explanation: Milton’s Paradise Lost was heavily influenced by Dante’s themes and structure.
influenced(the_divine_comedy, ts_eliot).
% Explanation: T.S. Eliot referenced Dante extensively in his poetry.
adapted_into(the_divine_comedy, gustave_doré_illustrations).
% Explanation: Gustave Doré illustrated The Divine Comedy in the 19th century.
adapted_into(the_divine_comedy, dante_gabriel_rossetti_translations).
% Explanation: Rossetti translated and illustrated the poem.
adapted_into(the_divine_comedy, film_adaptations).
% Explanation: The Divine Comedy has inspired multiple film adaptations.
adapted_into(the_divine_comedy, opera_adaptations).
% Explanation: The poem has been adapted into various operatic works.
consists_of(the_divine_comedy, canto).
% Explanation: The structure of the poem is divided into canti (canticles).
set_in(inferno, hell).
% Explanation: Inferno is set in the Christian conception of Hell.
set_in(purgatorio, purgatory).
% Explanation: Purgatorio is set in Purgatory.
set_in(paradiso, heaven).
% Explanation: Paradiso is set in Heaven.
subject_of(the_divine_comedy, divine_justice).
% Explanation: A theme running through the poem is Divine Justice.
author_of(dante_alighieri, la_vita_nuova).
% Explanation: Dante wrote La Vita Nuova, which explores his love for Beatrice.
influenced(la_vita_nuova, the_divine_comedy).
% Explanation: Dante’s earlier work La Vita Nuova influenced the representation of Beatrice in The Divine Comedy.
