% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Emily Dickinson
% Max depth: 1, Max related topics per node: 1

concept(emily_dickinson).
related_to(emily_dickinson, emily_dickinson).
concept(collected_poems).
related_to(collected_poems, emily_dickinson).
concept(life_in_amherst_massachusetts).
related_to(life_in_amherst_massachusetts, emily_dickinson).
concept(x19thcentury_american_poetry).
related_to(x19thcentury_american_poetry, emily_dickinson).
concept(romanticism).
related_to(romanticism, emily_dickinson).
concept(transcendentalism).
related_to(transcendentalism, emily_dickinson).
concept(death).
related_to(death, emily_dickinson).
concept(immortality).
related_to(immortality, emily_dickinson).
concept(nature).
related_to(nature, emily_dickinson).
concept(reclusion).
related_to(reclusion, emily_dickinson).
concept(manuscript_envelope_poems).
related_to(manuscript_envelope_poems, emily_dickinson).
concept(thomas_wentworth_higginson).
related_to(thomas_wentworth_higginson, emily_dickinson).
concept(mabel_loomis_todd).
related_to(mabel_loomis_todd, emily_dickinson).
concept(posthumous_publication).
related_to(posthumous_publication, emily_dickinson).
concept(innovative_poetic_form).
related_to(innovative_poetic_form, emily_dickinson).
concept(dashes_and_unusual_capitalization).
related_to(dashes_and_unusual_capitalization, emily_dickinson).
concept(influenced_by_emerson).
related_to(influenced_by_emerson, emily_dickinson).
concept(influenced_sylvia_plath).
related_to(influenced_sylvia_plath, emily_dickinson).
concept(influenced_by_the_bible).
related_to(influenced_by_the_bible, emily_dickinson).
concept(first_series_of_poems_1890).
related_to(first_series_of_poems_1890, emily_dickinson).
concept(second_series_of_poems_1891).
related_to(second_series_of_poems_1891, emily_dickinson).
concept(x1914_complete_poems).
related_to(x1914_complete_poems, emily_dickinson).
concept(themes_of_religion).
related_to(themes_of_religion, emily_dickinson).
concept(emily_brontë).
related_to(emily_brontë, emily_dickinson).
concept(letterwriting).
related_to(letterwriting, emily_dickinson).
concept(american_civil_war).
related_to(american_civil_war, emily_dickinson).
concept(x19thcentury_american_women_writers).
related_to(x19thcentury_american_women_writers, emily_dickinson).
concept(modernist_poetry).
related_to(modernist_poetry, emily_dickinson).
concept(poetry_collections).
related_to(poetry_collections, emily_dickinson).
concept(harvard_university_press_1955_edition).
related_to(harvard_university_press_1955_edition, emily_dickinson).
concept(susan_gilbert_dickinson).
related_to(susan_gilbert_dickinson, emily_dickinson).
concept(family_relationships).
related_to(family_relationships, emily_dickinson).
concept(correspondence_with_literary_figures).
related_to(correspondence_with_literary_figures, emily_dickinson).
written_by(collected_poems, emily_dickinson).
% Explanation: Emily Dickinson authored the poems later compiled into the Collected Poems volumes.
published_in(collected_poems, x1890).
% Explanation: The first posthumous collection of her poems was published in 1890.
lived_in(emily_dickinson, amherst_massachusetts).
% Explanation: Dickinson was born, lived, and died in Amherst, Massachusetts.
born_in(emily_dickinson, x1830).
% Explanation: Dickinson was born in 1830.
died_in(emily_dickinson, x1886).
% Explanation: Dickinson died in 1886.
literary_movement(emily_dickinson, romanticism).
% Explanation: Her poetry is often aligned with Romanticism due to its focus on nature, emotion, and the individual.
literary_movement(emily_dickinson, transcendentalism).
% Explanation: She was influenced by Transcendentalist ideas of spirituality and nature.
genre_of(emily_dickinson, x19thcentury_american_poetry).
% Explanation: Dickinson is a central figure in nineteenth-century American poetry.
theme_of(emily_dickinson, death).
% Explanation: Death is one of the most prominent recurring themes in her poetry.
theme_of(emily_dickinson, immortality).
% Explanation: Immortality is another major theme present in her works.
theme_of(emily_dickinson, nature).
% Explanation: The natural world and its metaphysical meanings are a frequent subject.
theme_of(emily_dickinson, religion).
% Explanation: Dickinson often explored themes related to belief, doubt, and faith.
lifestyle(emily_dickinson, reclusion).
% Explanation: She became notably reclusive, especially in her later years.
authored(emily_dickinson, manuscript_envelope_poems).
% Explanation: Dickinson handwrote many poems on scraps and envelopes, which were later studied as unique manuscripts.
correspondent_of(thomas_wentworth_higginson, emily_dickinson).
% Explanation: Higginson was a longtime correspondent and advisor to Dickinson.
editor_of(thomas_wentworth_higginson, collected_poems).
% Explanation: Higginson co-edited the first posthumous collection of Dickinson's poetry.
editor_of(mabel_loomis_todd, collected_poems).
% Explanation: Mabel Loomis Todd also co-edited the first published volumes.
published_in(collected_poems, x1891).
% Explanation: Second Series was published in 1891.
published_in(collected_poems, x1914).
% Explanation: A more complete collection of poems was published in 1914.
published_in(collected_poems, x1955).
% Explanation: Harvard University Press published the authoritative edition of Dickinson's works in 1955.
innovated(emily_dickinson, innovative_poetic_form).
% Explanation: Her poetry is known for innovative structures, slant rhyme, and unique style.
characteristic_of(emily_dickinson, dashes_and_unusual_capitalization).
% Explanation: Her poetry famously features dashes and unconventional capitalization.
influenced_by(emily_dickinson, ralph_waldo_emerson).
% Explanation: Dickinson was influenced by Emerson's poetry and Transcendentalist philosophy.
influenced_by(emily_dickinson, the_bible).
% Explanation: Biblical language and themes appear in many Dickinson poems.
influenced_by(emily_dickinson, emily_brontë).
% Explanation: She admired the work of Emily Brontë and was influenced by her poetry.
influenced_by(modernist_poetry, emily_dickinson).
% Explanation: Her innovative language and themes had a profound impact on Modernist poets.
influenced_by(sylvia_plath, emily_dickinson).
% Explanation: Sylvia Plath explicitly cited Dickinson as a poetic influence.
contains(poetry_collections, manuscript_envelope_poems).
% Explanation: Later poetry collections have included Dickinson's envelope poems.
corresponded_with(emily_dickinson, susan_gilbert_dickinson).
% Explanation: She wrote many letters and poems to her sister-in-law, Susan.
family_relationship(emily_dickinson, susan_gilbert_dickinson).
% Explanation: Susan was Emily's sister-in-law and close confidante.
family_relationship(emily_dickinson, austin_dickinson).
% Explanation: Austin was Emily Dickinson's brother.
family_relationship(emily_dickinson, lavinia_dickinson).
% Explanation: Lavinia (Vinnie) was Emily Dickinson's sister, who played a role in preserving her writings.
time_period(emily_dickinson, american_civil_war).
% Explanation: Dickinson wrote many poems during the time of the Civil War.
represented_by(emily_dickinson, x19thcentury_american_women_writers).
% Explanation: She represents one of the most prominent women writers in nineteenth-century America.
recipient_of(emily_dickinson, correspondence_with_literary_figures).
% Explanation: She exchanged letters with several prominent thinkers and writers of her time.
adapted_into(collected_poems, broadwayfilm_adaptations).
% Explanation: Her life and work have been adapted into various plays and films.
published(harvard_university_press_1955_edition, authoritative_collected_poems).
% Explanation: The definitive collection of her poems was published by HUP in 1955.
legacy(emily_dickinson, enduring_influence_on_englishlanguage_poetry).
% Explanation: Her style and themes have remained influential in subsequent generations.
concept(themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(death, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(immortality, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(emily_dickinson, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(emily_dickinsons_poetry).
related_to(emily_dickinsons_poetry, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(afterlife).
related_to(afterlife, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(personification_of_death).
related_to(personification_of_death, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(transcendence).
related_to(transcendence, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(religious_doubt).
related_to(religious_doubt, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(acceptance_of_mortality).
related_to(acceptance_of_mortality, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(nature, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(symbolism).
related_to(symbolism, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(psychological_exploration).
related_to(psychological_exploration, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(eternal_life).
related_to(eternal_life, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(x19thcentury_american_poetry, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(amherst_massachusetts).
related_to(amherst_massachusetts, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(civil_war_era).
related_to(civil_war_era, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(literary_modernism).
related_to(literary_modernism, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(transcendentalism, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(poem_479_because_i_could_not_stop_for_death).
related_to(poem_479_because_i_could_not_stop_for_death, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(poem_712_i_heard_a_fly_buzzwhen_i_died).
related_to(poem_712_i_heard_a_fly_buzzwhen_i_died, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(poem_465_i_felt_a_funeral_in_my_brain).
related_to(poem_465_i_felt_a_funeral_in_my_brain, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(publication_of_dickinsons_poems_1890).
related_to(publication_of_dickinsons_poems_1890, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(helen_hunt_jackson).
related_to(helen_hunt_jackson, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
related_to(thomas_wentworth_higginson, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(posthumous_fame).
related_to(posthumous_fame, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(influence_on_20thcentury_poetry).
related_to(influence_on_20thcentury_poetry, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
concept(female_voice_in_literature).
related_to(female_voice_in_literature, themes_of_death_and_immortality_in_emily_dickinsons_poetry).
explores(emily_dickinsons_poetry, death).
% Explanation: Death is a central and recurring theme throughout Dickinson's poetry.
explores(emily_dickinsons_poetry, immortality).
% Explanation: Her poems often meditate on the possibilities and conceptions of life after death.
analyzes(emily_dickinsons_poetry, afterlife).
% Explanation: The poetry delves into different views on what may happen after death.
utilizes(emily_dickinsons_poetry, personification_of_death).
% Explanation: Dickinson personifies Death, often making it a character in her poems.
considers(emily_dickinsons_poetry, transcendence).
% Explanation: Her poems question and challenge the boundaries between life and death.
displays(emily_dickinsons_poetry, religious_doubt).
% Explanation: She interrogates traditional Christian beliefs about death and the afterlife.
promotes(emily_dickinsons_poetry, acceptance_of_mortality).
% Explanation: Dickinson’s poems often move toward an honest confrontation with mortality.
draws_from(emily_dickinsons_poetry, nature).
% Explanation: Natural imagery is used to depict death and immortality.
makes_extensive_use_of(emily_dickinsons_poetry, symbolism).
% Explanation: Dickinson uses symbols (flies, horses, funerals) to represent aspects of death.
incorporates(emily_dickinsons_poetry, psychological_exploration).
% Explanation: Her poetry reflects the inner workings of the human mind facing mortality.
contemplates(emily_dickinsons_poetry, eternal_life).
% Explanation: There is consideration of eternity as an alternate state post-death.
born_in(emily_dickinson, amherst_massachusetts).
% Explanation: Dickinson spent her life in Amherst, tying her context to this specific location.
set_in(emily_dickinsons_poetry, x19thcentury_american_poetry).
% Explanation: Her poetry reflects the themes and style of American poetry written in the 1800s.
written_during(emily_dickinsons_poetry, civil_war_era).
% Explanation: Much of her work was composed during and after the American Civil War (1861-1865).
engages_with(emily_dickinsons_poetry, transcendentalism).
% Explanation: Her work shows influence from and dialogue with ideas of transcendence and the soul.
anticipates(emily_dickinsons_poetry, literary_modernism).
% Explanation: Her themes and experimental style foreshadow key aspects of Modernist literature.
written_by(poem_479_because_i_could_not_stop_for_death, emily_dickinson).
% Explanation: This iconic poem demonstrates her complex treatment of death.
written_by(poem_712_i_heard_a_fly_buzzwhen_i_died, emily_dickinson).
% Explanation: Another significant work centered on the moment of death.
written_by(poem_465_i_felt_a_funeral_in_my_brain, emily_dickinson).
% Explanation: This poem explores the psychological aspects of death.
symbolizes(poem_479_because_i_could_not_stop_for_death, personification_of_death).
% Explanation: Death is personified as a courteous suitor.
explores(poem_712_i_heard_a_fly_buzzwhen_i_died, religious_doubt).
% Explanation: The intruding fly symbolizes the interruption of expected religious certainty.
genre_of(emily_dickinsons_poetry, x19thcentury_american_poetry).
% Explanation: Her works are part of this broader genre.
author_of(emily_dickinson, emily_dickinsons_poetry).
% Explanation: She is the sole creator of these works.
associated_with(emily_dickinson, female_voice_in_literature).
% Explanation: Her poetry is significant for its pioneering female literary voice.
corresponded_with(emily_dickinson, helen_hunt_jackson).
% Explanation: Helen Hunt Jackson encouraged Dickinson to publish.
mentored_by(emily_dickinson, thomas_wentworth_higginson).
% Explanation: Higginson provided literary criticism and edited her poems posthumously.
published_in(emily_dickinsons_poetry, publication_of_dickinsons_poems_1890).
% Explanation: The first collection of Dickinson's poems, edited by Higginson and Todd, appeared in 1890.
influenced(emily_dickinsons_poetry, influence_on_20thcentury_poetry).
% Explanation: Her themes and style profoundly affected later poets.
contributed_to(emily_dickinsons_poetry, posthumous_fame).
% Explanation: Her reputation grew significantly only after her death.
movement(emily_dickinsons_poetry, x19thcentury_american_poetry).
% Explanation: Dickinson’s poetry is considered a core contribution to this literary movement.
