% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: The French Revolution
% Max depth: 1, Max related topics per node: 1

concept(the_french_revolution).
concept(french_revolution).
related_to(french_revolution, the_french_revolution).
concept(estatesgeneral).
related_to(estatesgeneral, the_french_revolution).
concept(national_assembly).
related_to(national_assembly, the_french_revolution).
concept(louis_xvi).
related_to(louis_xvi, the_french_revolution).
concept(marie_antoinette).
related_to(marie_antoinette, the_french_revolution).
concept(maximilien_robespierre).
related_to(maximilien_robespierre, the_french_revolution).
concept(georges_danton).
related_to(georges_danton, the_french_revolution).
concept(jeanpaul_marat).
related_to(jeanpaul_marat, the_french_revolution).
concept(jacques_necker).
related_to(jacques_necker, the_french_revolution).
concept(declaration_of_the_rights_of_man_and_of_the_citizen).
related_to(declaration_of_the_rights_of_man_and_of_the_citizen, the_french_revolution).
concept(storming_of_the_bastille).
related_to(storming_of_the_bastille, the_french_revolution).
concept(womens_march_on_versailles).
related_to(womens_march_on_versailles, the_french_revolution).
concept(reign_of_terror).
related_to(reign_of_terror, the_french_revolution).
concept(thermidorian_reaction).
related_to(thermidorian_reaction, the_french_revolution).
concept(directory).
related_to(directory, the_french_revolution).
concept(consulate).
related_to(consulate, the_french_revolution).
concept(napoleon_bonaparte).
related_to(napoleon_bonaparte, the_french_revolution).
concept(jacobins).
related_to(jacobins, the_french_revolution).
concept(girondins).
related_to(girondins, the_french_revolution).
concept(kingdom_of_france).
related_to(kingdom_of_france, the_french_revolution).
concept(first_french_republic).
related_to(first_french_republic, the_french_revolution).
concept(execution_of_louis_xvi).
related_to(execution_of_louis_xvi, the_french_revolution).
concept(execution_of_marie_antoinette).
related_to(execution_of_marie_antoinette, the_french_revolution).
concept(committee_of_public_safety).
related_to(committee_of_public_safety, the_french_revolution).
concept(great_fear).
related_to(great_fear, the_french_revolution).
concept(tennis_court_oath).
related_to(tennis_court_oath, the_french_revolution).
concept(civil_constitution_of_the_clergy).
related_to(civil_constitution_of_the_clergy, the_french_revolution).
concept(guillotine).
related_to(guillotine, the_french_revolution).
concept(emigres).
related_to(emigres, the_french_revolution).
concept(sansculottes).
related_to(sansculottes, the_french_revolution).
concept(paris_commune).
related_to(paris_commune, the_french_revolution).
concept(war_of_the_first_coalition).
related_to(war_of_the_first_coalition, the_french_revolution).
concept(the_enlightenment).
related_to(the_enlightenment, the_french_revolution).
concept(versailles).
related_to(versailles, the_french_revolution).
concept(paris).
related_to(paris, the_french_revolution).
concept(bastille).
related_to(bastille, the_french_revolution).
concept(x1798_egyptian_campaign).
related_to(x1798_egyptian_campaign, the_french_revolution).
concept(charlotte_corday).
related_to(charlotte_corday, the_french_revolution).
occurred_in(french_revolution, x17891799).
% Explanation: The French Revolution spanned from 1789 to 1799.
convened_in(estatesgeneral, x1789).
% Explanation: The Estates-General was convened in May 1789.
preceded(estatesgeneral, national_assembly).
% Explanation: The National Assembly arose from the Estates-General.
declared_in(national_assembly, june_1789).
% Explanation: The National Assembly was declared in June 1789.
occurred_in(tennis_court_oath, june_1789).
% Explanation: The Tennis Court Oath was taken in June 1789 by the National Assembly.
occurred_in(storming_of_the_bastille, july_14_1789).
% Explanation: The Storming of the Bastille occurred on July 14, 1789.
occurred_in(womens_march_on_versailles, october_1789).
% Explanation: The Women's March on Versailles took place in October 1789.
occurred_in(great_fear, julyaugust_1789).
% Explanation: The Great Fear spanned July and August 1789.
proclaimed_in(declaration_of_the_rights_of_man_and_of_the_citizen, august_1789).
% Explanation: The Declaration was adopted in August 1789.
ruled_during(louis_xvi, x17741792).
% Explanation: Louis XVI ruled France from 1774 to 1792.
executed_in(louis_xvi, execution_of_louis_xvi).
% Explanation: Louis XVI was executed in January 1793.
occurred_in(execution_of_louis_xvi, x1793).
% Explanation: Louis XVI was executed in 1793.
executed_in(marie_antoinette, execution_of_marie_antoinette).
% Explanation: Marie Antoinette was executed in October 1793.
occurred_in(execution_of_marie_antoinette, x1793).
% Explanation: Marie Antoinette was executed in 1793.
contemporary_of(jacques_necker, louis_xvi).
% Explanation: Necker, minister of finance, was contemporary of Louis XVI.
supported(jacques_necker, estatesgeneral).
% Explanation: Necker supported convening the Estates-General.
occurred_in(reign_of_terror, x17931794).
% Explanation: The Reign of Terror lasted from September 1793 to July 1794.
ruled_during(maximilien_robespierre, reign_of_terror).
% Explanation: Robespierre was a leading figure during the Reign of Terror.
led_by(committee_of_public_safety, maximilien_robespierre).
% Explanation: Robespierre was a leading member of the Committee.
governed_during(committee_of_public_safety, reign_of_terror).
% Explanation: The Committee led the government during the Reign of Terror.
member_of(jacobin, maximilien_robespierre).
% Explanation: Robespierre was a prominent leader of the Jacobin Club.
rival_of(jacobins, girondins).
% Explanation: The Jacobins and Girondins were rival political factions.
purged_in(girondins, reign_of_terror).
% Explanation: Many Girondins were executed during the Reign of Terror.
occurred_in(thermidorian_reaction, july_1794).
% Explanation: Thermidorian Reaction started in July 1794.
overthrew(thermidorian_reaction, maximilien_robespierre).
% Explanation: Robespierre was executed during the Thermidorian Reaction.
succeeded(directory, thermidorian_reaction).
% Explanation: The Directory became the new government after the Thermidorian Reaction.
governed_during(directory, x17951799).
% Explanation: The Directory governed from 1795 until 1799.
succeeded(consulate, directory).
% Explanation: The Consulate replaced the Directory in 1799.
headed(napoleon_bonaparte, consulate).
% Explanation: Napoleon became First Consul in 1799.
born_in(napoleon_bonaparte, x1769).
% Explanation: Napoleon was born in 1769.
contemporary_of(napoleon_bonaparte, maximilien_robespierre).
% Explanation: Napoleon and Robespierre lived during the same period.
proclaimed_in(first_french_republic, september_1792).
% Explanation: The First Republic replaced the monarchy in September 1792.
succeeded_by(kingdom_of_france, first_french_republic).
% Explanation: The monarchy was abolished and succeeded by the republic.
located_in(paris, france).
% Explanation: Paris is the capital of France and central to the Revolution.
located_in(bastille, paris).
% Explanation: The Bastille prison was in Paris.
located_in(versailles, france).
% Explanation: Royal palace near Paris where the Estates-General was held.
occurred_in(war_of_the_first_coalition, x17921797).
% Explanation: France fought European powers as a result of the Revolution.
used_in(guillotine, reign_of_terror).
% Explanation: The guillotine became a symbol of the Reign of Terror's executions.
assassinated_by(jeanpaul_marat, charlotte_corday).
% Explanation: Marat was assassinated in July 1793 by Corday.
contemporary_of(jeanpaul_marat, georges_danton).
% Explanation: Marat and Danton were political allies at times.
executed_in(georges_danton, x1794).
% Explanation: Danton was executed in April 1794.
executed_in(maximilien_robespierre, july_1794).
% Explanation: Robespierre was executed in July 1794.
active_in(sansculottes, paris).
% Explanation: The Sans-culottes were militant working-class revolutionaries in Paris.
governed(paris_commune, paris).
% Explanation: The Paris Commune was the city's revolutionary government.
active_in(paris_commune, french_revolution).
% Explanation: The Paris Commune played a major role during the Revolution.
passed_in(civil_constitution_of_the_clergy, x1790).
% Explanation: The Civil Constitution passed in 1790 reorganized the French church.
influenced(enlightenment, french_revolution).
% Explanation: Enlightenment ideas inspired revolutionary principles.
fled_from(emigres, france).
% Explanation: Emigres were nobles who fled France during the Revolution.
led_by(x1798_egyptian_campaign, napoleon_bonaparte).
% Explanation: Napoleon led the Egyptian Campaign in 1798.
concept(the_reign_of_terror).
related_to(reign_of_terror, the_reign_of_terror).
related_to(french_revolution, the_reign_of_terror).
concept(national_convention).
related_to(national_convention, the_reign_of_terror).
related_to(committee_of_public_safety, the_reign_of_terror).
related_to(maximilien_robespierre, the_reign_of_terror).
related_to(georges_danton, the_reign_of_terror).
related_to(jeanpaul_marat, the_reign_of_terror).
related_to(louis_xvi, the_reign_of_terror).
related_to(marie_antoinette, the_reign_of_terror).
related_to(guillotine, the_reign_of_terror).
concept(executions).
related_to(executions, the_reign_of_terror).
concept(law_of_suspects).
related_to(law_of_suspects, the_reign_of_terror).
related_to(thermidorian_reaction, the_reign_of_terror).
related_to(paris, the_reign_of_terror).
concept(france).
related_to(france, the_reign_of_terror).
concept(revolutionary_tribunals).
related_to(revolutionary_tribunals, the_reign_of_terror).
concept(republic_of_virtue).
related_to(republic_of_virtue, the_reign_of_terror).
concept(fall_of_robespierre).
related_to(fall_of_robespierre, the_reign_of_terror).
related_to(jacobins, the_reign_of_terror).
concept(gironde_girondins).
related_to(gironde_girondins, the_reign_of_terror).
concept(montagnards).
related_to(montagnards, the_reign_of_terror).
concept(federalist_revolts).
related_to(federalist_revolts, the_reign_of_terror).
related_to(emigres, the_reign_of_terror).
concept(counterrevolutionaries).
related_to(counterrevolutionaries, the_reign_of_terror).
concept(september_massacres).
related_to(september_massacres, the_reign_of_terror).
concept(x1793).
related_to(x1793, the_reign_of_terror).
concept(x1794).
related_to(x1794, the_reign_of_terror).
part_of(reign_of_terror, french_revolution).
% Explanation: The Reign of Terror was a phase within the broader French Revolution.
administered_by(reign_of_terror, committee_of_public_safety).
% Explanation: The Committee of Public Safety oversaw the Reign of Terror.
dominated_by(_committee_of_public_safety, maximilien_robespierre).
% Explanation: Robespierre became the most influential member of the Committee of Public Safety during the Terror.
born_in(maximilien_robespierre, x1758).
% Explanation: Robespierre was born in 1758.
died_in(maximilien_robespierre, x1794).
% Explanation: Robespierre was executed in 1794 after being arrested during the Thermidorian Reaction.
born_in(georges_danton, x1759).
% Explanation: Danton was born in 1759.
died_in(georges_danton, x1794).
% Explanation: Danton was executed during the Terror in 1794.
born_in(jeanpaul_marat, x1743).
% Explanation: Marat was born in 1743.
died_in(jeanpaul_marat, x1793).
% Explanation: Marat was assassinated in 1793.
born_in(louis_xvi, x1754).
% Explanation: Louis XVI was born in 1754.
died_in(louis_xvi, x1793).
% Explanation: Louis XVI was executed by guillotine in January 1793.
born_in(marie_antoinette, x1755).
% Explanation: Marie Antoinette was born in 1755.
died_in(marie_antoinette, x1793).
% Explanation: Marie Antoinette was executed by guillotine in October 1793.
centered_in(reign_of_terror, paris).
% Explanation: Paris was the primary center of political activity and executions during the Terror.
used_in(guillotine, executions).
% Explanation: The guillotine was the main instrument of execution during the Terror.
perpetrated_by(executions, revolutionary_tribunals).
% Explanation: Executions during the Terror were ordered by Revolutionary Tribunals.
established_by(revolutionary_tribunals, national_convention).
% Explanation: The National Convention established the Revolutionary Tribunals to try suspects.
preceded(reign_of_terror, thermidorian_reaction).
% Explanation: The Reign of Terror ended with the Thermidorian Reaction.
occurred_in(fall_of_robespierre, x27_july_1794).
% Explanation: Robespierre was arrested and executed on 27-28 July 1794.
passed_in(law_of_suspects, september_1793).
% Explanation: The Law of Suspects, enabling the arrest of suspected enemies, was passed in September 1793.
characterized_by(reign_of_terror, law_of_suspects).
% Explanation: The Law of Suspects was a key component of the Terror's legal repression.
dominated(jacobins, committee_of_public_safety).
% Explanation: The Jacobins, particularly the Montagnards, dominated the Committee during the Terror.
opposed(montagnards, gironde_girondins).
% Explanation: Montagnards and Girondins were rival factions in the National Convention.
purged_in(gironde_girondins, june_1793).
% Explanation: Girondins were purged from the Convention just before the Terror began.
occurred_in(federalist_revolts, x1793).
% Explanation: Revolts against Jacobin central authority broke out in several regions in 1793.
executed_by(counterrevolutionaries, revolutionary_tribunals).
% Explanation: Alleged counter-revolutionaries were executed by special tribunals.
envisioned_by(republic_of_virtue, maximilien_robespierre).
% Explanation: Robespierre promoted the idea of a 'Republic of Virtue' as the Terror's justification.
symbol_of(guillotine, reign_of_terror).
% Explanation: The guillotine became the enduring symbol of the Terror.
preceded(september_massacres, reign_of_terror).
% Explanation: The September Massacres of 1792 foreshadowed the mass violence of the Terror.
contemporary_of(maximilien_robespierre, georges_danton).
% Explanation: Both were revolutionary leaders active during the Terror.
contemporary_of(maximilien_robespierre, jeanpaul_marat).
% Explanation: Both were radical leaders and key figures in the Jacobin movement.
executed_by(george_danton, committee_of_public_safety).
% Explanation: Danton was executed as a moderate by the Committee led by Robespierre.
