% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Gabriel Garcia Marquez
% Max depth: 1, Max related topics per node: 1

concept(gabriel_garcia_marquez).
related_to(gabriel_garcia_marquez, gabriel_garcia_marquez).
concept(magic_realism).
related_to(magic_realism, gabriel_garcia_marquez).
concept(one_hundred_years_of_solitude).
related_to(one_hundred_years_of_solitude, gabriel_garcia_marquez).
concept(love_in_the_time_of_cholera).
related_to(love_in_the_time_of_cholera, gabriel_garcia_marquez).
concept(chronicle_of_a_death_foretold).
related_to(chronicle_of_a_death_foretold, gabriel_garcia_marquez).
concept(the_autumn_of_the_patriarch).
related_to(the_autumn_of_the_patriarch, gabriel_garcia_marquez).
concept(the_general_in_his_labyrinth).
related_to(the_general_in_his_labyrinth, gabriel_garcia_marquez).
concept(leaf_storm).
related_to(leaf_storm, gabriel_garcia_marquez).
concept(colombia).
related_to(colombia, gabriel_garcia_marquez).
concept(aracataca).
related_to(aracataca, gabriel_garcia_marquez).
concept(macondo).
related_to(macondo, gabriel_garcia_marquez).
concept(latin_american_boom).
related_to(latin_american_boom, gabriel_garcia_marquez).
concept(nobel_prize_in_literature).
related_to(nobel_prize_in_literature, gabriel_garcia_marquez).
concept(cuban_revolution).
related_to(cuban_revolution, gabriel_garcia_marquez).
concept(fidel_castro).
related_to(fidel_castro, gabriel_garcia_marquez).
concept(william_faulkner).
related_to(william_faulkner, gabriel_garcia_marquez).
concept(jorge_luis_borges).
related_to(jorge_luis_borges, gabriel_garcia_marquez).
concept(miguel_de_cervantes).
related_to(miguel_de_cervantes, gabriel_garcia_marquez).
concept(la_violencia).
related_to(la_violencia, gabriel_garcia_marquez).
concept(journalism).
related_to(journalism, gabriel_garcia_marquez).
concept(spanish_language).
related_to(spanish_language, gabriel_garcia_marquez).
concept(garcía_márquezs_influences).
related_to(garcía_márquezs_influences, gabriel_garcia_marquez).
concept(modern_latin_american_literature).
related_to(modern_latin_american_literature, gabriel_garcia_marquez).
concept(magic_realism_in_literature).
related_to(magic_realism_in_literature, gabriel_garcia_marquez).
concept(melquíades).
related_to(melquíades, gabriel_garcia_marquez).
concept(ursula_iguarán).
related_to(ursula_iguarán, gabriel_garcia_marquez).
concept(josé_arcadio_buendía).
related_to(josé_arcadio_buendía, gabriel_garcia_marquez).
concept(florentino_ariza).
related_to(florentino_ariza, gabriel_garcia_marquez).
concept(fermina_daza).
related_to(fermina_daza, gabriel_garcia_marquez).
concept(adaptations_filmsseries).
related_to(adaptations_filmsseries, gabriel_garcia_marquez).
concept(x1992_nobel_prize_speech).
related_to(x1992_nobel_prize_speech, gabriel_garcia_marquez).
written_by(one_hundred_years_of_solitude, gabriel_garcia_marquez).
% Explanation: Marquez authored this landmark 1967 novel.
written_by(love_in_the_time_of_cholera, gabriel_garcia_marquez).
% Explanation: Another major novel by Marquez, published in 1985.
written_by(chronicle_of_a_death_foretold, gabriel_garcia_marquez).
% Explanation: A 1981 novel by Marquez.
written_by(the_autumn_of_the_patriarch, gabriel_garcia_marquez).
% Explanation: A novel examining dictatorship in Latin America, published 1975.
written_by(the_general_in_his_labyrinth, gabriel_garcia_marquez).
% Explanation: A 1989 fictionalized biography of Simón Bolívar.
written_by(leaf_storm, gabriel_garcia_marquez).
% Explanation: Marquez's first novella, from 1955.
published_in(one_hundred_years_of_solitude, x1967).
% Explanation: The novel was published in 1967.
published_in(love_in_the_time_of_cholera, x1985).
% Explanation: The novel was published in 1985.
published_in(chronicle_of_a_death_foretold, x1981).
% Explanation: The novel was published in 1981.
born_in(gabriel_garcia_marquez, aracataca).
% Explanation: He was born in this Colombian town in 1927.
set_in(one_hundred_years_of_solitude, macondo).
% Explanation: The story takes place in the fictional town of Macondo.
inspired_by(macondo, aracataca).
% Explanation: Macondo is based on Marquez's hometown.
represents_country(gabriel_garcia_marquez, colombia).
% Explanation: He is a prominent Colombian literary figure.
contributed_to(gabriel_garcia_marquez, magic_realism).
% Explanation: Marquez is a central figure in the magic realism movement.
genre_of(one_hundred_years_of_solitude, magic_realism).
% Explanation: The novel is a classic example of magic realism.
member_of(gabriel_garcia_marquez, latin_american_boom).
% Explanation: He was a leading figure during the Latin American literary Boom of the 1960s-70s.
includes_author(latin_american_boom, gabriel_garcia_marquez).
% Explanation: A core member among other influential novelists.
won_prize(gabriel_garcia_marquez, nobel_prize_in_literature).
% Explanation: He was awarded the Nobel Prize in 1982.
associated_with(gabriel_garcia_marquez, journalism).
% Explanation: He worked as a journalist throughout his life.
influenced_by(gabriel_garcia_marquez, william_faulkner).
% Explanation: Faulkner's techniques and regionalism influenced Marquez's style.
influenced_by(gabriel_garcia_marquez, jorge_luis_borges).
% Explanation: Borges inspired Marquez's experiments with time and reality.
influenced_by(gabriel_garcia_marquez, miguel_de_cervantes).
% Explanation: The Spanish literary tradition, especially Cervantes, shaped Marquez's prose.
influenced_by(gabriel_garcia_marquez, la_violencia).
% Explanation: This period of Colombian civil war impacted his themes.
contemporary_of(gabriel_garcia_marquez, fidel_castro).
% Explanation: They had a notable friendship and shared political interests.
influenced_by(gabriel_garcia_marquez, cuban_revolution).
% Explanation: Cuban politics informed many of his journalistic and literary positions.
movement(one_hundred_years_of_solitude, magic_realism).
% Explanation: The novel defined and popularized magic realism.
historical_period(latin_american_boom, x1960s1970s).
% Explanation: This was the time of the Boom.
wrote_in_language(gabriel_garcia_marquez, spanish_language).
% Explanation: All his major works were written in Spanish.
protagonist_of(one_hundred_years_of_solitude, josé_arcadio_buendía).
% Explanation: José Arcadio Buendía is a patriarch in the novel.
protagonist_of(one_hundred_years_of_solitude, ursula_iguarán).
% Explanation: Ursula is the matriarch and a key figure in the novel.
protagonist_of(one_hundred_years_of_solitude, melquíades).
% Explanation: Melquíades is a mysterious character central to Macondo's mythical history.
protagonist_of(love_in_the_time_of_cholera, florentino_ariza).
% Explanation: Florentino is the main protagonist.
protagonist_of(love_in_the_time_of_cholera, fermina_daza).
% Explanation: Fermina is the novel's principal female lead.
adapted_into(one_hundred_years_of_solitude, netflix_series).
% Explanation: A planned adaptation by Netflix announced in 2019.
adapted_into(love_in_the_time_of_cholera, x2007_film).
% Explanation: A film adaptation of the novel released in 2007.
legacy_in(gabriel_garcia_marquez, modern_latin_american_literature).
% Explanation: He remains one of its most influential figures.
popularized_by(magic_realism, one_hundred_years_of_solitude).
% Explanation: The novel is considered the pinnacle of magic realism.
gave_speech(gabriel_garcia_marquez, x1992_nobel_prize_speech).
% Explanation: He delivered a landmark speech on solitude and Latin America.
concept(magical_realism).
related_to(magical_realism, magical_realism).
related_to(latin_american_boom, magical_realism).
concept(metafiction).
related_to(metafiction, magical_realism).
concept(hybridity).
related_to(hybridity, magical_realism).
concept(political_critique).
related_to(political_critique, magical_realism).
concept(garcía_márquez).
related_to(garcía_márquez, magical_realism).
related_to(one_hundred_years_of_solitude, magical_realism).
concept(salman_rushdie).
related_to(salman_rushdie, magical_realism).
concept(midnights_children).
related_to(midnights_children, magical_realism).
concept(isabel_allende).
related_to(isabel_allende, magical_realism).
concept(the_house_of_the_spirits).
related_to(the_house_of_the_spirits, magical_realism).
related_to(jorge_luis_borges, magical_realism).
concept(alejo_carpentier).
related_to(alejo_carpentier, magical_realism).
concept(miguel_ángel_asturias).
related_to(miguel_ángel_asturias, magical_realism).
concept(juan_rulfo).
related_to(juan_rulfo, magical_realism).
concept(pedro_páramo).
related_to(pedro_páramo, magical_realism).
concept(europe).
related_to(europe, magical_realism).
concept(latin_america).
related_to(latin_america, magical_realism).
concept(x1940s).
related_to(x1940s, magical_realism).
concept(x1960s).
related_to(x1960s, magical_realism).
concept(x1980s).
related_to(x1980s, magical_realism).
concept(surrealism).
related_to(surrealism, magical_realism).
concept(realism).
related_to(realism, magical_realism).
concept(postcolonialism).
related_to(postcolonialism, magical_realism).
concept(fabulism).
related_to(fabulism, magical_realism).
concept(myth).
related_to(myth, magical_realism).
concept(folklore).
related_to(folklore, magical_realism).
concept(narrative_unreliability).
related_to(narrative_unreliability, magical_realism).
concept(adaptations).
related_to(adaptations, magical_realism).
concept(the_house_of_the_spirits_film).
related_to(the_house_of_the_spirits_film, magical_realism).
concept(gabriel_garcía_márquez).
related_to(gabriel_garcía_márquez, magical_realism).
concept(caribbean_setting).
related_to(caribbean_setting, magical_realism).
concept(indian_subcontinent).
related_to(indian_subcontinent, magical_realism).
concept(magic).
related_to(magic, magical_realism).
concept(ordinary_reality).
related_to(ordinary_reality, magical_realism).
written_by(one_hundred_years_of_solitude, garcía_márquez).
% Explanation: Gabriel García Márquez is the author
movement(garcía_márquez, magical_realism).
% Explanation: García Márquez is a key representative of Magical Realism
set_in(one_hundred_years_of_solitude, caribbean_setting).
% Explanation: The novel is set in the fictional town of Macondo, inspired by the Caribbean region
genre_of(one_hundred_years_of_solitude, magical_realism).
% Explanation: The work exemplifies the genre
movement(one_hundred_years_of_solitude, latin_american_boom).
% Explanation: The novel is a centerpiece of the Latin American Boom
temporal_context(latin_american_boom, x1960s).
% Explanation: The literary movement peaked in the 1960s
geographical_context(latin_american_boom, latin_america).
% Explanation: The Boom is rooted in Latin America
influenced_by(magical_realism, surrealism).
% Explanation: Magical Realism incorporates elements of Surrealism
influenced_by(magical_realism, realism).
% Explanation: Magical Realism maintains realistic narrative techniques
employs(magical_realism, hybridity).
% Explanation: It blends the magical and the mundane
employs(magical_realism, political_critique).
% Explanation: It often contains political or social critique
theme(magical_realism, myth).
% Explanation: Magical Realism draws on mythic storytelling
theme(magical_realism, folklore).
% Explanation: The genre incorporates folklore
technique(magical_realism, narrative_unreliability).
% Explanation: Unreliable narration is often used
legacy(magical_realism, postcolonialism).
% Explanation: Influenced postcolonial literature globally
written_by(midnights_children, salman_rushdie).
% Explanation: Salman Rushdie is the author
published_in(midnights_children, x1981).
% Explanation: The book was published in 1981
set_in(midnights_children, indian_subcontinent).
% Explanation: The novel is set in India and Pakistan
genre_of(midnights_children, magical_realism).
% Explanation: The novel is a major example of the genre
influenced_by(midnights_children, one_hundred_years_of_solitude).
% Explanation: Rushdie’s novel drew narrative inspiration from Márquez’s work
written_by(the_house_of_the_spirits, isabel_allende).
% Explanation: Isabel Allende is the author
published_in(the_house_of_the_spirits, x1982).
% Explanation: The book was published in 1982
genre_of(the_house_of_the_spirits, magical_realism).
% Explanation: Allende’s debut utilizes magical realism
set_in(the_house_of_the_spirits, latin_america).
% Explanation: The novel is set in a fictional Latin American country
adapted_into(the_house_of_the_spirits, the_house_of_the_spirits_film).
% Explanation: The novel was adapted into a 1993 film
movement(jorge_luis_borges, magical_realism).
% Explanation: Borges’s short fictions influenced Magical Realism
coined_concept(alejo_carpentier, lo_real_maravilloso).
% Explanation: Carpentier introduced the concept of the marvelous real in Latin America
movement(alejo_carpentier, magical_realism).
% Explanation: Carpentier’s writing and theorizing were crucial for the movement
movement(miguel_ángel_asturias, magical_realism).
% Explanation: Asturias’s works (e.g., 'Men of Maize') are early examples
movement(juan_rulfo, magical_realism).
% Explanation: Rulfo’s 'Pedro Páramo' is iconic for the genre
written_by(pedro_páramo, juan_rulfo).
% Explanation: Rulfo authored the 1955 novel
published_in(pedro_páramo, x1955).
% Explanation: The novel was published in 1955
genre_of(pedro_páramo, magical_realism).
% Explanation: The work is a foundational text
spreads_to(magical_realism, europe).
% Explanation: The genre later influenced European writers
spreads_to(magical_realism, indian_subcontinent).
% Explanation: Writers such as Rushdie adopted its techniques
features(magical_realism, magic).
% Explanation: Supernatural elements are part of ordinary life
features(magical_realism, ordinary_reality).
% Explanation: Narratives present magical and realistic as one
related_genre_of(fabulism, magical_realism).
% Explanation: Fabulism is close but distinct, being less grounded in reality
temporal_origin(magical_realism, x1940s).
% Explanation: The term was popularized in literary criticism in the 1940s
influenced(jorge_luis_borges, garcía_márquez).
% Explanation: Borges’s work inspired later Magical Realism authors
influenced_by(isabel_allende, garcía_márquez).
% Explanation: Allende’s debut was inspired by Márquez
