% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: James Joyce
% Max depth: 1, Max related topics per node: 1

concept(james_joyce).
related_to(james_joyce, james_joyce).
concept(ulysses).
related_to(ulysses, james_joyce).
concept(dubliners).
related_to(dubliners, james_joyce).
concept(a_portrait_of_the_artist_as_a_young_man).
related_to(a_portrait_of_the_artist_as_a_young_man, james_joyce).
concept(finnegans_wake).
related_to(finnegans_wake, james_joyce).
concept(stephen_dedalus).
related_to(stephen_dedalus, james_joyce).
concept(leopold_bloom).
related_to(leopold_bloom, james_joyce).
concept(molly_bloom).
related_to(molly_bloom, james_joyce).
concept(modernism).
related_to(modernism, james_joyce).
concept(stream_of_consciousness).
related_to(stream_of_consciousness, james_joyce).
concept(dublin).
related_to(dublin, james_joyce).
concept(early_20th_century).
related_to(early_20th_century, james_joyce).
concept(ireland).
related_to(ireland, james_joyce).
concept(samuel_beckett).
related_to(samuel_beckett, james_joyce).
concept(ezra_pound).
related_to(ezra_pound, james_joyce).
concept(virginia_woolf).
related_to(virginia_woolf, james_joyce).
concept(homers_odyssey).
related_to(homers_odyssey, james_joyce).
concept(bloomsday).
related_to(bloomsday, james_joyce).
concept(censorship).
related_to(censorship, james_joyce).
concept(experimental_literature).
related_to(experimental_literature, james_joyce).
concept(the_dead).
related_to(the_dead, james_joyce).
concept(trieste).
related_to(trieste, james_joyce).
concept(paris).
related_to(paris, james_joyce).
concept(nora_barnacle).
related_to(nora_barnacle, james_joyce).
concept(joyces_blindness).
related_to(joyces_blindness, james_joyce).
concept(exile).
related_to(exile, james_joyce).
concept(harold_bloom).
related_to(harold_bloom, james_joyce).
concept(postmodernism).
related_to(postmodernism, james_joyce).
concept(jean_rhys).
related_to(jean_rhys, james_joyce).
concept(t_s_eliot).
related_to(t_s_eliot, james_joyce).
concept(adaptations).
related_to(adaptations, james_joyce).
concept(literary_epiphany).
related_to(literary_epiphany, james_joyce).
concept(autobiographical_fiction).
related_to(autobiographical_fiction, james_joyce).
concept(joycean_neologism).
related_to(joycean_neologism, james_joyce).
written_by(ulysses, james_joyce).
% Explanation: James Joyce is the author of Ulysses.
published_in(ulysses, x1922).
% Explanation: Ulysses was published in 1922.
set_in(ulysses, dublin).
% Explanation: Ulysses is set entirely in Dublin.
set_in(ulysses, early_20th_century).
% Explanation: Ulysses takes place on June 16, 1904.
genre_of(ulysses, modernism).
% Explanation: Ulysses is a quintessential modernist novel.
influenced_by(ulysses, homers_odyssey).
% Explanation: Ulysses borrows its structure and many themes from Homer's Odyssey.
protagonist_of(ulysses, leopold_bloom).
% Explanation: Leopold Bloom is a protagonist of Ulysses.
protagonist_of(ulysses, stephen_dedalus).
% Explanation: Stephen Dedalus is also a main protagonist in Ulysses.
protagonist_of(ulysses, molly_bloom).
% Explanation: Molly Bloom is a central character in Ulysses.
adapted_into(ulysses, ulysses_film_1967).
% Explanation: Ulysses was adapted into a film in 1967, among other adaptations.
born_in(james_joyce, dublin).
% Explanation: James Joyce was born in Dublin, Ireland.
lived_in(james_joyce, trieste).
% Explanation: James Joyce lived for several years in Trieste.
lived_in(james_joyce, paris).
% Explanation: James Joyce spent significant time in Paris.
written_by(dubliners, james_joyce).
% Explanation: James Joyce is the author of Dubliners.
published_in(dubliners, x1914).
% Explanation: Dubliners was published in 1914.
set_in(dubliners, dublin).
% Explanation: All stories in Dubliners are set in Dublin.
genre_of(dubliners, modernism).
% Explanation: Dubliners is recognized as a modernist work.
written_by(the_dead, james_joyce).
% Explanation: The Dead, the famous short story, is written by Joyce.
published_in(the_dead, x1914).
% Explanation: The Dead was published as part of Dubliners in 1914.
adapted_into(the_dead, the_dead_film_1987).
% Explanation: The Dead was adapted into a film by John Huston in 1987.
written_by(a_portrait_of_the_artist_as_a_young_man, james_joyce).
% Explanation: James Joyce wrote A Portrait of the Artist as a Young Man.
published_in(a_portrait_of_the_artist_as_a_young_man, x1916).
% Explanation: A Portrait of the Artist as a Young Man was published in 1916.
set_in(a_portrait_of_the_artist_as_a_young_man, dublin).
% Explanation: The novel is set in Joyce’s native city, Dublin.
protagonist_of(stephen_dedalus, a_portrait_of_the_artist_as_a_young_man).
% Explanation: Stephen Dedalus is the protagonist of this novel.
genre_of(a_portrait_of_the_artist_as_a_young_man, autobiographical_fiction).
% Explanation: A Portrait is partly autobiographical.
written_by(finnegans_wake, james_joyce).
% Explanation: James Joyce is the author of Finnegans Wake.
published_in(finnegans_wake, x1939).
% Explanation: Finnegans Wake was published in 1939.
genre_of(finnegans_wake, experimental_literature).
% Explanation: Finnegans Wake is a foundational work in experimental literature.
movement(james_joyce, modernism).
% Explanation: Joyce was a leading figure of modernist literature.
movement(james_joyce, stream_of_consciousness).
% Explanation: Joyce developed and popularized the stream of consciousness narrative technique.
employs(ulysses, stream_of_consciousness).
% Explanation: Ulysses is known for its innovative stream of consciousness narration.
associated_with(james_joyce, joycean_neologism).
% Explanation: Joyce created many new words, especially in Finnegans Wake.
originates_from(bloomsday, ulysses).
% Explanation: Bloomsday, celebrated June 16, marks the day of Ulysses' events.
influenced_by(samuel_beckett, james_joyce).
% Explanation: Beckett was mentored by, and heavily influenced by, Joyce.
influenced_by(virginia_woolf, james_joyce).
% Explanation: Joyce’s stream of consciousness technique influenced Virginia Woolf.
supported(ezra_pound, james_joyce).
% Explanation: Ezra Pound promoted Joyce's early career.
challenged_by(ulysses, censorship).
% Explanation: Ulysses faced considerable censorship and legal battles.
husband_of(james_joyce, nora_barnacle).
% Explanation: Nora Barnacle was Joyce's lifelong partner.
experienced(james_joyce, exile).
% Explanation: Joyce lived most of his adult life in self-imposed exile from Ireland.
suffered_from(james_joyce, joyces_blindness).
% Explanation: Joyce suffered from progressive blindness in later life.
critic_of(harold_bloom, james_joyce).
% Explanation: Harold Bloom considered Joyce central to the Western literary canon.
influenced(finnegans_wake, postmodernism).
% Explanation: Finnegans Wake’s linguistic experimentation influenced postmodern literature.
influenced_by(jean_rhys, james_joyce).
% Explanation: Jean Rhys and her narrative technique were influenced by Joyce.
influenced_by(t_s_eliot, james_joyce).
% Explanation: T. S. Eliot praised and was influenced by Joyce's modernism.
popularized_by(literary_epiphany, james_joyce).
% Explanation: Joyce popularized the idea of literary 'epiphany' in modern fiction.
concept(stream_of_consciousness_narrative_technique).
related_to(stream_of_consciousness, stream_of_consciousness_narrative_technique).
concept(interior_monologue).
related_to(interior_monologue, stream_of_consciousness_narrative_technique).
concept(narrative_technique).
related_to(narrative_technique, stream_of_consciousness_narrative_technique).
related_to(modernism, stream_of_consciousness_narrative_technique).
related_to(virginia_woolf, stream_of_consciousness_narrative_technique).
related_to(james_joyce, stream_of_consciousness_narrative_technique).
concept(william_faulkner).
related_to(william_faulkner, stream_of_consciousness_narrative_technique).
concept(dorothy_richardson).
related_to(dorothy_richardson, stream_of_consciousness_narrative_technique).
related_to(ulysses, stream_of_consciousness_narrative_technique).
concept(mrs_dalloway).
related_to(mrs_dalloway, stream_of_consciousness_narrative_technique).
concept(to_the_lighthouse).
related_to(to_the_lighthouse, stream_of_consciousness_narrative_technique).
concept(the_waves).
related_to(the_waves, stream_of_consciousness_narrative_technique).
concept(the_sound_and_the_fury).
related_to(the_sound_and_the_fury, stream_of_consciousness_narrative_technique).
concept(pilgrimage).
related_to(pilgrimage, stream_of_consciousness_narrative_technique).
concept(late_19th_century).
related_to(late_19th_century, stream_of_consciousness_narrative_technique).
related_to(early_20th_century, stream_of_consciousness_narrative_technique).
concept(england).
related_to(england, stream_of_consciousness_narrative_technique).
related_to(ireland, stream_of_consciousness_narrative_technique).
concept(united_states).
related_to(united_states, stream_of_consciousness_narrative_technique).
concept(psychological_realism).
related_to(psychological_realism, stream_of_consciousness_narrative_technique).
concept(free_indirect_discourse).
related_to(free_indirect_discourse, stream_of_consciousness_narrative_technique).
concept(consciousness).
related_to(consciousness, stream_of_consciousness_narrative_technique).
concept(subjectivity).
related_to(subjectivity, stream_of_consciousness_narrative_technique).
concept(time_perception).
related_to(time_perception, stream_of_consciousness_narrative_technique).
concept(unreliable_narrator).
related_to(unreliable_narrator, stream_of_consciousness_narrative_technique).
concept(experimental_narrative).
related_to(experimental_narrative, stream_of_consciousness_narrative_technique).
concept(influence_on_postmodernism).
related_to(influence_on_postmodernism, stream_of_consciousness_narrative_technique).
concept(firstperson_narration).
related_to(firstperson_narration, stream_of_consciousness_narrative_technique).
concept(influence_from_psychology).
related_to(influence_from_psychology, stream_of_consciousness_narrative_technique).
concept(sigmund_freud).
related_to(sigmund_freud, stream_of_consciousness_narrative_technique).
concept(marcel_proust).
related_to(marcel_proust, stream_of_consciousness_narrative_technique).
concept(remembrance_of_things_past).
related_to(remembrance_of_things_past, stream_of_consciousness_narrative_technique).
concept(stream_of_consciousness_in_film).
related_to(stream_of_consciousness_in_film, stream_of_consciousness_narrative_technique).
concept(legacy_in_contemporary_literature).
related_to(legacy_in_contemporary_literature, stream_of_consciousness_narrative_technique).
is_a(stream_of_consciousness, narrative_technique).
% Explanation: Stream of Consciousness is a specific style of narrative technique.
utilizes(stream_of_consciousness, interior_monologue).
% Explanation: Stream of Consciousness narrative often employs the interior monologue form.
closely_associated_with(stream_of_consciousness, modernism).
% Explanation: The stream of consciousness technique is a hallmark of Modernist literature.
set_in(ulysses, dublin_1904).
% Explanation: Ulysses is set in Dublin during 1904.
genre_of(ulysses, modernist_novel).
% Explanation: Ulysses is a Modernist novel.
movement(ulysses, modernism).
% Explanation: Ulysses is a foundational text of literary Modernism.
written_by(mrs_dalloway, virginia_woolf).
% Explanation: Virginia Woolf is the author of Mrs Dalloway.
published_in(mrs_dalloway, x1925).
% Explanation: Mrs Dalloway was published in 1925.
set_in(mrs_dalloway, london_postwwi).
% Explanation: Mrs Dalloway is set in post-World War I London.
genre_of(mrs_dalloway, modernist_novel).
% Explanation: Mrs Dalloway is a Modernist novel.
protagonist_of(mrs_dalloway, clarissa_dalloway).
% Explanation: Clarissa Dalloway is the protagonist of Mrs Dalloway.
written_by(to_the_lighthouse, virginia_woolf).
% Explanation: Virginia Woolf is the author of To the Lighthouse.
published_in(to_the_lighthouse, x1927).
% Explanation: To the Lighthouse was published in 1927.
written_by(the_sound_and_the_fury, william_faulkner).
% Explanation: William Faulkner is the author of The Sound and the Fury.
published_in(the_sound_and_the_fury, x1929).
% Explanation: The Sound and the Fury was published in 1929.
set_in(the_sound_and_the_fury, american_south_early_20th_century).
% Explanation: The novel is set in the American South during the early 20th century.
written_by(pilgrimage, dorothy_richardson).
% Explanation: Dorothy Richardson wrote the sequence of novels called Pilgrimage.
published_in(pilgrimage, x19151967).
% Explanation: Pilgrimage was published in parts between 1915 and 1967.
related_to(stream_of_consciousness, psychological_realism).
% Explanation: The technique aims to represent psychological depth and realism.
makes_use_of(stream_of_consciousness, free_indirect_discourse).
% Explanation: Many stream of consciousness narratives utilize free indirect discourse.
explores(stream_of_consciousness, consciousness).
% Explanation: It delves into the workings of human consciousness.
emphasizes(stream_of_consciousness, subjectivity).
% Explanation: It foregrounds the subjective experience of characters.
blurs(stream_of_consciousness, time_perception).
% Explanation: The technique often disrupts linear perception of time.
can_involve(stream_of_consciousness, unreliable_narrator).
% Explanation: Narrators in this style may not be reliable or objective.
is_an_example_of(stream_of_consciousness, experimental_narrative).
% Explanation: The technique is considered experimental in narrative form.
influenced_by(mrs_dalloway, ulysses).
% Explanation: Woolf’s Mrs Dalloway was influenced by Joyce's Ulysses.
influenced_by(to_the_lighthouse, ulysses).
% Explanation: Virginia Woolf's To the Lighthouse was influenced by Joyce’s stream of consciousness technique.
developed_in(modernism, late_19th_century).
% Explanation: The Modernist movement began in the late 19th century.
flourished_in(modernism, early_20th_century).
% Explanation: Modernism flourished in the early 20th century.
centered_in(modernism, england).
% Explanation: Modernism had important centers in England.
centered_in(modernism, ireland).
% Explanation: Modernism had important centers in Ireland.
centered_in(modernism, united_states).
% Explanation: Modernism also had important developments in the United States.
influenced(stream_of_consciousness, postmodernism).
% Explanation: The technique influenced the narrative experimentation of Postmodernism.
adapted_into(stream_of_consciousness, stream_of_consciousness_in_film).
% Explanation: Filmmakers adapted the style for cinema.
legacy_in(stream_of_consciousness, legacy_in_contemporary_literature).
% Explanation: Many contemporary authors use or reference the technique.
influenced_by(stream_of_consciousness, influence_from_psychology).
% Explanation: The narrative mode was influenced by psychological theory.
concept_developed_by(influence_from_psychology, sigmund_freud).
% Explanation: Freud's theories shaped ideas about interiority and subconscious.
preceded_by(stream_of_consciousness, marcel_proust).
% Explanation: Proust’s explorations of memory anticipated stream of consciousness.
written_by(remembrance_of_things_past, marcel_proust).
% Explanation: Proust wrote Remembrance of Things Past.
published_in(remembrance_of_things_past, x19131927).
% Explanation: The work was published over these years.
influenced(remembrance_of_things_past, stream_of_consciousness).
% Explanation: Proust’s work influenced later stream of consciousness writers.
pioneer_of(pilgrimage, stream_of_consciousness).
% Explanation: Dorothy Richardson's Pilgrimage is an early and influential example.
employed_by(stream_of_consciousness, firstperson_narration).
% Explanation: Stream of consciousness is often used in first-person narratives.
