% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Jean-Jacques Rousseau
% Max depth: 1, Max related topics per node: 1

concept(jeanjacques_rousseau).
concept(social_contract).
related_to(social_contract, jeanjacques_rousseau).
concept(general_will).
related_to(general_will, jeanjacques_rousseau).
concept(state_of_nature).
related_to(state_of_nature, jeanjacques_rousseau).
concept(natural_man).
related_to(natural_man, jeanjacques_rousseau).
concept(amour_de_soi).
related_to(amour_de_soi, jeanjacques_rousseau).
concept(amourpropre).
related_to(amourpropre, jeanjacques_rousseau).
concept(inequality).
related_to(inequality, jeanjacques_rousseau).
concept(popular_sovereignty).
related_to(popular_sovereignty, jeanjacques_rousseau).
concept(direct_democracy).
related_to(direct_democracy, jeanjacques_rousseau).
concept(civil_religion).
related_to(civil_religion, jeanjacques_rousseau).
concept(education_and_emile).
related_to(education_and_emile, jeanjacques_rousseau).
concept(corruption_of_civilization).
related_to(corruption_of_civilization, jeanjacques_rousseau).
concept(romanticism).
related_to(romanticism, jeanjacques_rousseau).
concept(noble_savage).
related_to(noble_savage, jeanjacques_rousseau).
related_to(jeanjacques_rousseau, jeanjacques_rousseau).
concept(the_social_contract_work).
related_to(the_social_contract_work, jeanjacques_rousseau).
concept(emile_or_on_education_work).
related_to(emile_or_on_education_work, jeanjacques_rousseau).
concept(discourse_on_the_origin_of_inequality_work).
related_to(discourse_on_the_origin_of_inequality_work, jeanjacques_rousseau).
concept(discourse_on_the_arts_and_sciences_work).
related_to(discourse_on_the_arts_and_sciences_work, jeanjacques_rousseau).
concept(confessions_work).
related_to(confessions_work, jeanjacques_rousseau).
concept(enlightenment).
related_to(enlightenment, jeanjacques_rousseau).
concept(john_locke).
related_to(john_locke, jeanjacques_rousseau).
concept(thomas_hobbes).
related_to(thomas_hobbes, jeanjacques_rousseau).
concept(voltaire).
related_to(voltaire, jeanjacques_rousseau).
concept(david_hume).
related_to(david_hume, jeanjacques_rousseau).
concept(immanuel_kant).
related_to(immanuel_kant, jeanjacques_rousseau).
concept(montesquieu).
related_to(montesquieu, jeanjacques_rousseau).
concept(romantic_movement).
related_to(romantic_movement, jeanjacques_rousseau).
concept(contractarianism).
related_to(contractarianism, jeanjacques_rousseau).
concept(encyclopedists).
related_to(encyclopedists, jeanjacques_rousseau).
concept(natural_rights).
related_to(natural_rights, jeanjacques_rousseau).
concept(human_perfectibility).
related_to(human_perfectibility, jeanjacques_rousseau).
lived_during(jeanjacques_rousseau, x18th_century).
% Explanation: Rousseau was a central Enlightenment thinker in the 1700s.
developed_by(social_contract, jeanjacques_rousseau).
% Explanation: Rousseau developed the concept in his 1762 book.
main_work(the_social_contract_work, jeanjacques_rousseau).
% Explanation: One of Rousseau's most influential works.
main_work(emile_or_on_education_work, jeanjacques_rousseau).
% Explanation: Rousseau's treatise on education and human development.
main_work(discourse_on_the_origin_of_inequality_work, jeanjacques_rousseau).
% Explanation: Work examining the source and effects of social inequality.
main_work(discourse_on_the_arts_and_sciences_work, jeanjacques_rousseau).
% Explanation: First major work, critical of civilization's corrupting influence.
main_work(confessions_work, jeanjacques_rousseau).
% Explanation: Rousseau's autobiographical work, significant for Romanticism.
central_in(social_contract, contractarianism).
% Explanation: Rousseau's social contract theory is a main foundation of contractarianism.
developed_by(general_will, jeanjacques_rousseau).
% Explanation: Key political concept about collective sovereignty.
developed_by(popular_sovereignty, jeanjacques_rousseau).
% Explanation: Popular sovereignty is a core element of Rousseau’s political theory.
advocated_by(direct_democracy, jeanjacques_rousseau).
% Explanation: He supported direct participation of citizens in governance.
developed_by(natural_man, jeanjacques_rousseau).
% Explanation: Rousseau theorized about humans in a pre-civilized state.
response_to(state_of_nature, john_locke).
% Explanation: Rousseau developed his own version in response to Locke's and Hobbes' theories.
response_to(state_of_nature, thomas_hobbes).
% Explanation: Contrasted with Hobbes’s violent state of nature, Rousseau idealized it.
analyzed_by(inequality, jeanjacques_rousseau).
% Explanation: Rousseau analyzed social inequality in his Discourse.
defined_by(amour_de_soi, jeanjacques_rousseau).
% Explanation: Concept of natural self-love, distinguished by Rousseau.
defined_by(amourpropre, jeanjacques_rousseau).
% Explanation: Concept of comparative, social self-love.
analyzed_in(corruption_of_civilization, discourse_on_the_arts_and_sciences_work).
% Explanation: Rousseau argues that civilization corrupts natural virtue.
developed_in(education_and_emile, emile_or_on_education_work).
% Explanation: Rousseau outlines his educational philosophy in Emile.
attributed_to(noble_savage, jeanjacques_rousseau).
% Explanation: Rousseau is associated with the belief that natural man is morally superior.
influenced_by(romanticism, jeanjacques_rousseau).
% Explanation: Rousseau is considered a forerunner of Romantic thought.
emphasized_by(human_perfectibility, jeanjacques_rousseau).
% Explanation: Rousseau stressed humans' ability to improve themselves.
developed_from(natural_rights, john_locke).
% Explanation: Both Locke and Rousseau expanded on natural rights theories.
school_of_thought(rousseau, enlightenment).
% Explanation: He was a central figure in the Enlightenment.
contemporary_of(enlightenment, voltaire).
% Explanation: Rousseau and Voltaire were both Enlightenment thinkers.
contemporary_of(jeanjacques_rousseau, david_hume).
% Explanation: Rousseau and Hume corresponded and were contemporaries.
influenced_by(jeanjacques_rousseau, john_locke).
% Explanation: Rousseau was influenced by Locke’s political theory.
influenced_by(jeanjacques_rousseau, thomas_hobbes).
% Explanation: Rousseau developed his state of nature partly in contrast to Hobbes.
criticized_by(jeanjacques_rousseau, voltaire).
% Explanation: Voltaire accused Rousseau of primitivism and idealizing nature.
influenced(jeanjacques_rousseau, immanuel_kant).
% Explanation: Kant was influenced by Rousseau's focus on autonomy and freedom.
influenced(jeanjacques_rousseau, romantic_movement).
% Explanation: Rousseau’s ideas inspired the Romantic movement.
influenced(jeanjacques_rousseau, french_revolution).
% Explanation: Rousseau’s ideas on sovereignty influenced revolutionary thought.
includes(contractarianism, social_contract).
% Explanation: Rousseau's social contract forms part of the contractarian tradition.
contemporary_of(encyclopedists, jeanjacques_rousseau).
% Explanation: Rousseau was originally a contributor and contemporary of the Encyclopedists.
contributor_to(jeanjacques_rousseau, encyclopedists).
% Explanation: Rousseau contributed articles to the French Encyclopédie.
contemporary_of(montesquieu, jeanjacques_rousseau).
% Explanation: Both were prominent Enlightenment thinkers.
criticized_by(general_will, liberal_theorists).
% Explanation: Criticized for potentially enabling totalitarianism.
concept(the_social_contract).
related_to(social_contract, the_social_contract).
related_to(state_of_nature, the_social_contract).
related_to(natural_rights, the_social_contract).
concept(civil_society).
related_to(civil_society, the_social_contract).
concept(sovereignty).
related_to(sovereignty, the_social_contract).
concept(consent_of_the_governed).
related_to(consent_of_the_governed, the_social_contract).
related_to(general_will, the_social_contract).
concept(absolute_sovereignty).
related_to(absolute_sovereignty, the_social_contract).
concept(liberalism).
related_to(liberalism, the_social_contract).
concept(republicanism).
related_to(republicanism, the_social_contract).
concept(tyranny).
related_to(tyranny, the_social_contract).
concept(law_of_nature).
related_to(law_of_nature, the_social_contract).
concept(leviathan).
related_to(leviathan, the_social_contract).
concept(two_treatises_of_government).
related_to(two_treatises_of_government, the_social_contract).
concept(the_social_contract_1762).
related_to(the_social_contract_1762, the_social_contract).
related_to(thomas_hobbes, the_social_contract).
related_to(john_locke, the_social_contract).
related_to(jeanjacques_rousseau, the_social_contract).
related_to(enlightenment, the_social_contract).
related_to(contractarianism, the_social_contract).
concept(utilitarianism).
related_to(utilitarianism, the_social_contract).
concept(critique_of_the_social_contract).
related_to(critique_of_the_social_contract, the_social_contract).
concept(john_rawls).
related_to(john_rawls, the_social_contract).
concept(a_theory_of_justice).
related_to(a_theory_of_justice, the_social_contract).
concept(hannah_arendt).
related_to(hannah_arendt, the_social_contract).
developed_by(social_contract, thomas_hobbes).
% Explanation: Hobbes is among the first to formalize the social contract concept.
developed_by(social_contract, john_locke).
% Explanation: Locke reinterprets and expands the social contract model.
further_developed_by(social_contract, john_rawls).
% Explanation: Rawls revives the idea in the 20th century with his theory of justice.
main_work(thomas_hobbes, leviathan).
% Explanation: Leviathan is the foundational text where Hobbes lays out his theory.
main_work(john_locke, two_treatises_of_government).
% Explanation: Locke's main exposition of social contract theory.
main_work(jeanjacques_rousseau, the_social_contract_1762).
% Explanation: Rousseau's influential work laying out his theory.
main_work(john_rawls, a_theory_of_justice).
% Explanation: Rawls's principal work reinterpreting the social contract.
lived_during(thomas_hobbes, x15881679).
% Explanation: Hobbes's lifespan, corresponding to the turmoil of the English Civil War.
lived_during(john_locke, x16321704).
% Explanation: Locke's era, encompassing the Enlightenment and Glorious Revolution.
lived_during(jeanjacques_rousseau, x17121778).
% Explanation: Rousseau's active period, in the age of Enlightenment.
lived_during(john_rawls, x19212002).
% Explanation: Rawls's lifespan in the 20th century.
component_of(social_contract, contractarianism).
% Explanation: Social contract theory is the core of contractarianism.
established_by(civil_society, social_contract).
% Explanation: The contract marks formation of an organized society.
granted_by(sovereignty, consent_of_the_governed).
% Explanation: Sovereign power is assigned through citizens' consent.
preceded_by(state_of_nature, social_contract).
% Explanation: Social contract ends humanity's state of nature.
retained_in(natural_rights, lockes_social_contract).
% Explanation: Lockeans retain certain natural rights (life, liberty, property).
espoused_by(absolute_sovereignty, thomas_hobbes).
% Explanation: Hobbes preferred a sovereign with absolute authority to avoid chaos.
criticized_by(tyranny, lockes_social_contract).
% Explanation: Locke's theory opposes tyranny, allowing rebellion against unjust rulers.
inspired_by(liberalism, lockes_social_contract).
% Explanation: Locke's theory is foundational for classical liberalism.
inspired_by(republicanism, rousseaus_social_contract).
% Explanation: Rousseau's emphasis on collective will underpins republican theory.
criticized_by(utilitarianism, contractarianism).
% Explanation: Utilitarians challenge contractarian focus on hypothetical agreements.
influenced_by(john_rawls, contractarianism).
% Explanation: Rawls modernizes the contractarian model in his work.
response_to(a_theory_of_justice, the_social_contract_1762).
% Explanation: Rawls's work is a 20th-century update and critique of classical social contract.
developed_by(critique_of_the_social_contract, hannah_arendt).
% Explanation: Arendt challenged the concept of the social contract and its atomistic anthropology.
contemporary_of(john_locke, thomas_hobbes).
% Explanation: Locke and Hobbes overlapped in the 17th century, though Locke was younger.
school_of_thought(contractarianism, thomas_hobbes).
% Explanation: Hobbes is a foundational contractarian.
school_of_thought(contractarianism, john_locke).
% Explanation: Locke is a representative figure of contractarian thought.
school_of_thought(contractarianism, jeanjacques_rousseau).
% Explanation: Rousseau is a key contractarian.
influenced(enlightenment, social_contract).
% Explanation: The Enlightenment is the intellectual context for these theories.
