% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Immanuel Kant
% Max depth: 1, Max related topics per node: 1

concept(immanuel_kant).
concept(transcendental_idealism).
related_to(transcendental_idealism, immanuel_kant).
concept(categorical_imperative).
related_to(categorical_imperative, immanuel_kant).
concept(synthetic_a_priori_judgments).
related_to(synthetic_a_priori_judgments, immanuel_kant).
concept(phenomena_and_noumena).
related_to(phenomena_and_noumena, immanuel_kant).
concept(copernican_revolution_in_philosophy).
related_to(copernican_revolution_in_philosophy, immanuel_kant).
concept(moral_law).
related_to(moral_law, immanuel_kant).
concept(autonomy).
related_to(autonomy, immanuel_kant).
concept(critique_of_pure_reason).
related_to(critique_of_pure_reason, immanuel_kant).
concept(critique_of_practical_reason).
related_to(critique_of_practical_reason, immanuel_kant).
concept(critique_of_judgment).
related_to(critique_of_judgment, immanuel_kant).
concept(ding_an_sich_thinginitself).
related_to(ding_an_sich_thinginitself, immanuel_kant).
concept(kingdom_of_ends).
related_to(kingdom_of_ends, immanuel_kant).
concept(universalizability_principle).
related_to(universalizability_principle, immanuel_kant).
concept(good_will).
related_to(good_will, immanuel_kant).
concept(faculty_of_judgment).
related_to(faculty_of_judgment, immanuel_kant).
concept(pure_reason).
related_to(pure_reason, immanuel_kant).
concept(practical_reason).
related_to(practical_reason, immanuel_kant).
concept(aesthetics).
related_to(aesthetics, immanuel_kant).
concept(enlightenment).
related_to(enlightenment, immanuel_kant).
concept(german_idealism).
related_to(german_idealism, immanuel_kant).
concept(david_hume).
related_to(david_hume, immanuel_kant).
concept(gwf_hegel).
related_to(gwf_hegel, immanuel_kant).
concept(arthur_schopenhauer).
related_to(arthur_schopenhauer, immanuel_kant).
concept(johann_gottlieb_fichte).
related_to(johann_gottlieb_fichte, immanuel_kant).
concept(friedrich_schelling).
related_to(friedrich_schelling, immanuel_kant).
concept(jeanjacques_rousseau).
related_to(jeanjacques_rousseau, immanuel_kant).
concept(rationalism).
related_to(rationalism, immanuel_kant).
concept(empiricism).
related_to(empiricism, immanuel_kant).
concept(deontology).
related_to(deontology, immanuel_kant).
concept(utilitarianism).
related_to(utilitarianism, immanuel_kant).
concept(moral_philosophy).
related_to(moral_philosophy, immanuel_kant).
developed_by(transcendental_idealism, immanuel_kant).
% Explanation: Kant formulated transcendental idealism as his central metaphysical doctrine.
main_work(transcendental_idealism, critique_of_pure_reason).
% Explanation: This concept is principally expounded in Kant's Critique of Pure Reason (1781/1787).
developed_by(categorical_imperative, immanuel_kant).
% Explanation: Kant developed the categorical imperative as the foundation of his moral philosophy.
main_work(categorical_imperative, critique_of_practical_reason).
% Explanation: Kant fully develops this concept in his second Critique.
temporal_context(critique_of_pure_reason, x1781).
% Explanation: Kant published the first edition in 1781.
temporal_context(critique_of_practical_reason, x1788).
% Explanation: This work was published in 1788.
temporal_context(critique_of_judgment, x1790).
% Explanation: Kant published this work in 1790.
includes_concept(transcendental_idealism, phenomena_and_noumena).
% Explanation: Kant's metaphysics distinguishes between phenomena (the world as we experience) and noumena (things-in-themselves).
synonym_of(ding_an_sich_thinginitself, noumena).
% Explanation: Kant uses 'Ding an sich' to refer to the noumenal realm.
developed_by(synthetic_a_priori_judgments, immanuel_kant).
% Explanation: Kant established the importance of synthetic a priori judgments for knowledge.
response_to(transcendental_idealism, empiricism).
% Explanation: Kant's philosophy synthesizes elements from the empiricist tradition.
response_to(transcendental_idealism, rationalism).
% Explanation: Kant's philosophy also addresses problematic aspects of rationalism.
copernican_revolution_in_philosophy(transcendental_idealism, copernican_revolution_in_philosophy).
% Explanation: Kant described his method as analogous to Copernicus' revolution in astronomy: knowledge must conform to the structure of the mind.
founded_by(deontology, immanuel_kant).
% Explanation: Kant's moral theory established deontological ethics.
core_principle_of(categorical_imperative, deontology).
% Explanation: Kant's categorical imperative is the central doctrine of deontological ethics.
component_of(universalizability_principle, categorical_imperative).
% Explanation: Universalizability is a test formulated in the categorical imperative.
discovered_by(moral_law, practical_reason).
% Explanation: Kant holds practical reason apprehends the moral law.
central_to(autonomy, kantian_ethics).
% Explanation: For Kant, autonomy is necessary for moral agency.
formulation_of(kingdom_of_ends, categorical_imperative).
% Explanation: Kingdom of Ends is a formulation of the categorical imperative, enjoining rational agents to treat each other as ends.
central_to(good_will, kantian_ethics).
% Explanation: Kant considers the good will to be the only unconditionally good thing.
explained_in(faculty_of_judgment, critique_of_judgment).
% Explanation: Faculty of judgment is explored in Kant's third Critique, focusing on aesthetics and teleology.
major_topic_of(aesthetics, critique_of_judgment).
% Explanation: Aesthetics is a key concern of Kant's third Critique.
criticized_by(transcendental_idealism, arthur_schopenhauer).
% Explanation: Schopenhauer criticized and extended Kant’s views on the thing-in-itself.
response_to(synthetic_a_priori_judgments, david_hume).
% Explanation: Kant developed this idea in response to Hume's skepticism about causality.
lived_during(immanuel_kant, x17241804).
% Explanation: Kant lived from 1724 to 1804.
school_of_thought(immanuel_kant, enlightenment).
% Explanation: Kant is a central figure in the European Enlightenment.
school_of_thought(immanuel_kant, german_idealism).
% Explanation: Kant is seen as the originator of German Idealism.
influenced_by(kantian_philosophy, david_hume).
% Explanation: Kant was awakened from his 'dogmatic slumber' by Hume's skepticism.
founded_by(german_idealism, immanuel_kant).
% Explanation: Kant's philosophy is the basis for German Idealism.
developed(gwf_hegel, german_idealism).
% Explanation: Hegel is a major figure in German Idealism, building on Kant.
developed(johann_gottlieb_fichte, german_idealism).
% Explanation: Fichte is another principal German Idealist after Kant.
developed(friedrich_schelling, german_idealism).
% Explanation: Schelling extended the German Idealist tradition.
influenced_by(gwf_hegel, immanuel_kant).
% Explanation: Hegel's philosophy is deeply influenced by Kant.
influenced_by(arthur_schopenhauer, immanuel_kant).
% Explanation: Schopenhauer builds on and alters Kantian metaphysics.
criticized_by(transcendental_idealism, gwf_hegel).
% Explanation: Hegel criticized some aspects of Kant's transcendental idealism.
criticized_by(deontology, utilitarianism).
% Explanation: Utilitarian philosophers such as Bentham and Mill criticized deontology.
criticized_by(kantian_ethics, friedrich_nietzsche).
% Explanation: Nietzsche offered criticisms of Kant's moral philosophy.
influenced(jeanjacques_rousseau, immanuel_kant).
% Explanation: Kant was inspired by Rousseau's writings on autonomy.
contemporary_of(immanuel_kant, david_hume).
% Explanation: Although not much overlap, Kant and Hume were near-contemporaries.
contemporary_of(immanuel_kant, jeanjacques_rousseau).
% Explanation: Kant was a contemporary of Rousseau, whose work he admired.
predated(rationalism, empiricism).
% Explanation: Rationalism (Descartes, Leibniz) and empiricism (Hume, Locke) set the stage for Kant.
response_to(german_idealism, transcendental_idealism).
% Explanation: German Idealism extends and critiques Kant's transcendental idealism.
main_work_of(critique_of_pure_reason, immanuel_kant).
% Explanation: Kant's magnum opus.
main_work_of(critique_of_practical_reason, immanuel_kant).
% Explanation: Second of Kant's three major Critiques.
main_work_of(critique_of_judgment, immanuel_kant).
% Explanation: Third and final major Critique by Kant.
related_to(categorical_imperative, categorical_imperative).
concept(hypothetical_imperative).
related_to(hypothetical_imperative, categorical_imperative).
related_to(good_will, categorical_imperative).
concept(universalizability).
related_to(universalizability, categorical_imperative).
related_to(practical_reason, categorical_imperative).
concept(duty).
related_to(duty, categorical_imperative).
related_to(moral_law, categorical_imperative).
related_to(autonomy, categorical_imperative).
related_to(kingdom_of_ends, categorical_imperative).
concept(respect_for_persons).
related_to(respect_for_persons, categorical_imperative).
related_to(deontology, categorical_imperative).
related_to(immanuel_kant, categorical_imperative).
concept(groundwork_of_the_metaphysics_of_morals).
related_to(groundwork_of_the_metaphysics_of_morals, categorical_imperative).
related_to(critique_of_practical_reason, categorical_imperative).
related_to(enlightenment, categorical_imperative).
related_to(utilitarianism, categorical_imperative).
concept(john_stuart_mill).
related_to(john_stuart_mill, categorical_imperative).
concept(jeremy_bentham).
related_to(jeremy_bentham, categorical_imperative).
concept(consequentialism).
related_to(consequentialism, categorical_imperative).
concept(virtue_ethics).
related_to(virtue_ethics, categorical_imperative).
concept(aristotle).
related_to(aristotle, categorical_imperative).
concept(moral_absolutism).
related_to(moral_absolutism, categorical_imperative).
concept(moral_relativism).
related_to(moral_relativism, categorical_imperative).
concept(g_w_f_hegel).
related_to(g_w_f_hegel, categorical_imperative).
concept(friedrich_nietzsche).
related_to(friedrich_nietzsche, categorical_imperative).
main_work(groundwork_of_the_metaphysics_of_morals, immanuel_kant).
% Explanation: Kant introduced the Categorical Imperative in this foundational philosophical work (1785).
main_work(critique_of_practical_reason, immanuel_kant).
% Explanation: Kant further elaborates the Categorical Imperative in this later work (1788).
lived_during(immanuel_kant, enlightenment).
% Explanation: Kant was a philosopher of the Enlightenment period (18th century).
contrasted_with(categorical_imperative, hypothetical_imperative).
% Explanation: Kant contrasted unconditional moral duties (categorical) with conditional practical obligations (hypothetical).
central_in(categorical_imperative, deontology).
% Explanation: Kant's Categorical Imperative is the core principle of deontological ethics.
school_of_thought(deontology, immanuel_kant).
% Explanation: Kant is the leading figure of Deontological ethics.
foundational_for(good_will, categorical_imperative).
% Explanation: The Categorical Imperative holds that only a 'good will' is good without qualification.
formulation_of(universalizability, categorical_imperative).
% Explanation: One main formulation is to act only according to maxims that can be universalized.
central_to(duty, categorical_imperative).
% Explanation: The moral worth of actions is determined by duty under the Categorical Imperative.
expressed_by(moral_law, categorical_imperative).
% Explanation: The Categorical Imperative is the expression of the moral law as rational legislation.
grounded_in(autonomy, categorical_imperative).
% Explanation: Moral autonomy arises from the self-imposition of the moral law, as per the Categorical Imperative.
mandated_by(respect_for_persons, categorical_imperative).
% Explanation: The Categorical Imperative requires treating persons as ends in themselves.
criticized_by(utilitarianism, categorical_imperative).
% Explanation: Utilitarian theorists criticize the Categorical Imperative for being too rigid or formalistic.
criticized_by(categorical_imperative, john_stuart_mill).
% Explanation: Mill, a key utilitarian, critiques Kantian morality in 'Utilitarianism' (1863).
developed_by(utilitarianism, jeremy_bentham).
% Explanation: Bentham, a contemporary of Kant, developed classical utilitarianism.
developed_by(utilitarianism, john_stuart_mill).
% Explanation: Mill refined Bentham's utilitarianism and critiqued deontological claims.
school_of_thought(utilitarianism, john_stuart_mill).
% Explanation: Mill is a leading utilitarian thinker.
school_of_thought(utilitarianism, jeremy_bentham).
% Explanation: Bentham is the founder of utilitarianism.
contemporary_of(immanuel_kant, jeremy_bentham).
% Explanation: Both philosophers were active during the late 18th and early 19th century.
contrasts_with(deontology, consequentialism).
% Explanation: Deontology judges morality by duty, whereas consequentialism judges by outcomes.
includes(consequentialism, utilitarianism).
% Explanation: Utilitarianism is a primary example of consequentialist moral theory.
contrasts_with(categorical_imperative, virtue_ethics).
% Explanation: Kantian duty-based ethics differs from Aristotle's virtue-oriented ethics.
developed_by(virtue_ethics, aristotle).
% Explanation: Aristotle was the key figure in virtue ethics, far before Kant's time.
criticized_by(g_w_f_hegel, categorical_imperative).
% Explanation: Hegel criticized the Categorical Imperative as being empty and overly formal.
criticized_by(friedrich_nietzsche, categorical_imperative).
% Explanation: Nietzsche rejected Kantian morality for suppressing individuality and life-affirmation.
temporal_context(categorical_imperative, late_18th_century).
% Explanation: Kant formulated and published the Categorical Imperative between 1785 and 1788.
expressed_by(moral_absolutism, categorical_imperative).
% Explanation: Categorical Imperative represents a form of moral absolutism (unconditional duty).
contrasted_with(moral_relativism, categorical_imperative).
% Explanation: Categorical Imperative posits universal moral rules, unlike relativism.
lived_during(aristotle, classical_greece).
% Explanation: Aristotle lived in the 4th century BCE, long before Kant.
lived_during(g_w_f_hegel, german_idealism_early_19th_century).
% Explanation: Hegel was active in the early 19th century following Kant.
lived_during(friedrich_nietzsche, late_19th_century).
% Explanation: Nietzsche was active many decades after Kant.
influenced_by(g_w_f_hegel, immanuel_kant).
% Explanation: Hegel's philosophy developed in response to Kantian ideas, including the Categorical Imperative.
influenced_by(friedrich_nietzsche, immanuel_kant).
% Explanation: Nietzsche engaged critically with Kant in developing his own moral philosophy.
response_to(deontology, teleological_ethics).
% Explanation: Deontology (Kant) is defined against earlier teleological and consequentialist approaches.
