% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Karl Marx
% Max depth: 1, Max related topics per node: 1

concept(karl_marx).
concept(historical_materialism).
related_to(historical_materialism, karl_marx).
concept(dialectical_materialism).
related_to(dialectical_materialism, karl_marx).
concept(class_struggle).
related_to(class_struggle, karl_marx).
concept(alienation).
related_to(alienation, karl_marx).
concept(surplus_value).
related_to(surplus_value, karl_marx).
concept(base_and_superstructure).
related_to(base_and_superstructure, karl_marx).
concept(proletariat).
related_to(proletariat, karl_marx).
concept(bourgeoisie).
related_to(bourgeoisie, karl_marx).
concept(capitalism).
related_to(capitalism, karl_marx).
concept(communism).
related_to(communism, karl_marx).
concept(socialism).
related_to(socialism, karl_marx).
concept(commodity_fetishism).
related_to(commodity_fetishism, karl_marx).
concept(means_of_production).
related_to(means_of_production, karl_marx).
concept(mode_of_production).
related_to(mode_of_production, karl_marx).
concept(revolution).
related_to(revolution, karl_marx).
concept(the_communist_manifesto).
related_to(the_communist_manifesto, karl_marx).
concept(das_kapital).
related_to(das_kapital, karl_marx).
related_to(karl_marx, karl_marx).
concept(friedrich_engels).
related_to(friedrich_engels, karl_marx).
concept(vladimir_lenin).
related_to(vladimir_lenin, karl_marx).
concept(georg_wilhelm_friedrich_hegel).
related_to(georg_wilhelm_friedrich_hegel, karl_marx).
concept(ludwig_feuerbach).
related_to(ludwig_feuerbach, karl_marx).
concept(jeanpaul_sartre).
related_to(jeanpaul_sartre, karl_marx).
concept(louis_althusser).
related_to(louis_althusser, karl_marx).
concept(herbert_marcuse).
related_to(herbert_marcuse, karl_marx).
concept(antonio_gramsci).
related_to(antonio_gramsci, karl_marx).
concept(western_marxism).
related_to(western_marxism, karl_marx).
concept(marxismleninism).
related_to(marxismleninism, karl_marx).
concept(frankfurt_school).
related_to(frankfurt_school, karl_marx).
concept(second_international).
related_to(second_international, karl_marx).
developed_by(historical_materialism, karl_marx).
% Explanation: Marx established historical materialism as the theory that material conditions drive historical development.
developed_by(dialectical_materialism, friedrich_engels).
% Explanation: Engels developed dialectical materialism based on Marx's ideas and Hegelian dialectics.
central_to(class_struggle, marxism).
% Explanation: Class struggle is the central dynamic in Marxism, underlying the conflict in every historical epoch.
developed_by(alienation, karl_marx).
% Explanation: Marx identified alienation as a key feature of labor under capitalism.
developed_by(surplus_value, karl_marx).
% Explanation: Marx introduced surplus value as the source of capitalist profit extracted from labor.
developed_by(base_and_superstructure, karl_marx).
% Explanation: Marx theorized society as structured via the base (economy) and superstructure (culture, law, politics).
oppressed_by(proletariat, bourgeoisie).
% Explanation: In Marxist theory, the proletariat is the working class oppressed by the bourgeoisie (capitalist class).
goal_of(communism, marxism).
% Explanation: Marxism envisions communism as the end state of classless society after socialism.
key_concept_in(mode_of_production, historical_materialism).
% Explanation: The mode of production determines the material base for social order and historical change.
component_of(means_of_production, mode_of_production).
% Explanation: Means of production are the tools, factories, land, etc. central to the mode of production.
described_in(commodity_fetishism, das_kapital).
% Explanation: Marx describes how commodities conceal underlying social relations in Das Kapital.
written_by(the_communist_manifesto, karl_marx).
% Explanation: Marx co-authored The Communist Manifesto (1848) as a call to proletarian revolution.
written_by(the_communist_manifesto, friedrich_engels).
% Explanation: Engels co-authored The Communist Manifesto with Marx.
written_by(das_kapital, karl_marx).
% Explanation: Marx's major economic analysis, Das Kapital, was published in 1867.
main_work(karl_marx, das_kapital).
% Explanation: Das Kapital is widely regarded as Marx's main work.
main_work(karl_marx, the_communist_manifesto).
% Explanation: The Communist Manifesto is another foundational work by Marx.
contemporary_of(karl_marx, friedrich_engels).
% Explanation: Marx and Engels were contemporaries and collaborators.
lived_during(karl_marx, x19th_century).
% Explanation: Marx lived from 1818 to 1883, during the 19th century.
lived_during(friedrich_engels, x19th_century).
% Explanation: Engels lived from 1820 to 1895, during the 19th century.
school_of_thought(karl_marx, marxism).
% Explanation: Marx is the founder of Marxism.
school_of_thought(friedrich_engels, marxism).
% Explanation: Engels is a key figure in Marxism.
response_to(historical_materialism, idealism).
% Explanation: Marx’s historical materialism was a response to Hegelian and other forms of philosophical idealism.
influenced_by(dialectical_materialism, georg_wilhelm_friedrich_hegel).
% Explanation: The dialectical method was influenced by Hegel's dialectics.
influenced_by(historical_materialism, ludwig_feuerbach).
% Explanation: Marx adapted Feuerbach’s materialism to create a theory of social and historical change.
response_to(marxismleninism, marxism).
% Explanation: Lenin adapted Marx’s theory to conditions in Russia, spawning a new school.
developed_by(vladimir_lenin, marxismleninism).
% Explanation: Lenin developed Marxism-Leninism, an application of Marxist theory to revolutionary practice.
influenced_by(marxismleninism, karl_marx).
% Explanation: Lenin’s ideas draw directly from Marx’s concepts.
response_to(western_marxism, marxismleninism).
% Explanation: Western Marxists critiqued the Soviet model and reinterpreted Marxist theory.
school_of_thought(frankfurt_school, western_marxism).
% Explanation: The Frankfurt School forms a major part of Western Marxism, integrating psychoanalysis and culture.
part_of(herbert_marcuse, frankfurt_school).
% Explanation: Marcuse was a member of the Frankfurt School.
part_of(louis_althusser, western_marxism).
% Explanation: Althusser was a key Western Marxist theorist.
developed(antonio_gramsci, hegemony).
% Explanation: Gramsci developed the concept of 'hegemony' as refinement of Marxist theory of the superstructure.
criticized_by(class_struggle, critics_of_marxism).
% Explanation: Various critics, from liberals to postmodernists, have challenged Marx’s emphasis on class struggle.
criticized_by(marxism, jeanpaul_sartre).
% Explanation: Sartre and existentialists criticized Marxism for insufficient attention to individual autonomy.
temporal_context(mode_of_production, mid19th_century).
% Explanation: Marx developed the concept in the mid-1800s.
temporal_context(commodity_fetishism, x1867).
% Explanation: Marx published the concept in Das Kapital in 1867.
temporal_context(alienation, x1844_manuscripts).
% Explanation: Alienation appears in Marx’s early Economic and Philosophic Manuscripts of 1844.
founded_on(second_international, marxism).
% Explanation: The Second International coordinated socialist parties inspired by Marxist theory.
related_to(historical_materialism, historical_materialism).
related_to(dialectical_materialism, historical_materialism).
related_to(base_and_superstructure, historical_materialism).
related_to(means_of_production, historical_materialism).
concept(relations_of_production).
related_to(relations_of_production, historical_materialism).
concept(modes_of_production).
related_to(modes_of_production, historical_materialism).
related_to(class_struggle, historical_materialism).
concept(ideology).
related_to(ideology, historical_materialism).
concept(social_revolution).
related_to(social_revolution, historical_materialism).
concept(primitive_communism).
related_to(primitive_communism, historical_materialism).
concept(slave_society).
related_to(slave_society, historical_materialism).
concept(feudalism).
related_to(feudalism, historical_materialism).
related_to(capitalism, historical_materialism).
related_to(socialism, historical_materialism).
related_to(communism, historical_materialism).
concept(forces_of_production).
related_to(forces_of_production, historical_materialism).
related_to(alienation, historical_materialism).
developed_by(historical_materialism, friedrich_engels).
% Explanation: Engels co-developed and expanded the concept alongside Marx.
lived_during(karl_marx, x18181883).
% Explanation: Karl Marx lived during the 19th century.
lived_during(friedrich_engels, x18201895).
% Explanation: Friedrich Engels was a contemporary and collaborator of Marx.
main_work(historical_materialism, the_german_ideology).
% Explanation: Historical Materialism is systematically outlined in 'The German Ideology' by Marx and Engels.
response_to(historical_materialism, idealist_conceptions_of_history).
% Explanation: Historical Materialism was developed as a critique and alternative to idealist history focusing on ideas over material conditions.
influenced_by(historical_materialism, georg_wilhelm_friedrich_hegel).
% Explanation: Marx adapted Hegel’s dialectics to materialist ends.
lived_during(georg_wilhelm_friedrich_hegel, x17701831).
% Explanation: Hegel was a philosopher of the early 19th century.
central_concept(historical_materialism, base_and_superstructure).
% Explanation: Base and Superstructure is a fundamental analytical distinction in historical materialism.
consists_of(base_and_superstructure, means_of_production).
% Explanation: The base includes the means of production.
consists_of(base_and_superstructure, relations_of_production).
% Explanation: The base also includes the relations of production.
composed_of(modes_of_production, means_of_production).
% Explanation: Each mode of production consists of its means of production.
composed_of(modes_of_production, relations_of_production).
% Explanation: Modes of production are also defined by their specific social relations.
emphasizes(historical_materialism, class_struggle).
% Explanation: Class struggle is central to historical change in historical materialism.
leads_to(class_struggle, social_revolution).
% Explanation: Contradictions between classes eventually lead to revolutionary change.
determines(base_and_superstructure, ideology).
% Explanation: The economic base conditions the types of ideology present in a society.
determines(base_and_superstructure, superstructure).
% Explanation: The economic base gives rise to the legal, political, and ideological superstructure.
periodizes(historical_materialism, primitive_communism).
% Explanation: One of the stages in Marx's periodization of history.
periodizes(historical_materialism, slave_society).
% Explanation: Another historical stage.
periodizes(historical_materialism, feudalism).
% Explanation: Feudalism is a stage in the historical sequence.
periodizes(historical_materialism, capitalism).
% Explanation: Capitalism is seen as a historical epoch.
periodizes(historical_materialism, socialism).
% Explanation: Socialism is posited as the next stage following capitalism.
periodizes(historical_materialism, communism).
% Explanation: Communism is considered the anticipated final stage.
component_of(forces_of_production, means_of_production).
% Explanation: Forces of production are part of what constitutes the means of production.
main_work(karl_marx, capital_das_kapital).
% Explanation: Marx's major work analyzing capitalism using historical materialism.
main_work(friedrich_engels, socialism_utopian_and_scientific).
% Explanation: Engels explains the science of historical materialism contrasted with earlier socialist thought.
criticized_by(historical_materialism, western_marxism).
% Explanation: Western Marxists criticized deterministic and economic reductionist readings of historical materialism.
criticized_by(historical_materialism, structural_marxism).
% Explanation: Structural Marxists such as Althusser criticized orthodox interpretations of historical materialism.
criticized_by(historical_materialism, critical_theory).
% Explanation: Frankfurt School theorists critiqued aspects of historical materialism, especially its economic determinism.
influenced_by(western_marxism, historical_materialism).
% Explanation: Western Marxists built upon and re-interpreted historical materialist foundations.
influenced_by(structural_marxism, historical_materialism).
% Explanation: Structuralist approaches emerged from debates about the structure and dynamics of history laid out in historical materialism.
school_of_thought(critical_theory, frankfurt_school).
% Explanation: Critical Theory is associated with the Frankfurt School, engaging with and critiquing Marxism.
developed_by(louis_althusser, structural_marxism).
% Explanation: Althusser is a primary figure in Structural Marxism and its critique of economic determinism.
lived_during(louis_althusser, x19181990).
% Explanation: Althusser was a 20th century philosopher.
lived_during(antonio_gramsci, x18911937).
% Explanation: Gramsci was a Marxist thinker active in the early 20th century.
criticized_by(antonio_gramsci, economic_determinism).
% Explanation: Gramsci critiqued the reduction of superstructural elements to economic causes.
main_work(antonio_gramsci, prison_notebooks).
% Explanation: Gramsci’s key work engages with historical materialism and the concept of hegemony.
