% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Ludwig Wittgenstein
% Max depth: 1, Max related topics per node: 1

concept(ludwig_wittgenstein).
concept(picture_theory_of_language).
related_to(picture_theory_of_language, ludwig_wittgenstein).
concept(language_games).
related_to(language_games, ludwig_wittgenstein).
concept(family_resemblance).
related_to(family_resemblance, ludwig_wittgenstein).
concept(rulefollowing).
related_to(rulefollowing, ludwig_wittgenstein).
concept(private_language_argument).
related_to(private_language_argument, ludwig_wittgenstein).
concept(forms_of_life).
related_to(forms_of_life, ludwig_wittgenstein).
concept(tractatus_logicophilosophicus).
related_to(tractatus_logicophilosophicus, ludwig_wittgenstein).
concept(philosophical_investigations).
related_to(philosophical_investigations, ludwig_wittgenstein).
concept(logical_atomism).
related_to(logical_atomism, ludwig_wittgenstein).
concept(ordinary_language_philosophy).
related_to(ordinary_language_philosophy, ludwig_wittgenstein).
concept(analytic_philosophy).
related_to(analytic_philosophy, ludwig_wittgenstein).
concept(vienna_circle).
related_to(vienna_circle, ludwig_wittgenstein).
concept(logical_positivism).
related_to(logical_positivism, ludwig_wittgenstein).
concept(ge_moore).
related_to(ge_moore, ludwig_wittgenstein).
concept(bertrand_russell).
related_to(bertrand_russell, ludwig_wittgenstein).
concept(frank_p_ramsey).
related_to(frank_p_ramsey, ludwig_wittgenstein).
concept(rudolf_carnap).
related_to(rudolf_carnap, ludwig_wittgenstein).
concept(gilbert_ryle).
related_to(gilbert_ryle, ludwig_wittgenstein).
concept(elizabeth_anscombe).
related_to(elizabeth_anscombe, ludwig_wittgenstein).
concept(norman_malcolm).
related_to(norman_malcolm, ludwig_wittgenstein).
concept(saul_kripke).
related_to(saul_kripke, ludwig_wittgenstein).
concept(early_wittgenstein).
related_to(early_wittgenstein, ludwig_wittgenstein).
concept(later_wittgenstein).
related_to(later_wittgenstein, ludwig_wittgenstein).
developed_by(picture_theory_of_language, ludwig_wittgenstein).
% Explanation: Wittgenstein developed this theory in his early philosophy.
formalized_in(picture_theory_of_language, tractatus_logicophilosophicus).
% Explanation: Picture Theory is central to the Tractatus.
developed_by(language_games, ludwig_wittgenstein).
% Explanation: Later Wittgenstein introduced the concept of Language Games.
formalized_in(language_games, philosophical_investigations).
% Explanation: This concept is crucial in Wittgenstein's later work.
developed_by(family_resemblance, ludwig_wittgenstein).
% Explanation: Family Resemblance is another important notion in his later philosophy.
developed_by(forms_of_life, ludwig_wittgenstein).
% Explanation: The concept describes the social context of language use.
developed_by(rulefollowing, ludwig_wittgenstein).
% Explanation: Rule-following arguments appear in Philosophical Investigations.
developed_by(private_language_argument, ludwig_wittgenstein).
% Explanation: Wittgenstein argued that a genuinely private language is impossible.
influenced_by(ordinary_language_philosophy, later_wittgenstein).
% Explanation: His later work inspired the ordinary language school.
developed_by(logical_atomism, bertrand_russell).
% Explanation: Russell developed Logical Atomism, which influenced early Wittgenstein.
defined_by(early_wittgenstein, tractatus_logicophilosophicus).
% Explanation: Wittgenstein's early period is marked by the Tractatus.
defined_by(later_wittgenstein, philosophical_investigations).
% Explanation: His later period is shaped by this book.
response_to(early_wittgenstein, logical_atomism).
% Explanation: He responded to and extended Russell's Logical Atomism.
response_to(later_wittgenstein, early_wittgenstein).
% Explanation: Wittgenstein's later philosophy is a critique of his earlier work.
influenced_by(logical_positivism, tractatus_logicophilosophicus).
% Explanation: Logical positivists were strongly influenced by Wittgenstein's early work.
adopted_concepts_from(vienna_circle, logical_positivism).
% Explanation: The Vienna Circle further developed logical positivism.
contemporary_of(frank_p_ramsey, ludwig_wittgenstein).
% Explanation: Ramsey discussed Wittgenstein's Tractatus and influenced his later work.
contemporary_of(rudolf_carnap, ludwig_wittgenstein).
% Explanation: Carnap was a logical positivist influenced by Wittgenstein.
contemporary_of(ge_moore, ludwig_wittgenstein).
% Explanation: Moore and Wittgenstein both worked at Cambridge.
student_of(elizabeth_anscombe, ludwig_wittgenstein).
% Explanation: Anscombe was Wittgenstein’s student and translator.
student_of(norman_malcolm, ludwig_wittgenstein).
% Explanation: Malcolm was a disciple and biographer of Wittgenstein.
contemporary_of(gilbert_ryle, ludwig_wittgenstein).
% Explanation: Ryle was part of the ordinary language school influenced by Wittgenstein.
interpreted(saul_kripke, rulefollowing).
% Explanation: Kripke presented an influential interpretation of Wittgenstein’s rule-following considerations.
main_work(tractatus_logicophilosophicus, ludwig_wittgenstein).
% Explanation: This book is his main early work.
main_work(philosophical_investigations, ludwig_wittgenstein).
% Explanation: His central later work.
lived_during(ludwig_wittgenstein, x18891951).
% Explanation: Wittgenstein lived from 1889 to 1951.
active_during(early_wittgenstein, x1910s1921).
% Explanation: His early period culminated with the completion of the Tractatus in 1921.
active_during(later_wittgenstein, late_1920s1951).
% Explanation: His later philosophy developed mainly from the 1930s until his death.
school_of_thought(ludwig_wittgenstein, analytic_philosophy).
% Explanation: He is a central figure in analytic philosophy.
school_of_thought(bertrand_russell, analytic_philosophy).
% Explanation: Russell was a co-founder of analytic philosophy.
school_of_thought(ge_moore, analytic_philosophy).
% Explanation: Moore was also a major analytic philosopher.
school_of_thought(logical_positivism, vienna_circle).
% Explanation: The Vienna Circle organized and defended logical positivism.
school_of_thought(ordinary_language_philosophy, analytic_philosophy).
% Explanation: A branch of analytic philosophy influenced by later Wittgenstein.
criticized_by(ordinary_language_philosophy, logical_positivism).
% Explanation: Logical positivists viewed ordinary language philosophy skeptically.
related_to(language_games, language_games).
concept(meaning_as_use).
related_to(meaning_as_use, language_games).
related_to(private_language_argument, language_games).
related_to(family_resemblance, language_games).
related_to(rulefollowing, language_games).
related_to(forms_of_life, language_games).
related_to(ordinary_language_philosophy, language_games).
related_to(picture_theory_of_language, language_games).
related_to(philosophical_investigations, language_games).
related_to(logical_positivism, language_games).
related_to(analytic_philosophy, language_games).
related_to(ludwig_wittgenstein, language_games).
related_to(ge_moore, language_games).
concept(jl_austin).
related_to(jl_austin, language_games).
related_to(gilbert_ryle, language_games).
concept(john_searle).
related_to(john_searle, language_games).
related_to(saul_kripke, language_games).
related_to(vienna_circle, language_games).
main_work(language_games, philosophical_investigations).
% Explanation: The central articulation of language games appears in Wittgenstein's 'Philosophical Investigations' (1953).
developed_by(meaning_as_use, ludwig_wittgenstein).
% Explanation: Wittgenstein advanced the idea that meaning is determined by the use of language in practice.
response_to(meaning_as_use, picture_theory_of_language).
% Explanation: Wittgenstein replaced the early picture theory from his 'Tractatus' with the idea of meaning as use in his later work.
based_on(language_games, forms_of_life).
% Explanation: Language games are embedded in forms of life, reflecting communal activities and practices.
influenced(language_games, ordinary_language_philosophy).
% Explanation: Language games inspired the ordinary language philosophy movement in mid-20th-century analytic philosophy.
school_of_thought(jl_austin, ordinary_language_philosophy).
% Explanation: Austin was a key figure in ordinary language philosophy inspired by Wittgenstein's later ideas.
school_of_thought(gilbert_ryle, ordinary_language_philosophy).
% Explanation: Ryle also contributed significantly to ordinary language philosophy.
influenced_by(john_searle, jl_austin).
% Explanation: Searle's speech act theory built upon Austin's and traces roots to language games.
criticized_by(saul_kripke, rulefollowing).
% Explanation: Kripke submitted a skeptical reading of Wittgenstein's rule-following argument (known as 'Kripkenstein').
promoted(vienna_circle, logical_positivism).
% Explanation: The Vienna Circle was the group most responsible for developing and promoting logical positivism.
criticized_by(logical_positivism, language_games).
% Explanation: Wittgenstein's later philosophy and language games constitute a major critique of logical positivism.
contemporary_of(vienna_circle, ludwig_wittgenstein).
% Explanation: The Vienna Circle was active when Wittgenstein was developing his early and later philosophies.
contemporary_of(gilbert_ryle, jl_austin).
% Explanation: Ryle and Austin were both prominent mid-20th-century British philosophers.
developed_during(language_games, x1940s1950s).
% Explanation: The concept was developed in Wittgenstein's later period and posthumously published in 1953.
developed_during(ordinary_language_philosophy, x1940s1960s).
% Explanation: This school of thought grew directly out of postwar engagement with Wittgenstein's later philosophy.
