% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Mark Twain
% Max depth: 1, Max related topics per node: 1

concept(mark_twain).
related_to(mark_twain, mark_twain).
concept(samuel_langhorne_clemens).
related_to(samuel_langhorne_clemens, mark_twain).
concept(the_adventures_of_tom_sawyer).
related_to(the_adventures_of_tom_sawyer, mark_twain).
concept(the_adventures_of_huckleberry_finn).
related_to(the_adventures_of_huckleberry_finn, mark_twain).
concept(life_on_the_mississippi).
related_to(life_on_the_mississippi, mark_twain).
concept(a_connecticut_yankee_in_king_arthurs_court).
related_to(a_connecticut_yankee_in_king_arthurs_court, mark_twain).
concept(puddnhead_wilson).
related_to(puddnhead_wilson, mark_twain).
concept(x19thcentury_american_literature).
related_to(x19thcentury_american_literature, mark_twain).
concept(realism).
related_to(realism, mark_twain).
concept(satire).
related_to(satire, mark_twain).
concept(missouri).
related_to(missouri, mark_twain).
concept(mississippi_river).
related_to(mississippi_river, mark_twain).
concept(x1835).
related_to(x1835, mark_twain).
concept(x1910).
related_to(x1910, mark_twain).
concept(american_civil_war).
related_to(american_civil_war, mark_twain).
concept(tom_sawyer).
related_to(tom_sawyer, mark_twain).
concept(huckleberry_finn).
related_to(huckleberry_finn, mark_twain).
concept(literary_humor).
related_to(literary_humor, mark_twain).
concept(american_dialect).
related_to(american_dialect, mark_twain).
concept(american_south).
related_to(american_south, mark_twain).
concept(hartford_connecticut).
related_to(hartford_connecticut, mark_twain).
concept(gilded_age).
related_to(gilded_age, mark_twain).
concept(samuel_clemens_as_author).
related_to(samuel_clemens_as_author, mark_twain).
concept(racism_and_slavery).
related_to(racism_and_slavery, mark_twain).
concept(literary_legacy).
related_to(literary_legacy, mark_twain).
concept(film_adaptations_of_twains_works).
related_to(film_adaptations_of_twains_works, mark_twain).
concept(ernest_hemingway).
related_to(ernest_hemingway, mark_twain).
concept(william_faulkner).
related_to(william_faulkner, mark_twain).
concept(american_literature_canon).
related_to(american_literature_canon, mark_twain).
concept(first_great_american_novelist).
related_to(first_great_american_novelist, mark_twain).
real_name_of(mark_twain, samuel_langhorne_clemens).
% Explanation: Mark Twain was the pen name of Samuel Langhorne Clemens.
written_by(the_adventures_of_tom_sawyer, mark_twain).
% Explanation: Twain wrote 'The Adventures of Tom Sawyer'.
written_by(the_adventures_of_huckleberry_finn, mark_twain).
% Explanation: Twain wrote 'The Adventures of Huckleberry Finn'.
written_by(life_on_the_mississippi, mark_twain).
% Explanation: Twain wrote 'Life on the Mississippi'.
written_by(a_connecticut_yankee_in_king_arthurs_court, mark_twain).
% Explanation: Twain is the author of this satirical science fiction novel.
written_by(puddnhead_wilson, mark_twain).
% Explanation: Twain is the author of this novel set in the antebellum South.
published_in(the_adventures_of_tom_sawyer, x1876).
% Explanation: The novel was first published in 1876.
published_in(the_adventures_of_huckleberry_finn, x1884).
% Explanation: Huckleberry Finn was published in 1884.
published_in(life_on_the_mississippi, x1883).
% Explanation: Life on the Mississippi was published in 1883.
published_in(a_connecticut_yankee_in_king_arthurs_court, x1889).
% Explanation: The novel was published in 1889.
published_in(puddnhead_wilson, x1894).
% Explanation: Pudd’nhead Wilson was published in 1894.
set_in(the_adventures_of_tom_sawyer, missouri).
% Explanation: The novel is set in a fictional town inspired by Twain's boyhood in Missouri.
set_in(the_adventures_of_huckleberry_finn, mississippi_river).
% Explanation: The story follows Huck and Jim’s journey down the Mississippi River.
set_in(life_on_the_mississippi, mississippi_river).
% Explanation: The work is a memoir and travelogue about Twain's experiences on the river.
protagonist_of(the_adventures_of_tom_sawyer, tom_sawyer).
% Explanation: Tom Sawyer is the main character of the novel.
protagonist_of(the_adventures_of_huckleberry_finn, huckleberry_finn).
% Explanation: Huck Finn is the central character of the novel.
genre_of(the_adventures_of_huckleberry_finn, realism).
% Explanation: The novel exemplifies American literary realism.
movement(mark_twain, realism).
% Explanation: Twain is a major figure of American Realism.
movement(mark_twain, x19thcentury_american_literature).
% Explanation: Twain is one of the key authors of 19th-century American literature.
known_for(mark_twain, satire).
% Explanation: Twain frequently used satire in his works.
born_in(mark_twain, missouri).
% Explanation: Mark Twain was born in Florida, Missouri, in 1835.
died_in(mark_twain, x1910).
% Explanation: Mark Twain died in 1910.
deals_with(the_adventures_of_huckleberry_finn, racism_and_slavery).
% Explanation: The novel directly addresses issues of racism and slavery in antebellum America.
influenced_by(the_adventures_of_huckleberry_finn, american_dialect).
% Explanation: Twain used regional dialects to create authentic dialogue.
influenced_by(the_adventures_of_huckleberry_finn, missouri).
% Explanation: The setting and characters are influenced by Twain’s childhood experiences in Missouri.
lived_in(mark_twain, hartford_connecticut).
% Explanation: Twain lived for many years in Hartford, where he wrote some of his famous works.
active_during(mark_twain, gilded_age).
% Explanation: Twain coined the term 'Gilded Age' for the late 19th-century era of rapid change.
genre_of(a_connecticut_yankee_in_king_arthurs_court, satire).
% Explanation: The novel is a satirical commentary on romanticized chivalry and social hierarchy.
genre_of(life_on_the_mississippi, memoir).
% Explanation: It is a memoir and travel book.
adapted_into(the_adventures_of_tom_sawyer, film_adaptations_of_twains_works).
% Explanation: The novel has been adapted into various plays, films, and television series.
adapted_into(the_adventures_of_huckleberry_finn, film_adaptations_of_twains_works).
% Explanation: Huckleberry Finn has been frequently adapted for stage and screen.
influenced(mark_twain, ernest_hemingway).
% Explanation: Hemingway credited Twain's works with influencing modern American literature.
influenced(mark_twain, william_faulkner).
% Explanation: Faulkner considered Twain the 'father of American literature.'
considered_as(the_adventures_of_huckleberry_finn, first_great_american_novel).
% Explanation: The novel is often called the first true American novel.
canonical_work_of(the_adventures_of_huckleberry_finn, american_literature_canon).
% Explanation: The novel is widely studied in American literature.
noteworthy_for(mark_twain, literary_humor).
% Explanation: Twain's wit and humor are signature elements of his style.
concept(american_realism_in_literature).
concept(american_realism).
related_to(american_realism, american_realism_in_literature).
concept(regionalism).
related_to(regionalism, american_realism_in_literature).
concept(naturalism).
related_to(naturalism, american_realism_in_literature).
concept(verisimilitude).
related_to(verisimilitude, american_realism_in_literature).
concept(ordinary_characters).
related_to(ordinary_characters, american_realism_in_literature).
concept(everyday_life).
related_to(everyday_life, american_realism_in_literature).
concept(social_critique).
related_to(social_critique, american_realism_in_literature).
concept(postcivil_war_america).
related_to(postcivil_war_america, american_realism_in_literature).
concept(late_19th_century).
related_to(late_19th_century, american_realism_in_literature).
related_to(mark_twain, american_realism_in_literature).
concept(henry_james).
related_to(henry_james, american_realism_in_literature).
concept(william_dean_howells).
related_to(william_dean_howells, american_realism_in_literature).
concept(kate_chopin).
related_to(kate_chopin, american_realism_in_literature).
concept(edith_wharton).
related_to(edith_wharton, american_realism_in_literature).
concept(stephen_crane).
related_to(stephen_crane, american_realism_in_literature).
related_to(the_adventures_of_huckleberry_finn, american_realism_in_literature).
concept(the_rise_of_silas_lapham).
related_to(the_rise_of_silas_lapham, american_realism_in_literature).
concept(the_awakening).
related_to(the_awakening, american_realism_in_literature).
concept(the_red_badge_of_courage).
related_to(the_red_badge_of_courage, american_realism_in_literature).
concept(the_age_of_innocence).
related_to(the_age_of_innocence, american_realism_in_literature).
concept(daisy_miller).
related_to(daisy_miller, american_realism_in_literature).
related_to(mississippi_river, american_realism_in_literature).
concept(new_england).
related_to(new_england, american_realism_in_literature).
concept(urban_life).
related_to(urban_life, american_realism_in_literature).
concept(class_distinctions).
related_to(class_distinctions, american_realism_in_literature).
concept(psychological_depth).
related_to(psychological_depth, american_realism_in_literature).
concept(local_color).
related_to(local_color, american_realism_in_literature).
concept(written_by).
related_to(written_by, american_realism_in_literature).
concept(published_in).
related_to(published_in, american_realism_in_literature).
concept(set_in).
related_to(set_in, american_realism_in_literature).
concept(protagonist_of).
related_to(protagonist_of, american_realism_in_literature).
concept(genre_of).
related_to(genre_of, american_realism_in_literature).
concept(movement).
related_to(movement, american_realism_in_literature).
concept(influenced_by).
related_to(influenced_by, american_realism_in_literature).
concept(adapted_into).
related_to(adapted_into, american_realism_in_literature).
concept(legacy).
related_to(legacy, american_realism_in_literature).
concept(modernism).
related_to(modernism, american_realism_in_literature).
concept(harlem_renaissance).
related_to(harlem_renaissance, american_realism_in_literature).
concept(x20th_century_american_fiction).
related_to(x20th_century_american_fiction, american_realism_in_literature).
emphasizes(american_realism, verisimilitude).
% Explanation: American Realism focuses on accurate, lifelike depictions of the world.
focuses_on(american_realism, everyday_life).
% Explanation: The movement depicts the mundane aspects of daily existence.
centers_on(american_realism, ordinary_characters).
% Explanation: Unlike previous movements, Realism focused on common people instead of heroes or aristocrats.
overlaps_with(american_realism, regionalism).
% Explanation: Regionalism is considered both a subset and companion movement to Realism.
influenced(american_realism, naturalism).
% Explanation: Naturalism developed from Realist techniques and themes, emphasizing determinism.
extends(naturalism, social_critique).
% Explanation: Naturalist works often critique societal and environmental influences on individuals.
responds_to(american_realism, postcivil_war_america).
% Explanation: The movement emerged in response to social changes after the Civil War.
flourished_in(american_realism, late_19th_century).
% Explanation: Primary period of activity for American Realism (c. 1865–1910).
movement(mark_twain, american_realism).
% Explanation: Twain is a key figure in the American Realist movement.
movement(henry_james, american_realism).
% Explanation: James is considered one of the central American Realists.
movement(william_dean_howells, american_realism).
% Explanation: Often called the 'Dean of American Realism.'
movement(kate_chopin, regionalism).
% Explanation: Chopin's works often display both Realist and Regionalist characteristics.
movement(edith_wharton, american_realism).
% Explanation: Wharton is a notable Realist and early Modernist.
movement(stephen_crane, naturalism).
% Explanation: Crane’s works exemplify naturalist offshoots of Realism.
written_by(the_rise_of_silas_lapham, william_dean_howells).
% Explanation: A prime example of Realist fiction.
written_by(the_awakening, kate_chopin).
% Explanation: Displays Realist and Regionalist qualities.
written_by(the_red_badge_of_courage, stephen_crane).
% Explanation: A classic of Realist and Naturalist writing.
written_by(the_age_of_innocence, edith_wharton).
% Explanation: A work of late American Realism.
written_by(daisy_miller, henry_james).
% Explanation: A notable Realist novella.
published_in(the_rise_of_silas_lapham, x1885).
% Explanation: Published during the height of American Realism.
published_in(the_awakening, x1899).
% Explanation: Reflects turn-of-the-century concerns.
published_in(the_red_badge_of_courage, x1895).
% Explanation: Published at the end of the Realist period.
published_in(the_age_of_innocence, x1920).
% Explanation: Blends Realist and Modernist elements.
published_in(daisy_miller, x1878).
% Explanation: Early work of American Realism.
set_in(the_rise_of_silas_lapham, urban_life).
% Explanation: Set in Boston, reflecting changes in urban America.
set_in(the_awakening, new_orleans_and_gulf_coast).
% Explanation: Evokes the life and customs of Louisiana.
set_in(the_red_badge_of_courage, american_civil_war).
% Explanation: Centers on the inner experience of a Civil War soldier.
set_in(the_age_of_innocence, new_york_gilded_age).
% Explanation: Explores elite society in historical NYC.
set_in(daisy_miller, europe).
% Explanation: Follows American expatriate experience abroad.
protagonist_of(huckleberry_finn, the_adventures_of_huckleberry_finn).
% Explanation: The central, ordinary boy hero.
protagonist_of(silas_lapham, the_rise_of_silas_lapham).
% Explanation: Self-made businessman protagonist.
protagonist_of(edna_pontellier, the_awakening).
% Explanation: Explores the psychological depth typical of Realism.
protagonist_of(henry_fleming, the_red_badge_of_courage).
% Explanation: A young, ordinary soldier with great complexity.
protagonist_of(newland_archer, the_age_of_innocence).
% Explanation: A conflicted upper-class New Yorker.
protagonist_of(daisy_miller_character, daisy_miller).
% Explanation: Typical of the psychological realism of Henry James.
genre_of(the_adventures_of_huckleberry_finn, realist_novel).
% Explanation: Blends Realism with social satire.
genre_of(the_rise_of_silas_lapham, realist_novel).
% Explanation: Prototypical Realist work.
genre_of(the_awakening, realist_novel).
% Explanation: Depicts internal and social conflicts.
genre_of(the_red_badge_of_courage, realist_novel).
% Explanation: Uses realistic language and perspective.
genre_of(daisy_miller, novella).
% Explanation: Short Realist work.
subset_of(regionalism, american_realism).
% Explanation: Regionalist works are often considered Realist in nature.
characteristic_of(local_color, regionalism).
% Explanation: Local color writing focuses on specific geographical settings, dialect, and customs.
depicted_by(everyday_life, american_realism).
% Explanation: Central element depicted within the movement.
theme_in(class_distinctions, american_realism).
% Explanation: Attention to social hierarchies and economics.
technique_of(psychological_depth, american_realism).
% Explanation: Focus on the nuanced interior life of characters.
influenced_by(american_realism, european_realism).
% Explanation: Inspired by French and Russian realism (e.g., Balzac, Flaubert, Tolstoy).
influenced(american_realism, modernism).
% Explanation: Helped set the stage for Modernist experimentation by rejecting romantic idealization.
influenced(american_realism, x20th_century_american_fiction).
% Explanation: Realist methods and themes persisted in literature of later periods.
influenced(american_realism, harlem_renaissance).
% Explanation: Helped shape the truthful depiction of African American experience.
adapted_into(the_age_of_innocence, the_age_of_innocence_1993_film).
% Explanation: Wharton's Realist novel was adapted into a film directed by Martin Scorsese.
