% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Michel Foucault
% Max depth: 1, Max related topics per node: 1

concept(michel_foucault).
concept(powerknowledge).
related_to(powerknowledge, michel_foucault).
concept(discourse).
related_to(discourse, michel_foucault).
concept(biopower).
related_to(biopower, michel_foucault).
concept(disciplinary_power).
related_to(disciplinary_power, michel_foucault).
concept(governmentality).
related_to(governmentality, michel_foucault).
concept(genealogy).
related_to(genealogy, michel_foucault).
concept(archaeology).
related_to(archaeology, michel_foucault).
concept(panopticism).
related_to(panopticism, michel_foucault).
concept(subjectivation).
related_to(subjectivation, michel_foucault).
concept(carceral_society).
related_to(carceral_society, michel_foucault).
concept(episteme).
related_to(episteme, michel_foucault).
concept(madness_and_civilization).
related_to(madness_and_civilization, michel_foucault).
concept(the_order_of_things).
related_to(the_order_of_things, michel_foucault).
concept(discipline_and_punish).
related_to(discipline_and_punish, michel_foucault).
concept(the_history_of_sexuality).
related_to(the_history_of_sexuality, michel_foucault).
concept(structuralism).
related_to(structuralism, michel_foucault).
concept(poststructuralism).
related_to(poststructuralism, michel_foucault).
concept(claude_lévistrauss).
related_to(claude_lévistrauss, michel_foucault).
concept(louis_althusser).
related_to(louis_althusser, michel_foucault).
concept(jacques_derrida).
related_to(jacques_derrida, michel_foucault).
concept(gilles_deleuze).
related_to(gilles_deleuze, michel_foucault).
concept(jeanpaul_sartre).
related_to(jeanpaul_sartre, michel_foucault).
concept(friedrich_nietzsche).
related_to(friedrich_nietzsche, michel_foucault).
concept(karl_marx).
related_to(karl_marx, michel_foucault).
concept(sigmund_freud).
related_to(sigmund_freud, michel_foucault).
concept(lived_duringmichel_foucault_19261984).
related_to(lived_duringmichel_foucault_19261984, michel_foucault).
concept(school_of_thoughtmichel_foucault_poststructuralism).
related_to(school_of_thoughtmichel_foucault_poststructuralism, michel_foucault).
concept(school_of_thoughtmichel_foucault_postmodernism).
related_to(school_of_thoughtmichel_foucault_postmodernism, michel_foucault).
concept(main_workmichel_foucault_discipline_and_punish).
related_to(main_workmichel_foucault_discipline_and_punish, michel_foucault).
concept(main_workmichel_foucault_the_history_of_sexuality).
related_to(main_workmichel_foucault_the_history_of_sexuality, michel_foucault).
concept(main_workmichel_foucault_madness_and_civilization).
related_to(main_workmichel_foucault_madness_and_civilization, michel_foucault).
concept(main_workmichel_foucault_the_order_of_things).
related_to(main_workmichel_foucault_the_order_of_things, michel_foucault).
developed_by(powerknowledge, michel_foucault).
% Explanation: Foucault formulated the concept that power and knowledge are intertwined and shape each other.
developed_by(discourse, michel_foucault).
% Explanation: Foucault reconceptualized discourse as systems of thought that shape knowledge and social practices.
developed_by(biopower, michel_foucault).
% Explanation: Foucault defined biopower as practices of modern states to regulate populations.
developed_by(disciplinary_power, michel_foucault).
% Explanation: He analyzed disciplinary power as a means to control bodies, especially in 'Discipline and Punish.'
found_in(disciplinary_power, panopticism).
% Explanation: Panopticism is a model of disciplinary power described by Foucault.
originates_from(panopticism, benthams_panopticon).
% Explanation: Foucault adapted Jeremy Bentham's Panopticon as a metaphor for modern surveillance societies.
developed_by(governmentality, michel_foucault).
% Explanation: Foucault developed the concept of governmentality to describe the art of governing beyond the state.
developed_by(genealogy, michel_foucault).
% Explanation: Foucault used genealogy as a method inspired by Nietzsche to analyze history.
inspired_by(genealogy, friedrich_nietzsche).
% Explanation: Foucault's genealogical method is based on Nietzsche's critique of history and morals.
developed_by(archaeology, michel_foucault).
% Explanation: Archaeology is Foucault's method for analyzing historical discourses.
developed_by(subjectivation, michel_foucault).
% Explanation: He examined how subjects are constituted through power relations and discourses.
developed_by(carceral_society, michel_foucault).
% Explanation: Describes the pervasiveness of disciplinary mechanisms throughout society.
developed_by(episteme, michel_foucault).
% Explanation: Foucault introduced 'episteme' as the underlying logic of knowledge in an era.
main_work(madness_and_civilization, michel_foucault).
% Explanation: Published in 1961, it analyzes the history of madness.
main_work(the_order_of_things, michel_foucault).
% Explanation: Published in 1966, it explores the history of the sciences and episteme.
main_work(discipline_and_punish, michel_foucault).
% Explanation: 1975 work exploring the genealogy of prisons and disciplinary power.
main_work(the_history_of_sexuality, michel_foucault).
% Explanation: Series started 1976, examining sexuality, power, and biopolitics.
first_appeared(powerknowledge, x1970s).
% Explanation: Foucault's research from the mid-1970s onward focused on this concept.
first_appeared(biopower, x1970s).
% Explanation: Discussed primarily in 'The History of Sexuality, Vol. 1' (1976).
first_appeared(genealogy, early_1970s).
% Explanation: Shift from archaeology to genealogy in Foucault's work.
first_appeared(archaeology, x1960s).
% Explanation: First fully developed in 'The Archaeology of Knowledge' (1969).
first_appeared(episteme, x1966).
% Explanation: Key theme in 'The Order of Things.'
contemporary_of(michel_foucault, jacques_derrida).
% Explanation: Both active in late 20th-century French philosophy.
contemporary_of(michel_foucault, louis_althusser).
% Explanation: Both taught at the École Normale Supérieure and influenced each other.
contemporary_of(michel_foucault, claude_lévistrauss).
% Explanation: Both key figures in French structuralism and its aftermath.
contemporary_of(michel_foucault, gilles_deleuze).
% Explanation: Deleuze wrote extensively on Foucault's philosophy.
influenced_by(michel_foucault, friedrich_nietzsche).
% Explanation: Foucault adapted Nietzsche’s genealogical approach.
influenced_by(michel_foucault, karl_marx).
% Explanation: Foucault’s analysis of power and institutions draws on Marxist critique.
influenced_by(michel_foucault, sigmund_freud).
% Explanation: Foucault engages psychoanalysis in his theories of subjectivation and sexuality.
criticized_by(michel_foucault, jürgen_habermas).
% Explanation: Habermas critiqued Foucault’s apparent relativism and lack of normative foundation.
criticized_by(discipline_and_punish, critical_criminology).
% Explanation: Foucault's approach was debated for historicizing punishment rather than offering reform proposals.
school_of_thought(poststructuralism, michel_foucault).
% Explanation: Foucault is a key figure in post-structuralist philosophy.
school_of_thought(postmodernism, michel_foucault).
% Explanation: Often associated with postmodernism due to critique of universal truths.
school_of_thought(structuralism, claude_lévistrauss).
% Explanation: Lévi-Strauss founded French structural anthropology, influencing Foucault’s early work.
response_to(structuralism, marxism).
% Explanation: Structuralists proposed new models of understanding culture beyond economic reductionism.
response_to(poststructuralism, structuralism).
% Explanation: Post-structuralists, including Foucault, critiqued limitations of structuralist models.
school_of_thought(jacques_derrida, poststructuralism).
% Explanation: Derrida and Foucault were both post-structuralists, often debating each other.
school_of_thought(gilles_deleuze, poststructuralism).
% Explanation: Deleuze, like Foucault, challenged structuralist and humanist paradigms.
related_to(powerknowledge, powerknowledge).
related_to(discourse, powerknowledge).
related_to(biopower, powerknowledge).
related_to(disciplinary_power, powerknowledge).
related_to(genealogy, powerknowledge).
concept(regimes_of_truth).
related_to(regimes_of_truth, powerknowledge).
concept(archaeology_of_knowledge).
related_to(archaeology_of_knowledge, powerknowledge).
related_to(panopticism, powerknowledge).
concept(ideology).
related_to(ideology, powerknowledge).
concept(sovereign_power).
related_to(sovereign_power, powerknowledge).
related_to(governmentality, powerknowledge).
related_to(subjectivation, powerknowledge).
related_to(episteme, powerknowledge).
concept(hegemony).
related_to(hegemony, powerknowledge).
concept(surveillance).
related_to(surveillance, powerknowledge).
concept(resistance).
related_to(resistance, powerknowledge).
main_work(powerknowledge, discipline_and_punish).
% Explanation: One of the key works where Foucault elaborates power/knowledge.
main_work(powerknowledge, the_history_of_sexuality_vol_1).
% Explanation: Another foundational text by Foucault outlining power/knowledge.
lived_during(michel_foucault, x19261984).
% Explanation: Lifespan of Michel Foucault.
school_of_thought(michel_foucault, poststructuralism).
% Explanation: Foucault is considered a post-structuralist thinker.
school_of_thought(michel_foucault, french_theory).
% Explanation: Foucault is a major figure in French Theory.
closely_linked_to(discourse, powerknowledge).
% Explanation: Discourse is the medium through which power/knowledge operates.
response_to(biopower, sovereign_power).
% Explanation: Bio-power shifts analysis from traditional sovereign power to regulation of populations.
developed_by(genealogy, friedrich_nietzsche).
% Explanation: Nietzsche developed the method of genealogy, which Foucault adapted for his studies.
applied_by(genealogy, michel_foucault).
% Explanation: Foucault uses genealogy to analyze the historical formation of discourses and power relations.
developed_by(archaeology_of_knowledge, michel_foucault).
% Explanation: Foucault's early method for examining historical discursive formations.
main_work(archaeology_of_knowledge, the_archaeology_of_knowledge).
% Explanation: Title of Foucault's book outlining this method.
response_to(genealogy, archaeology_of_knowledge).
% Explanation: Genealogy supplanted Foucault’s archaeological method as his later approach.
developed_by(panopticism, michel_foucault).
% Explanation: Panopticism is Foucault's theory of surveillance and control via visibility.
main_work(panopticism, discipline_and_punish).
% Explanation: Panopticism is discussed in detail in this work.
function_of(surveillance, panopticism).
% Explanation: Surveillance is the key mechanism described by panopticism.
operates_through(disciplinary_power, surveillance).
% Explanation: Disciplinary power functions through ongoing observation and normalization.
developed_by(regimes_of_truth, michel_foucault).
% Explanation: Foucault theorizes regimes of truth as historically contingent truths enforced by power.
constitutes(powerknowledge, regimes_of_truth).
% Explanation: Power/knowledge establishes what counts as truth in society.
process_of(subjectivation, powerknowledge).
% Explanation: Subjectivation refers to how individuals are shaped and constituted by power/knowledge relations.
lived_during(friedrich_nietzsche, x18441900).
% Explanation: Lifespan of Friedrich Nietzsche.
school_of_thought(friedrich_nietzsche, existentialism).
% Explanation: Nietzsche is often associated with existentialism.
main_work(friedrich_nietzsche, on_the_genealogy_of_morals).
% Explanation: Key text developing the genealogy method.
criticized_by(powerknowledge, critical_theory).
% Explanation: Critical theorists argue Foucault underemphasizes ideology and collective resistance.
school_of_thought(critical_theory, frankfurt_school).
% Explanation: Critical Theory originates from the Frankfurt School.
criticizes(jürgen_habermas, foucault).
% Explanation: Habermas critiques Foucault for relativism and lack of normative grounding.
school_of_thought(jürgen_habermas, critical_theory).
% Explanation: Habermas is a leading figure in Critical Theory.
lived_during(jürgen_habermas, x1929present).
% Explanation: Lifespan of Habermas.
contemporary_of(jürgen_habermas, michel_foucault).
% Explanation: Both were leading European philosophers in the late 20th century.
main_work(episteme, the_order_of_things).
% Explanation: Foucault introduces and elaborates the concept of 'episteme' here.
influenced_by(powerknowledge, marxist_theory).
% Explanation: Foucault draws from Marxist critiques of ideology but moves beyond them.
response_to(powerknowledge, ideology).
% Explanation: Foucault’s power/knowledge concept replaces ideology as the main analytic tool.
developed_by(ideology, karl_marx).
% Explanation: Marx formulated the concept of ideology as false consciousness.
lived_during(karl_marx, x18181883).
% Explanation: Lifespan of Karl Marx.
school_of_thought(karl_marx, marxism).
% Explanation: Founder of Marxist theory.
main_work(karl_marx, capital).
% Explanation: Main economic critique, also discusses ideology.
criticized_by(powerknowledge, traditional_marxism).
% Explanation: Marxists argue Foucault neglects class and economic structures.
developed_by(hegemony, antonio_gramsci).
% Explanation: Hegemony explains how ideology maintains power, related but distinct from Foucault’s notion.
lived_during(antonio_gramsci, x18911937).
% Explanation: Lifespan of Gramsci.
school_of_thought(antonio_gramsci, marxism).
% Explanation: Gramsci is a leading Western Marxist.
main_work(biopower, the_history_of_sexuality_vol_1).
% Explanation: Foucault introduces and analyzes bio-power here.
response_to(governmentality, sovereign_power).
% Explanation: Governmentality signifies a shift from sovereignty to management of populations.
developed_by(resistance, michel_foucault).
% Explanation: Foucault claims that where there is power, there is always resistance.
response_to(resistance, powerknowledge).
% Explanation: Resistance is always possible within systems of power/knowledge.
