% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Jean-Paul Sartre
% Max depth: 1, Max related topics per node: 1

concept(jeanpaul_sartre).
concept(existentialism).
related_to(existentialism, jeanpaul_sartre).
concept(phenomenology).
related_to(phenomenology, jeanpaul_sartre).
concept(beingforitself_êtrepoursoi).
related_to(beingforitself_êtrepoursoi, jeanpaul_sartre).
concept(beinginitself_êtreensoi).
related_to(beinginitself_êtreensoi, jeanpaul_sartre).
concept(bad_faith_mauvaise_foi).
related_to(bad_faith_mauvaise_foi, jeanpaul_sartre).
concept(authenticity).
related_to(authenticity, jeanpaul_sartre).
concept(freedom).
related_to(freedom, jeanpaul_sartre).
concept(responsibility).
related_to(responsibility, jeanpaul_sartre).
concept(absurdity).
related_to(absurdity, jeanpaul_sartre).
concept(nausea).
related_to(nausea, jeanpaul_sartre).
concept(the_other).
related_to(the_other, jeanpaul_sartre).
concept(nothingness).
related_to(nothingness, jeanpaul_sartre).
concept(humanism).
related_to(humanism, jeanpaul_sartre).
concept(marxism).
related_to(marxism, jeanpaul_sartre).
concept(radical_freedom).
related_to(radical_freedom, jeanpaul_sartre).
concept(existential_psychoanalysis).
related_to(existential_psychoanalysis, jeanpaul_sartre).
concept(anguish).
related_to(anguish, jeanpaul_sartre).
concept(engagement).
related_to(engagement, jeanpaul_sartre).
concept(existence_precedes_essence).
related_to(existence_precedes_essence, jeanpaul_sartre).
related_to(jeanpaul_sartre, jeanpaul_sartre).
concept(simone_de_beauvoir).
related_to(simone_de_beauvoir, jeanpaul_sartre).
concept(martin_heidegger).
related_to(martin_heidegger, jeanpaul_sartre).
concept(edmund_husserl).
related_to(edmund_husserl, jeanpaul_sartre).
concept(friedrich_nietzsche).
related_to(friedrich_nietzsche, jeanpaul_sartre).
concept(albert_camus).
related_to(albert_camus, jeanpaul_sartre).
concept(maurice_merleauponty).
related_to(maurice_merleauponty, jeanpaul_sartre).
concept(simone_weil).
related_to(simone_weil, jeanpaul_sartre).
concept(jeanpaul_sartres_being_and_nothingness).
related_to(jeanpaul_sartres_being_and_nothingness, jeanpaul_sartre).
concept(jeanpaul_sartres_existentialism_is_a_humanism).
related_to(jeanpaul_sartres_existentialism_is_a_humanism, jeanpaul_sartre).
concept(jeanpaul_sartres_nausea).
related_to(jeanpaul_sartres_nausea, jeanpaul_sartre).
concept(french_existentialism).
related_to(french_existentialism, jeanpaul_sartre).
concept(continental_philosophy).
related_to(continental_philosophy, jeanpaul_sartre).
developed_by(existentialism, jeanpaul_sartre).
% Explanation: Sartre is a major figure in the development of existentialist philosophy, especially in France.
lived_during(jeanpaul_sartre, x20th_century_19051980).
% Explanation: Sartre was active predominantly during the mid-20th century.
influenced_by(phenomenology, edmund_husserl).
% Explanation: Husserl founded phenomenology, which influenced Sartre's early philosophy.
influenced_by(existentialism, friedrich_nietzsche).
% Explanation: Nietzsche’s emphasis on individual existence and values influenced the existentialists, including Sartre.
influenced_by(existentialism, martin_heidegger).
% Explanation: Heidegger’s ontological analysis of existence influenced Sartre’s version of existentialism.
developed_by(beingforitself_êtrepoursoi, jeanpaul_sartre).
% Explanation: Sartre introduced the distinction between being-for-itself and being-in-itself in his philosophy.
developed_by(beinginitself_êtreensoi, jeanpaul_sartre).
% Explanation: Sartre developed the concept to describe the existence of objects.
developed_by(bad_faith_mauvaise_foi, jeanpaul_sartre).
% Explanation: Bad faith is a central concept in Sartre's philosophy, denoting self-deception.
contrasts_with(authenticity, bad_faith_mauvaise_foi).
% Explanation: Authenticity is achieved by overcoming bad faith and acknowledging one's freedom.
core_concept_of(freedom, existentialism).
% Explanation: Freedom is fundamental to existentialist philosophy as defined by Sartre.
developed_by(existence_precedes_essence, jeanpaul_sartre).
% Explanation: A defining concept of Sartre's existentialism, first famously articulated in the 1940s.
main_work(jeanpaul_sartres_being_and_nothingness, jeanpaul_sartre).
% Explanation: Published in 1943, it is Sartre’s major philosophical treatise.
main_work(jeanpaul_sartres_existentialism_is_a_humanism, jeanpaul_sartre).
% Explanation: A key 1946 lecture summarizing Sartre's existentialist views.
main_work(jeanpaul_sartres_nausea, jeanpaul_sartre).
% Explanation: A philosophical novel (1938) introducing key existentialist ideas.
school_of_thought(continental_philosophy, jeanpaul_sartre).
% Explanation: Sartre is part of continental philosophy, particularly the existentialist stream.
school_of_thought(french_existentialism, jeanpaul_sartre).
% Explanation: Sartre is the central figure in French existentialism.
school_of_thought(french_existentialism, simone_de_beauvoir).
% Explanation: De Beauvoir is a principal figure in French existentialism.
contemporary_of(simone_de_beauvoir, jeanpaul_sartre).
% Explanation: Beauvoir and Sartre were contemporaries, colleagues, and partners.
contemporary_of(jeanpaul_sartre, albert_camus).
% Explanation: Sartre and Camus were leading existentialist thinkers in mid-20th-century France.
developed_by(absurdity, albert_camus).
% Explanation: While Sartre discussed absurdity, Camus made it central to his philosophy.
thematized_in(absurdity, jeanpaul_sartres_nausea).
% Explanation: Absurdity and meaninglessness are key elements in 'Nausea'.
response_to(marxism, existentialism).
% Explanation: Sartre sought to synthesize existentialism with Marxism in his later work.
core_concept_of(radical_freedom, jeanpaul_sartre).
% Explanation: Radical freedom is the foundation of Sartre's blame and responsibility.
entails(freedom, responsibility).
% Explanation: According to Sartre, absolute freedom implies absolute responsibility for one's actions.
explored_in(nothingness, jeanpaul_sartres_being_and_nothingness).
% Explanation: Sartre analyzes the concept of nothingness extensively in his magnum opus.
criticized_by(existence_precedes_essence, essentialist_thinkers).
% Explanation: The claim is rejected by proponents of essentialist metaphysics.
promoted_by(authenticity, jeanpaul_sartre).
% Explanation: Living authentically is a major imperative in Sartre's existentialism.
central_to(anguish, existentialism).
% Explanation: Anguish is the emotional response to radical freedom.
developed_by(existential_psychoanalysis, jeanpaul_sartre).
% Explanation: Sartre proposed existential psychoanalysis as an alternative to Freudian psychoanalysis.
core_value_of(engagement, jeanpaul_sartre).
% Explanation: Sartre's later philosophy emphasized political and social commitment.
affirmed_by(humanism, jeanpaul_sartres_existentialism_is_a_humanism).
% Explanation: Sartre argued for an atheistic humanism grounded in freedom and responsibility.
developed_by(phenomenology, edmund_husserl).
% Explanation: Husserl is the founder of phenomenological philosophy.
modified_by(phenomenology, martin_heidegger).
% Explanation: Heidegger transformed phenomenology by focusing on the question of Being.
response_to(jeanpaul_sartre, martin_heidegger).
% Explanation: Sartre’s existentialism was partly a response to Heidegger’s work.
influenced_by(jeanpaul_sartre, edmund_husserl).
% Explanation: Sartre relied on Husserl’s phenomenological method in his early philosophy.
influenced_by(jeanpaul_sartre, martin_heidegger).
% Explanation: Heidegger’s analysis of existence influenced Sartre’s concepts of being.
influenced_by(jeanpaul_sartre, friedrich_nietzsche).
% Explanation: Nietzsche’s views on values and individuality shaped existentialist thought.
explored_by(nothingness, jeanpaul_sartre).
% Explanation: Nothingness is central in Sartre’s ontological analysis.
problem_of(the_other, intersubjectivity).
% Explanation: The Other is a key theme in Sartre’s exploration of consciousness and intersubjectivity.
contemporary_of(maurice_merleauponty, jeanpaul_sartre).
% Explanation: Merleau-Ponty and Sartre were both post-war French existential phenomenologists.
contemporary_of(simone_weil, jeanpaul_sartre).
% Explanation: Weil was a French contemporary of Sartre, although not aligned with existentialism.
theme_in(engagement, jeanpaul_sartres_political_writings).
% Explanation: Engagement refers to intellectual and political activism as promoted by Sartre in the 1940s-50s.
related_to(existence_precedes_essence, existentialism).
related_to(authenticity, existentialism).
related_to(absurdity, existentialism).
related_to(anguish, existentialism).
related_to(freedom, existentialism).
related_to(responsibility, existentialism).
related_to(bad_faith_mauvaise_foi, existentialism).
concept(alienation).
related_to(alienation, existentialism).
concept(despair).
related_to(despair, existentialism).
concept(subjectivity).
related_to(subjectivity, existentialism).
related_to(nothingness, existentialism).
concept(leap_of_faith).
related_to(leap_of_faith, existentialism).
concept(beingtowarddeath).
related_to(beingtowarddeath, existentialism).
concept(anxiety).
related_to(anxiety, existentialism).
related_to(the_other, existentialism).
concept(facticity).
related_to(facticity, existentialism).
concept(transcendence).
related_to(transcendence, existentialism).
concept(revolt).
related_to(revolt, existentialism).
concept(meaninglessness).
related_to(meaninglessness, existentialism).
concept(dread).
related_to(dread, existentialism).
concept(existential_crisis).
related_to(existential_crisis, existentialism).
concept(freedom_of_choice).
related_to(freedom_of_choice, existentialism).
developed_by(authenticity, martin_heidegger).
% Explanation: Heidegger described authenticity as owning one's existence and choices.
developed_by(anguish, jeanpaul_sartre).
% Explanation: Sartre discussed anguish arising from realization of total freedom and responsibility.
developed_by(freedom, jeanpaul_sartre).
% Explanation: Central to Sartrean existentialism, emphasizing radical freedom.
implied_by(responsibility, freedom).
% Explanation: Because humans are free, they are wholly responsible for their actions.
developed_by(alienation, jeanpaul_sartre).
% Explanation: Sartre describes alienation as estrangement from authentic self or others.
discussed_by(despair, søren_kierkegaard).
% Explanation: Kierkegaard explored despair as awareness of one's freedom and limitations.
emphasized_by(subjectivity, existentialism).
% Explanation: Existentialism foregrounds personal experience and subjectivity.
developed_by(nothingness, jeanpaul_sartre).
% Explanation: Sartre emphasized nothingness as inherent in consciousness and freedom.
developed_by(leap_of_faith, søren_kierkegaard).
% Explanation: Kierkegaard proposed that authentic religious belief requires a leap of faith.
developed_by(beingtowarddeath, martin_heidegger).
% Explanation: Heidegger described authenticity in facing one's own mortality.
developed_by(anxiety, martin_heidegger).
% Explanation: Heidegger analyzed anxiety as exposure to nothingness and freedom.
elaborated_by(the_other, jeanpaul_sartre).
% Explanation: Sartre focused on self-identity in relation to the Other.
discussed_by(facticity, martin_heidegger).
% Explanation: Heidegger explored facticity as the given conditions of existence.
described_by(transcendence, jeanpaul_sartre).
% Explanation: Sartre described transcendence as the capacity to project oneself beyond facticity.
developed_by(revolt, albert_camus).
% Explanation: Camus emphasized revolt as a response to life's absurdity.
central_to(meaninglessness, absurdity).
% Explanation: Absurdity arises from the conflict between seeking meaning and its absence.
developed_by(dread, søren_kierkegaard).
% Explanation: Kierkegaard viewed dread as a fundamental experience of confronting possibility.
arises_from(existential_crisis, meaninglessness).
% Explanation: Confrontation with life's meaninglessness triggers existential crisis.
implied_by(freedom_of_choice, freedom).
% Explanation: Freedom entails the necessity and burden of continual choice.
lived_during(jeanpaul_sartre, x19051980).
% Explanation: Sartre's major works appeared mid-20th century.
lived_during(martin_heidegger, x18891976).
% Explanation: Heidegger was active primarily in early-to-mid 20th century.
lived_during(søren_kierkegaard, x18131855).
% Explanation: Kierkegaard is seen as a precursor to existentialism in the 19th century.
lived_during(albert_camus, x19131960).
% Explanation: Camus wrote during World War II and postwar years.
lived_during(friedrich_nietzsche, x18441900).
% Explanation: Nietzsche is a 19th century forerunner of existentialist thought.
lived_during(simone_de_beauvoir, x19081986).
% Explanation: She contributed significantly to existentialism and feminist thought in the 20th century.
school_of_thought(jeanpaul_sartre, atheistic_existentialism).
% Explanation: Sartre is the leading figure of atheistic existentialism.
school_of_thought(søren_kierkegaard, christian_existentialism).
% Explanation: Kierkegaard is the primary figure in Christian existentialism.
school_of_thought(martin_heidegger, phenomenological_existentialism).
% Explanation: Heidegger integrates existentialism with phenomenology.
school_of_thought(albert_camus, absurdism).
% Explanation: Camus is often called a leading theorist of the absurd.
school_of_thought(simone_de_beauvoir, existentialist_feminism).
% Explanation: De Beauvoir applied existentialism to feminism.
main_work(jeanpaul_sartre, being_and_nothingness_1943).
% Explanation: Sartre's foundational text for existentialist philosophy.
main_work(martin_heidegger, being_and_time_1927).
% Explanation: Heidegger's central work, laying existential and phenomenological groundwork.
main_work(søren_kierkegaard, fear_and_trembling_1843).
% Explanation: Seminal text for existential and religious themes.
main_work(albert_camus, the_myth_of_sisyphus_1942).
% Explanation: Camus analyzes the absurd and responses to it.
main_work(simone_de_beauvoir, the_second_sex_1949).
% Explanation: De Beauvoir applies existentialism to the condition of women.
contemporary_of(jeanpaul_sartre, simone_de_beauvoir).
% Explanation: They were lifelong intellectual partners.
influenced_by(martin_heidegger, søren_kierkegaard).
% Explanation: Heidegger drew on Kierkegaard’s religious existentialism.
influenced_by(albert_camus, friedrich_nietzsche).
% Explanation: Nietzsche’s rejection of objective meaning inspired Camus.
influenced_by(simone_de_beauvoir, jeanpaul_sartre).
% Explanation: De Beauvoir’s philosophy was shaped by Sartrean existentialism.
criticized_by(athenian_philosophy_essence_precedes_existence, existentialism).
% Explanation: Existentialism opposes classical essentialism.
response_to(atheistic_existentialism, christian_existentialism).
% Explanation: Atheistic existentialism moves existentialist ideas outside the religious context.
