% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Simone de Beauvoir
% Max depth: 1, Max related topics per node: 1

concept(simone_de_beauvoir).
related_to(simone_de_beauvoir, simone_de_beauvoir).
concept(existentialism).
related_to(existentialism, simone_de_beauvoir).
concept(feminism).
related_to(feminism, simone_de_beauvoir).
concept(the_second_sex).
related_to(the_second_sex, simone_de_beauvoir).
concept(existential_feminism).
related_to(existential_feminism, simone_de_beauvoir).
concept(woman_as_other).
related_to(woman_as_other, simone_de_beauvoir).
concept(freedom_and_ambiguity).
related_to(freedom_and_ambiguity, simone_de_beauvoir).
concept(ethics_of_ambiguity).
related_to(ethics_of_ambiguity, simone_de_beauvoir).
concept(jeanpaul_sartre).
related_to(jeanpaul_sartre, simone_de_beauvoir).
concept(sexgender_distinction).
related_to(sexgender_distinction, simone_de_beauvoir).
concept(becoming_a_woman).
related_to(becoming_a_woman, simone_de_beauvoir).
concept(patriarchy).
related_to(patriarchy, simone_de_beauvoir).
concept(french_existentialism).
related_to(french_existentialism, simone_de_beauvoir).
concept(philosophy_of_existence).
related_to(philosophy_of_existence, simone_de_beauvoir).
concept(womens_liberation_movement).
related_to(womens_liberation_movement, simone_de_beauvoir).
concept(transcendence_and_immanence).
related_to(transcendence_and_immanence, simone_de_beauvoir).
concept(literature_as_philosophy).
related_to(literature_as_philosophy, simone_de_beauvoir).
concept(albert_camus).
related_to(albert_camus, simone_de_beauvoir).
concept(maurice_merleauponty).
related_to(maurice_merleauponty, simone_de_beauvoir).
concept(simone_weil).
related_to(simone_weil, simone_de_beauvoir).
concept(phenomenology).
related_to(phenomenology, simone_de_beauvoir).
concept(x1940s_french_philosophy).
related_to(x1940s_french_philosophy, simone_de_beauvoir).
concept(poststructuralism).
related_to(poststructuralism, simone_de_beauvoir).
concept(judith_butler).
related_to(judith_butler, simone_de_beauvoir).
main_work(simone_de_beauvoir, the_second_sex).
% Explanation: The Second Sex (1949) is Beauvoir's seminal philosophical and feminist text.
developed_by(simone_de_beauvoir, existential_feminism).
% Explanation: Beauvoir is widely credited as the founder of existentialist feminism.
synthesizes(existential_feminism, existentialism).
% Explanation: Existential feminism combines existentialist philosophy with feminist perspectives.
developed_by(simone_de_beauvoir, woman_as_other).
% Explanation: In The Second Sex, Beauvoir argues that women are constructed as 'the Other' in society.
articulated_in(woman_as_other, the_second_sex).
% Explanation: The concept of 'Woman as Other' is a central argument in The Second Sex.
developed_by(simone_de_beauvoir, sexgender_distinction).
% Explanation: She distinguished between biological sex and socially constructed gender roles.
further_developed_by(sexgender_distinction, judith_butler).
% Explanation: Judith Butler built upon Beauvoir’s sex-gender distinction in post-structuralist feminism.
school_of_thought(existentialism, simone_de_beauvoir).
% Explanation: Beauvoir is a prominent figure in existentialist philosophy.
contemporary_of(simone_de_beauvoir, jeanpaul_sartre).
% Explanation: Beauvoir and Sartre collaborated and were partners in intellectual and personal life.
articulated_in(freedom_and_ambiguity, ethics_of_ambiguity).
% Explanation: Beauvoir explores freedom and moral ambiguity in her earlier philosophical work.
main_work(simone_de_beauvoir, ethics_of_ambiguity).
% Explanation: The Ethics of Ambiguity (1947) is another influential philosophical work by Beauvoir.
lived_during(simone_de_beauvoir, x20th_century).
% Explanation: Beauvoir lived and worked primarily in the 20th century (1908–1986).
published_in(the_second_sex, x1949).
% Explanation: The Second Sex was published in 1949.
critized_by(simone_de_beauvoir, poststructuralism).
% Explanation: Post-structuralists such as Judith Butler have critiqued aspects of Beauvoir’s work.
contemporary_of(simone_de_beauvoir, albert_camus).
% Explanation: Beauvoir and Camus were key figures in mid-20th-century French existentialism.
contemporary_of(simone_de_beauvoir, maurice_merleauponty).
% Explanation: Beauvoir was a contemporary of phenomenologist Merleau-Ponty.
influenced_by(simone_de_beauvoir, simone_weil).
% Explanation: Beauvoir’s philosophical ideas were partly influenced by Weil.
school_of_thought(existentialism, jeanpaul_sartre).
% Explanation: Sartre was the leading figure in existentialism.
influenced_by(simone_de_beauvoir, jeanpaul_sartre).
% Explanation: Beauvoir was influenced by Sartre’s existentialist ideas but developed her own distinct positions.
response_to(existential_feminism, patriarchy).
% Explanation: Existential feminism directly challenges the structures of patriarchy.
school_of_thought(simone_de_beauvoir, feminism).
% Explanation: Beauvoir is a foundational figure in modern feminism.
influenced(the_second_sex, womens_liberation_movement).
% Explanation: The Second Sex was crucial to the theoretical and practical emergence of the late 20th-century women’s movement.
conceptualized_by(becoming_a_woman, simone_de_beauvoir).
% Explanation: She stated, 'One is not born, but rather becomes, a woman,' highlighting gender as a social process.
articulated_in(becoming_a_woman, the_second_sex).
% Explanation: This idea is central to The Second Sex’s chapter on childhood and socialization.
analyzed_by(transcendence_and_immanence, simone_de_beauvoir).
% Explanation: She examines how women are relegated to immanence (passivity) versus men’s transcendence (activity).
exemplified_by(literature_as_philosophy, simone_de_beauvoir).
% Explanation: Beauvoir often used novels and memoirs to explore philosophical questions.
influenced_by(phenomenology, simone_de_beauvoir).
% Explanation: Beauvoir incorporated themes from phenomenology (Husserl, Merleau-Ponty) into her work.
influenced_by(judith_butler, simone_de_beauvoir).
% Explanation: Butler’s gender theory is indebted to Beauvoir’s distinction between sex and gender.
concept(existentialist_feminism).
related_to(existentialist_feminism, existentialist_feminism).
concept(subjectobject_dichotomy).
related_to(subjectobject_dichotomy, existentialist_feminism).
concept(the_other).
related_to(the_other, existentialist_feminism).
concept(freedom).
related_to(freedom, existentialist_feminism).
concept(authenticity).
related_to(authenticity, existentialist_feminism).
concept(bad_faith).
related_to(bad_faith, existentialist_feminism).
concept(oppression).
related_to(oppression, existentialist_feminism).
concept(transcendence).
related_to(transcendence, existentialist_feminism).
concept(immanence).
related_to(immanence, existentialist_feminism).
concept(embodiment).
related_to(embodiment, existentialist_feminism).
related_to(patriarchy, existentialist_feminism).
concept(power).
related_to(power, existentialist_feminism).
concept(gender).
related_to(gender, existentialist_feminism).
concept(sex).
related_to(sex, existentialist_feminism).
concept(intersectionality).
related_to(intersectionality, existentialist_feminism).
concept(lived_experience).
related_to(lived_experience, existentialist_feminism).
concept(alienation).
related_to(alienation, existentialist_feminism).
concept(agency).
related_to(agency, existentialist_feminism).
related_to(simone_de_beauvoir, existentialist_feminism).
related_to(jeanpaul_sartre, existentialist_feminism).
related_to(simone_weil, existentialist_feminism).
related_to(judith_butler, existentialist_feminism).
related_to(the_second_sex, existentialist_feminism).
concept(french_feminism).
related_to(french_feminism, existentialist_feminism).
concept(secondwave_feminism).
related_to(secondwave_feminism, existentialist_feminism).
concept(poststructuralist_feminism).
related_to(poststructuralist_feminism, existentialist_feminism).
related_to(phenomenology, existentialist_feminism).
developed_by(existentialist_feminism, simone_de_beauvoir).
% Explanation: Simone de Beauvoir is credited with developing and articulating Existentialist Feminism, especially in her seminal work 'The Second Sex'.
response_to(existentialist_feminism, patriarchy).
% Explanation: Existentialist Feminism responds to the structures of patriarchy that define women as the 'other' and restrict their agency.
central_concept_of(the_other, existentialist_feminism).
% Explanation: The concept of 'the Other' is fundamental to Existentialist Feminism, describing how women are placed in a subordinate position by men.
used_by(subjectobject_dichotomy, existentialist_feminism).
% Explanation: The subject/object dichotomy is used to analyze gendered oppression, with men as subjects and women as objects.
analyzed_by(oppression, existentialist_feminism).
% Explanation: Existentialist Feminists analyze the experience and structures of oppression faced by women.
contrasted_with(immanence, transcendence).
% Explanation: Immanence signifies being constrained in a fixed role; transcendence refers to self-determination and agency. Existentialist Feminism posits women are often confined to immanence.
core_value_of(freedom, existentialist_feminism).
% Explanation: Freedom is a core existentialist value that Existentialist Feminism seeks to realize for women.
explored_by(bad_faith, existentialist_feminism).
% Explanation: Existentialist Feminism uses the concept of 'bad faith' to explain how women may internalize roles imposed by society.
lived_during(simone_de_beauvoir, x19081986).
% Explanation: Simone de Beauvoir lived during the 20th century.
lived_during(jeanpaul_sartre, x19051980).
% Explanation: Jean-Paul Sartre, whose existentialism influenced Beauvoir, lived during the 20th century.
school_of_thought(simone_de_beauvoir, existentialism).
% Explanation: Beauvoir is associated with existentialism as a philosophical movement.
school_of_thought(jeanpaul_sartre, existentialism).
% Explanation: Sartre was the leading figure in existentialist philosophy.
includes(french_feminism, existentialist_feminism).
% Explanation: Existentialist Feminism is seen as an early and foundational form of French Feminism.
influenced_by(secondwave_feminism, existentialist_feminism).
% Explanation: The concepts and analyses of Existentialist Feminism, especially from 'The Second Sex', greatly influenced the emergence of second-wave feminism in the 1960s and 1970s.
response_to(poststructuralist_feminism, existentialist_feminism).
% Explanation: Poststructuralist Feminism builds on and also criticizes Existentialist Feminism for its notions of identity, moving towards more fluid understandings.
influenced(phenomenology, existentialist_feminism).
% Explanation: Phenomenological approaches to lived experience shaped how Existentialist Feminism analyzes embodiment and subjectivity.
explored_in(embodiment, the_second_sex).
% Explanation: Beauvoir analyzes the lived experience of the female body in 'The Second Sex.'
developed_later_than(intersectionality, existentialist_feminism).
% Explanation: Intersectionality (1980s onward) expanded analyses of oppression to axes beyond gender, highlighting limitations of earlier existentialist feminism.
central_to(lived_experience, phenomenology).
% Explanation: Phenomenology centers on lived experience, which is pivotal in Existentialist Feminist theory.
distinguished_from(gender, sex).
% Explanation: Existentialist Feminism, particularly in Beauvoir's work, distinguishes between biologically determined sex and socially constructed gender.
contemporary_of(simone_weil, simone_de_beauvoir).
% Explanation: Simone Weil and Simone de Beauvoir were both active in French intellectual circles in the early-to-mid 20th century.
maintained_by(oppression, power).
% Explanation: Power dynamics are fundamental to the maintenance of women's oppression, analyzed by existentialist feminists.
central_value_of(agency, existentialist_feminism).
% Explanation: Agency, or the ability to act freely, is a key value in Existentialist Feminism's vision for women.
result_of(alienation, oppression).
% Explanation: Alienation is a psychological and existential result of oppression, as discussed in existentialist feminist writing.
