% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: The Space Race
% Max depth: 1, Max related topics per node: 1

concept(the_space_race).
related_to(the_space_race, the_space_race).
concept(cold_war).
related_to(cold_war, the_space_race).
concept(united_states).
related_to(united_states, the_space_race).
concept(soviet_union).
related_to(soviet_union, the_space_race).
concept(nasa).
related_to(nasa, the_space_race).
concept(sputnik_1).
related_to(sputnik_1, the_space_race).
concept(vostok_1).
related_to(vostok_1, the_space_race).
concept(apollo_11).
related_to(apollo_11, the_space_race).
concept(yuri_gagarin).
related_to(yuri_gagarin, the_space_race).
concept(john_f_kennedy).
related_to(john_f_kennedy, the_space_race).
concept(neil_armstrong).
related_to(neil_armstrong, the_space_race).
concept(sergei_korolev).
related_to(sergei_korolev, the_space_race).
concept(wernher_von_braun).
related_to(wernher_von_braun, the_space_race).
concept(luna_program).
related_to(luna_program, the_space_race).
concept(mercury_program).
related_to(mercury_program, the_space_race).
concept(gemini_program).
related_to(gemini_program, the_space_race).
concept(apollo_program).
related_to(apollo_program, the_space_race).
concept(saturn_v).
related_to(saturn_v, the_space_race).
concept(baikonur_cosmodrome).
related_to(baikonur_cosmodrome, the_space_race).
concept(cape_canaveral).
related_to(cape_canaveral, the_space_race).
concept(moon_landing).
related_to(moon_landing, the_space_race).
concept(space_shuttle).
related_to(space_shuttle, the_space_race).
concept(valentina_tereshkova).
related_to(valentina_tereshkova, the_space_race).
concept(alexei_leonov).
related_to(alexei_leonov, the_space_race).
concept(explorer_1).
related_to(explorer_1, the_space_race).
concept(laika).
related_to(laika, the_space_race).
concept(sputnik_2).
related_to(sputnik_2, the_space_race).
concept(kosmos).
related_to(kosmos, the_space_race).
concept(voskhod_program).
related_to(voskhod_program, the_space_race).
concept(end_of_space_race).
related_to(end_of_space_race, the_space_race).
concept(treaty_on_the_nonproliferation_of_nuclear_weapons).
related_to(treaty_on_the_nonproliferation_of_nuclear_weapons, the_space_race).
concept(moon).
related_to(moon, the_space_race).
occurred_in(the_space_race, x19571975).
% Explanation: The Space Race took place primarily between 1957 and 1975.
occurred_during(the_space_race, cold_war).
% Explanation: The Space Race was a key aspect of Cold War rivalry.
involved(the_space_race, united_states).
% Explanation: The United States was a principal participant.
involved(the_space_race, soviet_union).
% Explanation: The Soviet Union was a principal participant.
launched_by(sputnik_1, soviet_union).
% Explanation: Sputnik 1 was launched by the Soviet Union.
occurred_in(sputnik_1, x1957).
% Explanation: Sputnik 1 was launched on October 4, 1957.
preceded(sputnik_1, explorer_1).
% Explanation: Sputnik 1's launch preceded the U.S. response of Explorer 1.
launched_by(explorer_1, united_states).
% Explanation: Explorer 1 was launched by the United States.
occurred_in(explorer_1, x1958).
% Explanation: Explorer 1 was launched on January 31, 1958.
founded_in(nasa, x1958).
% Explanation: NASA was established in 1958.
founded_by(nasa, united_states).
% Explanation: NASA was created by the U.S. government.
launched_by(vostok_1, soviet_union).
% Explanation: Vostok 1 was a Soviet spaceflight.
occurred_in(vostok_1, x1961).
% Explanation: Vostok 1 launched in 1961 with Yuri Gagarin aboard.
carried(vostok_1, yuri_gagarin).
% Explanation: Yuri Gagarin was the cosmonaut on board Vostok 1.
born_in(yuri_gagarin, x1934).
% Explanation: Yuri Gagarin was born in 1934.
died_in(yuri_gagarin, x1968).
% Explanation: Yuri Gagarin died in 1968.
preceded(vostok_1, mercury_program).
% Explanation: Vostok 1's first manned flight preceded the first U.S. manned missions.
born_in(john_f_kennedy, x1917).
% Explanation: JFK was born in 1917.
died_in(john_f_kennedy, x1963).
% Explanation: JFK was assassinated in 1963.
announced(john_f_kennedy, apollo_program).
% Explanation: Kennedy publicly committed to landing a man on the Moon by the end of the 1960s.
carried_out_by(apollo_program, nasa).
% Explanation: The Apollo Program was a NASA endeavor.
part_of(apollo_11, apollo_program).
% Explanation: Apollo 11 was the mission that achieved the Moon landing.
occurred_in(apollo_11, x1969).
% Explanation: Apollo 11 landed on the Moon in July 1969.
landed_on(apollo_11, moon).
% Explanation: Apollo 11 was the first crewed mission to land on the Moon.
carried(apollo_11, neil_armstrong).
% Explanation: Neil Armstrong was a crew member of Apollo 11.
born_in(neil_armstrong, x1930).
% Explanation: Neil Armstrong was born in 1930.
died_in(neil_armstrong, x2012).
% Explanation: Neil Armstrong died in 2012.
born_in(sergei_korolev, x1907).
% Explanation: Korolev was born in 1907.
died_in(sergei_korolev, x1966).
% Explanation: Korolev died in 1966.
headed(sergei_korolev, soviet_space_program).
% Explanation: Korolev was the chief designer and engineer of the Soviet space effort.
contemporary_of(sergei_korolev, wernher_von_braun).
% Explanation: Both led their countries' rocket programs during the same period.
born_in(wernher_von_braun, x1912).
% Explanation: von Braun was born in 1912.
died_in(wernher_von_braun, x1977).
% Explanation: von Braun died in 1977.
headed(wernher_von_braun, saturn_v).
% Explanation: von Braun was responsible for developing the Saturn V rocket.
used_by(saturn_v, apollo_program).
% Explanation: Saturn V was the launch vehicle for the Apollo missions.
carried_out_by(luna_program, soviet_union).
% Explanation: The Luna Program was the Soviet lunar exploration program.
preceded(luna_program, apollo_program).
% Explanation: The Luna program's achievements (first Moon impact, flybys) occurred before the succesful Apollo landing.
succeeded(mercury_program, gemini_program).
% Explanation: Gemini expanded on Mercury's initial manned missions.
preceded(gemini_program, apollo_program).
% Explanation: Gemini mission achievements enabled Apollo's lunar attempts.
located_in(baikonur_cosmodrome, kazakhstan).
% Explanation: Main Soviet launch site.
launched_from(vostok_1, baikonur_cosmodrome).
% Explanation: Vostok 1 was launched from Baikonur.
located_in(cape_canaveral, florida).
% Explanation: Main U.S. launch site.
launched_from(apollo_11, cape_canaveral).
% Explanation: Apollo 11 departed from Cape Canaveral.
preceded(apollo_11, end_of_space_race).
% Explanation: The Moon landing is often seen as the Space Race's climax.
carried_out_by(kosmos, soviet_union).
% Explanation: Kosmos was a broad Soviet satellite program.
succeeded(voskhod_program, vostok_program).
% Explanation: Voskhod followed Vostok in manned Soviet missions.
born_in(valentina_tereshkova, x1937).
% Explanation: Tereshkova was born in 1937.
flew_on(valentina_tereshkova, vostok_6).
% Explanation: She was the first woman in space in 1963.
born_in(alexei_leonov, x1934).
% Explanation: Leonov was born in 1934.
performed(alexei_leonov, first_spacewalk).
% Explanation: Leonov performed the world's first EVA in 1965 during Voskhod 2.
launched_on(laika, sputnik_2).
% Explanation: Laika was the first animal to orbit Earth, on Sputnik 2 (1957).
preceded(sputnik_2, vostok_program).
% Explanation: Sputnik 2's biological payload preceded human spaceflight.
occurred_in(end_of_space_race, x1975).
% Explanation: Generally marked by the Apollo-Soyuz Test Project.
occurred_in(apollosoyuz_test_project, x1975).
% Explanation: First joint US-Soviet mission, marking collaborative era.
developed_by(space_shuttle, nasa).
% Explanation: NASA developed the reusable Space Shuttle after the Space Race.
signed_in(treaty_on_the_nonproliferation_of_nuclear_weapons, x1968).
% Explanation: Marked a parallel movement of cooperation amid space and nuclear rivalry.
contemporary_of(john_f_kennedy, nikita_khrushchev).
% Explanation: Kennedy and Khrushchev led their countries during the early Space Race.
related_to(apollo_program, apollo_program).
related_to(nasa, apollo_program).
related_to(mercury_program, apollo_program).
related_to(gemini_program, apollo_program).
related_to(saturn_v, apollo_program).
related_to(apollo_11, apollo_program).
concept(apollo_13).
related_to(apollo_13, apollo_program).
concept(apollo_1).
related_to(apollo_1, apollo_program).
concept(lunar_module).
related_to(lunar_module, apollo_program).
concept(command_module).
related_to(command_module, apollo_program).
concept(kennedy_space_center).
related_to(kennedy_space_center, apollo_program).
concept(lunar_surface).
related_to(lunar_surface, apollo_program).
related_to(united_states, apollo_program).
related_to(john_f_kennedy, apollo_program).
related_to(neil_armstrong, apollo_program).
concept(buzz_aldrin).
related_to(buzz_aldrin, apollo_program).
concept(michael_collins).
related_to(michael_collins, apollo_program).
concept(jim_lovell).
related_to(jim_lovell, apollo_program).
concept(gene_kranz).
related_to(gene_kranz, apollo_program).
related_to(wernher_von_braun, apollo_program).
related_to(cape_canaveral, apollo_program).
concept(houston_mission_control).
related_to(houston_mission_control, apollo_program).
related_to(moon_landing, apollo_program).
concept(apollo_17).
related_to(apollo_17, apollo_program).
concept(x1961).
related_to(x1961, apollo_program).
concept(x1972).
related_to(x1972, apollo_program).
operated_by(apollo_program, nasa).
% Explanation: NASA managed and led the Apollo Program.
preceded_by(apollo_program, gemini_program).
% Explanation: Gemini Program developed technology and procedures needed for Apollo.
preceded_by(gemini_program, mercury_program).
% Explanation: Mercury Program was the first US human spaceflight program, preceding Gemini.
initiated_by(apollo_program, john_f_kennedy).
% Explanation: Initiated after JFK’s 1961 speech setting goal to land a man on the Moon.
ruled_during(john_f_kennedy, x19611963).
% Explanation: Kennedy was US President during early Apollo planning.
occurred_in(apollo_program, x19611972).
% Explanation: Apollo’s active years were 1961–1972.
launched_from(apollo_program, kennedy_space_center).
% Explanation: All Saturn V launches took place at KSC in Florida.
much_activity_at(apollo_program, houston_mission_control).
% Explanation: Mission Control in Houston tracked all crewed Apollo missions.
carried(apollo_11, buzz_aldrin).
% Explanation: Buzz Aldrin was Lunar Module Pilot of Apollo 11.
carried(apollo_11, michael_collins).
% Explanation: Michael Collins was Command Module Pilot of Apollo 11.
born_in(buzz_aldrin, x1930).
% Explanation: Buzz Aldrin was born in 1930.
born_in(michael_collins, x1930).
% Explanation: Michael Collins was born in 1930.
died_in(michael_collins, x2021).
% Explanation: Michael Collins died in 2021.
contemporary_of(buzz_aldrin, neil_armstrong).
% Explanation: Aldrin and Armstrong were born the same year and flew Apollo 11 together.
occurred_in(apollo_13, x1970).
% Explanation: Apollo 13’s rescue mission was in April 1970.
commanded_by(apollo_13, jim_lovell).
% Explanation: Jim Lovell was the commander of Apollo 13.
born_in(jim_lovell, x1928).
% Explanation: Jim Lovell was born in 1928.
used_rocket(apollo_program, saturn_v).
% Explanation: Saturn V was the main launch vehicle for lunar missions.
designed_by(saturn_v, wernher_von_braun).
% Explanation: Von Braun was chief architect of the Saturn V rocket.
included_event(apollo_program, apollo_1).
% Explanation: Apollo 1 was the first crewed mission, tragically lost in a fire during testing.
occurred_in(apollo_1, x1967).
% Explanation: The Apollo 1 fire occurred in 1967 pre-launch testing.
landed_on(apollo_11, lunar_surface).
% Explanation: Apollo 11 achieved the first human landing on the Moon.
occurred_in(apollo_17, x1972).
% Explanation: Apollo 17 was the last crewed lunar mission, in December 1972.
preceded(apollo_11, apollo_17).
% Explanation: Apollo 17’s mission followed Apollo 11 and other Apollo landings.
launched_from(saturn_v, cape_canaveral).
% Explanation: Saturn V launches occurred at Cape Canaveral (Kennedy Space Center).
succeeded(apollo_program, mercury_program).
% Explanation: Apollo Program followed Mercury and Gemini in sequence.
objective(apollo_program, moon_landing).
% Explanation: Main goal was to land humans on the Moon and return them safely.
used_by(command_module, apollo_program).
% Explanation: Command Module was the crew compartment for Apollo missions.
used_by(lunar_module, apollo_program).
% Explanation: The Lunar Module landed astronauts on the Moon.
born_in(gene_kranz, x1933).
% Explanation: Gene Kranz was born in 1933.
role_in(gene_kranz, apollo_program).
% Explanation: Gene Kranz was a key flight director in Mission Control.
operated(united_states, nasa).
% Explanation: NASA is the US civilian space agency.
located_in(apollo_program, united_states).
% Explanation: The program was primarily operated and funded by the US government.
