% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: The Protestant Reformation
% Max depth: 1, Max related topics per node: 1

concept(the_protestant_reformation).
concept(protestant_reformation).
related_to(protestant_reformation, the_protestant_reformation).
concept(martin_luther).
related_to(martin_luther, the_protestant_reformation).
concept(ninetyfive_theses).
related_to(ninetyfive_theses, the_protestant_reformation).
concept(excommunication_of_luther).
related_to(excommunication_of_luther, the_protestant_reformation).
concept(diet_of_worms).
related_to(diet_of_worms, the_protestant_reformation).
concept(edict_of_worms).
related_to(edict_of_worms, the_protestant_reformation).
concept(johann_tetzel).
related_to(johann_tetzel, the_protestant_reformation).
concept(indulgences).
related_to(indulgences, the_protestant_reformation).
concept(papal_authority).
related_to(papal_authority, the_protestant_reformation).
concept(roman_catholic_church).
related_to(roman_catholic_church, the_protestant_reformation).
concept(salvation_by_faith_alone).
related_to(salvation_by_faith_alone, the_protestant_reformation).
concept(scripture_alone_sola_scriptura).
related_to(scripture_alone_sola_scriptura, the_protestant_reformation).
concept(john_calvin).
related_to(john_calvin, the_protestant_reformation).
concept(calvinism).
related_to(calvinism, the_protestant_reformation).
concept(institutes_of_the_christian_religion).
related_to(institutes_of_the_christian_religion, the_protestant_reformation).
concept(predestination).
related_to(predestination, the_protestant_reformation).
concept(geneva).
related_to(geneva, the_protestant_reformation).
concept(henry_viii).
related_to(henry_viii, the_protestant_reformation).
concept(english_reformation).
related_to(english_reformation, the_protestant_reformation).
concept(church_of_england_anglicanism).
related_to(church_of_england_anglicanism, the_protestant_reformation).
concept(act_of_supremacy).
related_to(act_of_supremacy, the_protestant_reformation).
concept(elizabeth_i).
related_to(elizabeth_i, the_protestant_reformation).
concept(philip_melanchthon).
related_to(philip_melanchthon, the_protestant_reformation).
concept(peace_of_augsburg).
related_to(peace_of_augsburg, the_protestant_reformation).
concept(thirty_years_war).
related_to(thirty_years_war, the_protestant_reformation).
concept(counterreformation).
related_to(counterreformation, the_protestant_reformation).
concept(council_of_trent).
related_to(council_of_trent, the_protestant_reformation).
concept(jesuits_society_of_jesus).
related_to(jesuits_society_of_jesus, the_protestant_reformation).
concept(ignatius_of_loyola).
related_to(ignatius_of_loyola, the_protestant_reformation).
concept(huldrych_zwingli).
related_to(huldrych_zwingli, the_protestant_reformation).
concept(swiss_reformation).
related_to(swiss_reformation, the_protestant_reformation).
concept(anabaptists).
related_to(anabaptists, the_protestant_reformation).
concept(charles_v_holy_roman_emperor).
related_to(charles_v_holy_roman_emperor, the_protestant_reformation).
concept(frederick_the_wise).
related_to(frederick_the_wise, the_protestant_reformation).
concept(lutheranism).
related_to(lutheranism, the_protestant_reformation).
concept(wittenberg).
related_to(wittenberg, the_protestant_reformation).
concept(augsburg).
related_to(augsburg, the_protestant_reformation).
concept(schmalkaldic_league).
related_to(schmalkaldic_league, the_protestant_reformation).
concept(german_peasants_war).
related_to(german_peasants_war, the_protestant_reformation).
concept(edict_of_nantes).
related_to(edict_of_nantes, the_protestant_reformation).
concept(huguenots).
related_to(huguenots, the_protestant_reformation).
concept(st_bartholomews_day_massacre).
related_to(st_bartholomews_day_massacre, the_protestant_reformation).
born_in(martin_luther, x1483).
% Explanation: Martin Luther was born in 1483.
died_in(martin_luther, x1546).
% Explanation: Martin Luther died in 1546.
wrote(martin_luther, ninetyfive_theses).
% Explanation: Luther wrote the Ninety-Five Theses.
occurred_in(ninetyfive_theses, x1517).
% Explanation: The Ninety-Five Theses were posted in 1517.
posted_in(ninetyfive_theses, wittenberg).
% Explanation: The Ninety-Five Theses were posted on the church door in Wittenberg.
challenged(ninetyfive_theses, indulgences).
% Explanation: The theses criticized the sale of indulgences.
promoted_by(indulgences, johann_tetzel).
% Explanation: Tetzel was a preacher selling indulgences.
authorized_by(indulgences, papal_authority).
% Explanation: The Pope authorized the sale of indulgences.
ruled_during(roman_catholic_church, papal_authority).
% Explanation: The Roman Catholic Church was headed by the Papacy.
occurred_in(diet_of_worms, x1521).
% Explanation: Luther was summoned to the Diet of Worms in 1521.
occurred_in(edict_of_worms, x1521).
% Explanation: The Edict of Worms, declaring Luther an outlaw, was issued in 1521.
preceded(diet_of_worms, edict_of_worms).
% Explanation: The Edict followed the Diet.
excommunicated_in(martin_luther, excommunication_of_luther).
% Explanation: Luther was excommunicated by the Pope.
occurred_in(excommunication_of_luther, x1521).
% Explanation: Luther was excommunicated in 1521.
protected(frederick_the_wise, martin_luther).
% Explanation: Frederick sheltered Luther after the Diet of Worms.
founded_by(lutheranism, martin_luther).
% Explanation: Lutheranism was inspired by the teachings of Martin Luther.
spread_in(lutheranism, german_states).
% Explanation: Lutheranism gained wide acceptance in many German territories.
occurred_in(peace_of_augsburg, x1555).
% Explanation: The Peace of Augsburg was concluded in 1555.
established(peace_of_augsburg, cuius_regio_eius_religio).
% Explanation: The Peace allowed rulers to choose the religion of their states.
born_in(john_calvin, x1509).
% Explanation: Calvin was born in 1509.
died_in(john_calvin, x1564).
% Explanation: Calvin died in 1564.
wrote(john_calvin, institutes_of_the_christian_religion).
% Explanation: A foundational text for Reformed theology.
founded_by(calvinism, john_calvin).
% Explanation: Calvinism was developed from Calvin’s teachings.
centered_in(calvinism, geneva).
% Explanation: Calvinism became centered in Geneva.
emphasized_doctrine(calvinism, predestination).
% Explanation: Predestination was a key teaching in Calvinism.
born_in(huldrych_zwingli, x1484).
% Explanation: Zwingli was born in 1484.
died_in(huldrych_zwingli, x1531).
% Explanation: Zwingli died in 1531.
led_by(swiss_reformation, huldrych_zwingli).
% Explanation: The Swiss Reformation was led by Zwingli.
occurred_in(swiss_reformation, zurich).
% Explanation: The Swiss Reformation started in Zurich.
originated_during(anabaptists, protestant_reformation).
% Explanation: The Anabaptist movement emerged as a radical reform group.
born_in(henry_viii, x1491).
% Explanation: Henry VIII was born in 1491.
died_in(henry_viii, x1547).
% Explanation: Henry VIII died in 1547.
initiated_by(english_reformation, henry_viii).
% Explanation: Henry VIII triggered the English split from Rome.
founded_by(church_of_england_anglicanism, henry_viii).
% Explanation: Henry VIII founded the Anglican Church.
occurred_in(act_of_supremacy, x1534).
% Explanation: The Act of Supremacy was passed in 1534.
established(act_of_supremacy, supreme_headship_of_henry_viii_over_the_church_of_england).
% Explanation: Declared Henry as head of the Church of England.
born_in(elizabeth_i, x1533).
% Explanation: Elizabeth I was born in 1533.
died_in(elizabeth_i, x1603).
% Explanation: Elizabeth I died in 1603.
ruled_during(elizabeth_i, x15581603).
% Explanation: Elizabeth I reigned during this period.
continued_under(english_reformation, elizabeth_i).
% Explanation: Elizabeth finalized Anglican settlement.
born_in(philip_melanchthon, x1497).
% Explanation: Melanchthon was Luther’s collaborator, born in 1497.
died_in(philip_melanchthon, x1560).
% Explanation: Melanchthon died in 1560.
collaborated_with(martin_luther, philip_melanchthon).
% Explanation: Melanchthon was a close colleague of Luther.
succeeded(peace_of_augsburg, schmalkaldic_league).
% Explanation: The Peace followed conflicts involving the Schmalkaldic League.
preceded(protestant_reformation, counterreformation).
% Explanation: The Counter-Reformation responded to Protestantism.
led_to(counterreformation, council_of_trent).
% Explanation: Council of Trent was a major Catholic reform event.
occurred_in(council_of_trent, x15451563).
% Explanation: The Council met intermittently during these years.
founded_by(jesuits_society_of_jesus, ignatius_of_loyola).
% Explanation: Ignatius founded the Jesuits, key figures in the Counter-Reformation.
born_in(ignatius_of_loyola, x1491).
% Explanation: Ignatius of Loyola was born in 1491.
died_in(ignatius_of_loyola, x1556).
% Explanation: Ignatius died in 1556.
occurred_in(thirty_years_war, x16181648).
% Explanation: Thirty Years' War spanned these years.
rooted_in(thirty_years_war, religious_conflict_from_protestant_reformation).
% Explanation: The war was caused by religious strife stirred by the Reformation.
occurred_in(edict_of_nantes, x1598).
% Explanation: Edict of Nantes issued in 1598.
provided_for(edict_of_nantes, huguenots).
% Explanation: Edict granted French Protestants (Huguenots) religious right.
occurred_in(st_bartholomews_day_massacre, x1572).
% Explanation: The massacre took place in 1572.
targeted(st_bartholomews_day_massacre, huguenots).
% Explanation: Mass killing of French Protestants.
emphasized(martin_luther, salvation_by_faith_alone).
% Explanation: Luther taught that salvation is by faith alone.
emphasized(martin_luther, scripture_alone_sola_scriptura).
% Explanation: Luther advocated the Bible as the sole authority.
ruled_during(charles_v_holy_roman_emperor, reformation_conflicts_in_germany).
% Explanation: Charles V was Holy Roman Emperor during the height of Reformation.
contemporary_of(charles_v_holy_roman_emperor, martin_luther).
% Explanation: Both played major roles in the early Reformation period.
concept(the_ninetyfive_theses).
related_to(the_ninetyfive_theses, the_ninetyfive_theses).
related_to(martin_luther, the_ninetyfive_theses).
related_to(wittenberg, the_ninetyfive_theses).
concept(holy_roman_empire).
related_to(holy_roman_empire, the_ninetyfive_theses).
concept(pope_leo_x).
related_to(pope_leo_x, the_ninetyfive_theses).
related_to(johann_tetzel, the_ninetyfive_theses).
related_to(indulgences, the_ninetyfive_theses).
related_to(the_protestant_reformation, the_ninetyfive_theses).
concept(printing_press).
related_to(printing_press, the_ninetyfive_theses).
related_to(frederick_the_wise, the_ninetyfive_theses).
concept(charles_v).
related_to(charles_v, the_ninetyfive_theses).
related_to(diet_of_worms, the_ninetyfive_theses).
related_to(excommunication_of_luther, the_ninetyfive_theses).
concept(all_saints_church_wittenberg_castle_church).
related_to(all_saints_church_wittenberg_castle_church, the_ninetyfive_theses).
concept(october_31_1517).
related_to(october_31_1517, the_ninetyfive_theses).
concept(x1517).
related_to(x1517, the_ninetyfive_theses).
concept(erasmus_of_rotterdam).
related_to(erasmus_of_rotterdam, the_ninetyfive_theses).
concept(sola_scriptura).
related_to(sola_scriptura, the_ninetyfive_theses).
concept(sola_fide).
related_to(sola_fide, the_ninetyfive_theses).
concept(catholic_church).
related_to(catholic_church, the_ninetyfive_theses).
concept(x95_theses_publication).
related_to(x95_theses_publication, the_ninetyfive_theses).
related_to(lutheranism, the_ninetyfive_theses).
authored_by(the_ninetyfive_theses, martin_luther).
% Explanation: Martin Luther wrote the Ninety-Five Theses.
posted_on(the_ninetyfive_theses, all_saints_church_wittenberg_castle_church).
% Explanation: Luther posted the Theses on the door of this church.
occurred_in(the_ninetyfive_theses, october_31_1517).
% Explanation: The Theses were published and posted on this date.
occurred_in(the_ninetyfive_theses, wittenberg).
% Explanation: The event occurred in the town of Wittenberg.
criticized(the_ninetyfive_theses, indulgences).
% Explanation: The Theses challenged the Church's sale of indulgences.
served_under(johann_tetzel, pope_leo_x).
% Explanation: Tetzel acted under papal authority.
ruled_during(pope_leo_x, x15131521).
% Explanation: Reigned as pope during the initial Reformation period.
preceded(the_ninetyfive_theses, the_protestant_reformation).
% Explanation: The Theses are often marked as the starting point of the Protestant Reformation.
occurred_in(the_protestant_reformation, x16th_century).
% Explanation: The Reformation spanned much of the 16th century.
spread_by(the_protestant_reformation, printing_press).
% Explanation: The printing press enabled rapid dissemination of Reformation ideas.
excommunicated_by(martin_luther, pope_leo_x).
% Explanation: Leo X formally excommunicated Luther in 1521.
ruled_during(charles_v, x15191556).
% Explanation: Emperor during the height of the Reformation.
presided_by(diet_of_worms, charles_v).
% Explanation: Charles V presided over the Diet.
translated_by(the_ninetyfive_theses, printing_press).
% Explanation: The Theses were quickly printed and disseminated.
located_in(wittenberg, holy_roman_empire).
% Explanation: Wittenberg was a city in the Holy Roman Empire in 1517.
elector_of(frederick_the_wise, saxony).
% Explanation: Frederick was the Elector of Saxony, which included Wittenberg.
formulated_by(sola_scriptura, martin_luther).
% Explanation: Luther advocated for Scripture as the sole source of authority.
formulated_by(sola_fide, martin_luther).
% Explanation: Luther asserted salvation by faith alone.
contemporary_of(the_ninetyfive_theses, erasmus_of_rotterdam).
% Explanation: Erasmus and Luther were contemporaries with parallel reform interests.
contemporary_of(martin_luther, charles_v).
% Explanation: Both key figures during early 16th century.
contemporary_of(martin_luther, pope_leo_x).
% Explanation: Luther and Leo X were contemporaneous during the Reformation era.
criticized_by(catholic_church, the_ninetyfive_theses).
% Explanation: Luther directly criticized Church practices in the Theses.
occurred_in(x95_theses_publication, x1517).
% Explanation: The publication and spread of the Theses occurred in 1517.
succeeded(the_ninetyfive_theses, indulgence_controversy).
% Explanation: The Theses followed earlier controversy over indulgences in the Church.
