% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: The Black Death
% Max depth: 1, Max related topics per node: 1

concept(the_black_death).
related_to(the_black_death, the_black_death).
concept(yersinia_pestis).
related_to(yersinia_pestis, the_black_death).
concept(bubonic_plague).
related_to(bubonic_plague, the_black_death).
concept(x14th_century).
related_to(x14th_century, the_black_death).
concept(x13471351).
related_to(x13471351, the_black_death).
concept(pandemic).
related_to(pandemic, the_black_death).
concept(europe).
related_to(europe, the_black_death).
concept(asia).
related_to(asia, the_black_death).
concept(north_africa).
related_to(north_africa, the_black_death).
concept(mortality).
related_to(mortality, the_black_death).
concept(peasants_revolt).
related_to(peasants_revolt, the_black_death).
concept(economic_impact).
related_to(economic_impact, the_black_death).
concept(social_impact).
related_to(social_impact, the_black_death).
concept(religious_impact).
related_to(religious_impact, the_black_death).
concept(flagellants).
related_to(flagellants, the_black_death).
concept(jewish_communities).
related_to(jewish_communities, the_black_death).
concept(quarantine).
related_to(quarantine, the_black_death).
concept(giovanni_boccaccio).
related_to(giovanni_boccaccio, the_black_death).
concept(edward_iii).
related_to(edward_iii, the_black_death).
concept(ibn_battuta).
related_to(ibn_battuta, the_black_death).
concept(x1347).
related_to(x1347, the_black_death).
concept(x1348).
related_to(x1348, the_black_death).
concept(x1349).
related_to(x1349, the_black_death).
concept(venice).
related_to(venice, the_black_death).
concept(constantinople).
related_to(constantinople, the_black_death).
concept(sicily).
related_to(sicily, the_black_death).
concept(england).
related_to(england, the_black_death).
concept(paris).
related_to(paris, the_black_death).
concept(mongol_empire).
related_to(mongol_empire, the_black_death).
concept(crimea).
related_to(crimea, the_black_death).
concept(kaffa).
related_to(kaffa, the_black_death).
concept(trade_routes).
related_to(trade_routes, the_black_death).
concept(silk_road).
related_to(silk_road, the_black_death).
concept(rats).
related_to(rats, the_black_death).
concept(fleas).
related_to(fleas, the_black_death).
concept(medical_response).
related_to(medical_response, the_black_death).
concept(mass_graves).
related_to(mass_graves, the_black_death).
concept(pogroms).
related_to(pogroms, the_black_death).
concept(decameron).
related_to(decameron, the_black_death).
caused_by(the_black_death, yersinia_pestis).
% Explanation: The Black Death was caused by the bacterium Yersinia pestis.
identified_as(the_black_death, bubonic_plague).
% Explanation: The Black Death is commonly identified as an outbreak of the bubonic plague.
occurred_in(the_black_death, x13471351).
% Explanation: The main wave of the Black Death occurred between 1347 and 1351.
occurred_during(the_black_death, x14th_century).
% Explanation: The Black Death took place in the 14th century.
occurred_in(the_black_death, europe).
% Explanation: The pandemic was most deadly in Europe.
occurred_in(the_black_death, asia).
% Explanation: The Black Death began in Asia before spreading to Europe.
occurred_in(the_black_death, north_africa).
% Explanation: The Black Death also affected parts of North Africa.
characterized_by(the_black_death, mortality).
% Explanation: The Black Death was marked by extremely high mortality rates.
triggered(the_black_death, peasants_revolt).
% Explanation: The aftermath contributed to social upheavals such as the Peasants' Revolt (1381) in England.
caused(the_black_death, economic_impact).
% Explanation: The pandemic led to significant economic disruption in affected regions.
caused(the_black_death, social_impact).
% Explanation: The Black Death triggered major social changes and unrest.
caused(the_black_death, religious_impact).
% Explanation: The pandemic deeply affected religious life and institutions.
emerged_during(flagellants, the_black_death).
% Explanation: The Flagellant movement rose in response to the Black Death.
persecuted_during(jewish_communities, the_black_death).
% Explanation: Jewish communities were scapegoated and persecuted during the pandemic.
led_to(the_black_death, quarantine).
% Explanation: The concept of quarantine originated as a response to the Black Death.
wrote_about(giovanni_boccaccio, the_black_death).
% Explanation: Boccaccio described the pandemic in his work, the Decameron.
wrote(giovanni_boccaccio, decameron).
% Explanation: The Decameron was written in response to the Black Death.
ruled_during(edward_iii, the_black_death).
% Explanation: Edward III was the monarch of England during the Black Death.
contemporary_of(ibn_battuta, giovanni_boccaccio).
% Explanation: Both lived during the period of the Black Death.
entered_via(the_black_death, sicily).
% Explanation: The Black Death entered Europe via Sicily in 1347.
spread_to(the_black_death, venice).
% Explanation: From Sicily, the Black Death spread to Venice.
spread_to(the_black_death, constantinople).
% Explanation: The plague reached Constantinople shortly after entering Europe.
spread_to(the_black_death, england).
% Explanation: The epidemic reached England by 1348.
spread_to(the_black_death, paris).
% Explanation: Paris was infected by the Black Death in 1348.
preceded(the_black_death, peasants_revolt).
% Explanation: The Black Death occurred before the Peasants' Revolt of 1381.
spread_via(the_black_death, trade_routes).
% Explanation: Trade routes were a primary method for the spread of the Black Death.
included(trade_routes, silk_road).
% Explanation: The Silk Road was a major trade route connecting Asia and Europe.
located_in(kaffa, crimea).
% Explanation: Kaffa (now Feodosiya) was a port in Crimea.
entered_via(the_black_death, kaffa).
% Explanation: The Black Death entered Europe through Kaffa.
carried(rats, fleas).
% Explanation: Rats were commonly hosts for fleas that transmitted Yersinia pestis.
transmitted(fleas, yersinia_pestis).
% Explanation: Fleas are the direct vectors that transmitted the bacterium.
preceded(mongol_empire, the_black_death).
% Explanation: The Mongol Empire's trade networks facilitated the spread of the disease before the outbreak in Europe.
associated_with(the_black_death, mass_graves).
% Explanation: Mass graves were dug for the enormous number of victims.
led_to(the_black_death, pogroms).
% Explanation: Anti-Jewish violence (pogroms) surged due to scapegoating during the pandemic.
prompted(the_black_death, medical_response).
% Explanation: The pandemic forced new forms of medical and public health response.
born_in(giovanni_boccaccio, x1313).
% Explanation: Boccaccio was born in 1313.
died_in(giovanni_boccaccio, x1375).
% Explanation: Boccaccio died in 1375.
born_in(edward_iii, x1312).
% Explanation: Edward III was born in 1312.
died_in(edward_iii, x1377).
% Explanation: Edward III died in 1377.
born_in(ibn_battuta, x1304).
% Explanation: Ibn Battuta was born in 1304.
died_in(ibn_battuta, x13689).
% Explanation: Ibn Battuta died in 1368 or 1369.
peaked_in(the_black_death, x1348).
% Explanation: The pandemic reached its peak in many European countries in 1348.
first_applied_in(quarantine, venice).
% Explanation: Venice was among the first cities to apply systematic quarantine in response to plague.
concept(origins_and_spread_of_the_black_death_in_europe).
concept(black_death).
related_to(black_death, origins_and_spread_of_the_black_death_in_europe).
related_to(yersinia_pestis, origins_and_spread_of_the_black_death_in_europe).
related_to(bubonic_plague, origins_and_spread_of_the_black_death_in_europe).
concept(third_pandemic).
related_to(third_pandemic, origins_and_spread_of_the_black_death_in_europe).
related_to(silk_road, origins_and_spread_of_the_black_death_in_europe).
related_to(mongol_empire, origins_and_spread_of_the_black_death_in_europe).
related_to(crimea, origins_and_spread_of_the_black_death_in_europe).
concept(genoese_traders).
related_to(genoese_traders, origins_and_spread_of_the_black_death_in_europe).
related_to(constantinople, origins_and_spread_of_the_black_death_in_europe).
concept(messina).
related_to(messina, origins_and_spread_of_the_black_death_in_europe).
related_to(sicily, origins_and_spread_of_the_black_death_in_europe).
concept(italy).
related_to(italy, origins_and_spread_of_the_black_death_in_europe).
concept(france).
related_to(france, origins_and_spread_of_the_black_death_in_europe).
related_to(england, origins_and_spread_of_the_black_death_in_europe).
concept(germany).
related_to(germany, origins_and_spread_of_the_black_death_in_europe).
concept(scandinavia).
related_to(scandinavia, origins_and_spread_of_the_black_death_in_europe).
concept(ibn_alwardi).
related_to(ibn_alwardi, origins_and_spread_of_the_black_death_in_europe).
concept(gabriele_de_mussi).
related_to(gabriele_de_mussi, origins_and_spread_of_the_black_death_in_europe).
concept(x1346).
related_to(x1346, origins_and_spread_of_the_black_death_in_europe).
related_to(x1347, origins_and_spread_of_the_black_death_in_europe).
related_to(x1348, origins_and_spread_of_the_black_death_in_europe).
related_to(x1349, origins_and_spread_of_the_black_death_in_europe).
concept(x1351).
related_to(x1351, origins_and_spread_of_the_black_death_in_europe).
concept(plague_reservoirs_rodents).
related_to(plague_reservoirs_rodents, origins_and_spread_of_the_black_death_in_europe).
concept(flea_vector_xenopsylla_cheopis).
related_to(flea_vector_xenopsylla_cheopis, origins_and_spread_of_the_black_death_in_europe).
related_to(trade_routes, origins_and_spread_of_the_black_death_in_europe).
concept(caffa).
related_to(caffa, origins_and_spread_of_the_black_death_in_europe).
concept(siege_of_caffa).
related_to(siege_of_caffa, origins_and_spread_of_the_black_death_in_europe).
concept(catapulting_of_plague_corpses).
related_to(catapulting_of_plague_corpses, origins_and_spread_of_the_black_death_in_europe).
concept(european_port_cities).
related_to(european_port_cities, origins_and_spread_of_the_black_death_in_europe).
concept(human_migration).
related_to(human_migration, origins_and_spread_of_the_black_death_in_europe).
related_to(social_impact, origins_and_spread_of_the_black_death_in_europe).
concept(population_decline).
related_to(population_decline, origins_and_spread_of_the_black_death_in_europe).
concept(medieval_europe).
related_to(medieval_europe, origins_and_spread_of_the_black_death_in_europe).
related_to(medical_response, origins_and_spread_of_the_black_death_in_europe).
related_to(flagellants, origins_and_spread_of_the_black_death_in_europe).
related_to(giovanni_boccaccio, origins_and_spread_of_the_black_death_in_europe).
concept(philip_vi_of_france).
related_to(philip_vi_of_france, origins_and_spread_of_the_black_death_in_europe).
concept(edward_iii_of_england).
related_to(edward_iii_of_england, origins_and_spread_of_the_black_death_in_europe).
caused_by(black_death, yersinia_pestis).
% Explanation: The Black Death was caused by the bacterium Yersinia pestis.
transmitted_by(yersinia_pestis, flea_vector_xenopsylla_cheopis).
% Explanation: The bacterium was primarily transmitted to humans through fleas carried by rodents.
affected_species(yersinia_pestis, plague_reservoirs_rodents).
% Explanation: Rodents served as reservoirs for Yersinia pestis.
manifestation_of(black_death, bubonic_plague).
% Explanation: The Black Death is the term used for a particularly devastating outbreak of Bubonic plague.
synonymous_with(black_death, great_plague).
% Explanation: The Black Death is sometimes called the Great Plague of the 14th century.
occurred_in(black_death, x13471351).
% Explanation: The main outbreak in Europe occurred between 1347-1351.
preceded(black_death, third_pandemic).
% Explanation: The Black Death was an earlier major plague pandemic preceding the Third Pandemic (19th-20th c.).
controlled(mongol_empire, silk_road).
% Explanation: The Mongol Empire provided stability for increased Silk Road trade.
enabled(silk_road, trade_routes).
% Explanation: The Silk Road was a major artery for trans-Eurasian trade.
route_of(trade_routes, black_death).
% Explanation: Trade routes facilitated the spread of the Black Death from Asia to Europe.
occurred_in(siege_of_caffa, x1346).
% Explanation: Siege of Caffa took place in 1346; it is thought to be an initial transmission point.
located_in(siege_of_caffa, caffa).
% Explanation: The siege was at the trading port of Caffa, Crimea.
engaged_in(mongol_empire, siege_of_caffa).
% Explanation: Mongol forces besieged the trading city of Caffa.
occurred_during(catapulting_of_plague_corpses, siege_of_caffa).
% Explanation: Historical sources claim Mongols catapulted plague-infected corpses into Caffa during the siege.
origin_of_spread_to(crimea, europe).
% Explanation: Crimea, specifically Caffa, was a jumping-off point for the plague into Europe.
fled_from(genoese_traders, caffa).
% Explanation: Genoese traders left infected Caffa, spreading the plague westward.
arrived_in(genoese_traders, messina).
% Explanation: Fleeing traders arrived in Messina, Sicily in 1347, beginning the European outbreak.
located_in(messina, sicily).
% Explanation: Messina is a port on the island of Sicily.
entered_europe_through(black_death, messina).
% Explanation: Messina was the first European port to experience the Black Death.
spread_to(black_death, italy).
% Explanation: From Messina, the Black Death quickly spread through the Italian peninsula.
spread_to(black_death, france).
% Explanation: The Black Death entered France from Italy.
spread_to(black_death, england).
% Explanation: The disease reached England in 1348.
spread_to(black_death, germany).
% Explanation: After France, the Black Death swept into the Germanic lands.
spread_to(black_death, scandinavia).
% Explanation: By 1350, the Black Death had reached as far as Scandinavia.
transmission_center_for(european_port_cities, black_death).
% Explanation: Port cities facilitated further spread through trade and shipping.
caused(black_death, population_decline).
% Explanation: The Black Death resulted in the death of 30-60% of Europe's population.
occurred_in(black_death, medieval_europe).
% Explanation: The pandemic took place during the Late Middle Ages.
contributed_to(human_migration, spread_of_black_death).
% Explanation: Movement of people helped expand the epidemic.
ineffective_against(medical_response, black_death).
% Explanation: Medieval medical responses did little to halt the pandemic.
became_prevalent_during(flagellants, black_death).
% Explanation: The religious flagellant movement grew as a response to the plague.
witnessed_event(giovanni_boccaccio, black_death).
% Explanation: Boccaccio wrote about the plague's effects in 'The Decameron'.
died_in(ibn_alwardi, x1349).
% Explanation: Ibn al-Wardi died during the plague.
chronicled(ibn_alwardi, black_death).
% Explanation: He authored early plague chronicles.
chronicled(gabriele_de_mussi, siege_of_caffa).
% Explanation: De' Mussi reported plague transmission via sieged corpses at Caffa.
ruled_during(edward_iii_of_england, x13481351).
% Explanation: Edward III reigned through England's main plague years.
contemporary_of(edward_iii_of_england, philip_vi_of_france).
% Explanation: Both monarchs ruled during the Black Death period.
ruled_during(philip_vi_of_france, black_death).
% Explanation: Philip VI was king of France during the plague.
