% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: Virginia Woolf
% Max depth: 1, Max related topics per node: 1

concept(virginia_woolf).
related_to(virginia_woolf, virginia_woolf).
concept(modernism).
related_to(modernism, virginia_woolf).
concept(bloomsbury_group).
related_to(bloomsbury_group, virginia_woolf).
concept(london).
related_to(london, virginia_woolf).
concept(sussex).
related_to(sussex, virginia_woolf).
concept(england).
related_to(england, virginia_woolf).
concept(late_19th_century).
related_to(late_19th_century, virginia_woolf).
concept(early_20th_century).
related_to(early_20th_century, virginia_woolf).
concept(mrs_dalloway).
related_to(mrs_dalloway, virginia_woolf).
concept(to_the_lighthouse).
related_to(to_the_lighthouse, virginia_woolf).
concept(orlando).
related_to(orlando, virginia_woolf).
concept(a_room_of_ones_own).
related_to(a_room_of_ones_own, virginia_woolf).
concept(the_waves).
related_to(the_waves, virginia_woolf).
concept(jacobs_room).
related_to(jacobs_room, virginia_woolf).
concept(feminism).
related_to(feminism, virginia_woolf).
concept(stream_of_consciousness).
related_to(stream_of_consciousness, virginia_woolf).
concept(leonard_woolf).
related_to(leonard_woolf, virginia_woolf).
concept(hogarth_press).
related_to(hogarth_press, virginia_woolf).
concept(vanessa_bell).
related_to(vanessa_bell, virginia_woolf).
concept(lytton_strachey).
related_to(lytton_strachey, virginia_woolf).
concept(e_m_forster).
related_to(e_m_forster, virginia_woolf).
concept(james_joyce).
related_to(james_joyce, virginia_woolf).
concept(samuel_beckett).
related_to(samuel_beckett, virginia_woolf).
concept(shakespeare).
related_to(shakespeare, virginia_woolf).
concept(psychological_realism).
related_to(psychological_realism, virginia_woolf).
concept(suicide).
related_to(suicide, virginia_woolf).
concept(mental_illness).
related_to(mental_illness, virginia_woolf).
concept(woolfs_diaries).
related_to(woolfs_diaries, virginia_woolf).
concept(adaptations).
related_to(adaptations, virginia_woolf).
concept(the_hours).
related_to(the_hours, virginia_woolf).
concept(nicole_kidman).
related_to(nicole_kidman, virginia_woolf).
concept(michael_cunningham).
related_to(michael_cunningham, virginia_woolf).
concept(literary_criticism).
related_to(literary_criticism, virginia_woolf).
concept(woolfian_narrative_technique).
related_to(woolfian_narrative_technique, virginia_woolf).
concept(womens_rights).
related_to(womens_rights, virginia_woolf).
concept(virginia_stephen).
related_to(virginia_stephen, virginia_woolf).
concept(virginia_and_leonard_woolfs_marriage).
related_to(virginia_and_leonard_woolfs_marriage, virginia_woolf).
concept(virginia_woolfs_legacy).
related_to(virginia_woolfs_legacy, virginia_woolf).
written_by(mrs_dalloway, virginia_woolf).
% Explanation: Virginia Woolf authored 'Mrs Dalloway'
written_by(to_the_lighthouse, virginia_woolf).
% Explanation: Virginia Woolf authored 'To the Lighthouse'
written_by(orlando, virginia_woolf).
% Explanation: Virginia Woolf authored 'Orlando'
written_by(a_room_of_ones_own, virginia_woolf).
% Explanation: Virginia Woolf wrote 'A Room of One's Own', a key feminist text
written_by(the_waves, virginia_woolf).
% Explanation: Virginia Woolf authored 'The Waves'
written_by(jacobs_room, virginia_woolf).
% Explanation: Virginia Woolf authored 'Jacob's Room'
published_in(mrs_dalloway, x1925).
% Explanation: 'Mrs Dalloway' was published in 1925
published_in(to_the_lighthouse, x1927).
% Explanation: 'To the Lighthouse' was published in 1927
published_in(orlando, x1928).
% Explanation: 'Orlando' was published in 1928
published_in(a_room_of_ones_own, x1929).
% Explanation: 'A Room of One's Own' was published in 1929
published_in(the_waves, x1931).
% Explanation: 'The Waves' was published in 1931
published_in(jacobs_room, x1922).
% Explanation: 'Jacob's Room' was published in 1922
set_in(mrs_dalloway, london).
% Explanation: The novel 'Mrs Dalloway' is set in post-World War I London
set_in(to_the_lighthouse, isle_of_skye).
% Explanation: 'To the Lighthouse' is set on the Isle of Skye in Scotland
set_in(orlando, england).
% Explanation: 'Orlando' takes place in England and across centuries
genre_of(a_room_of_ones_own, essay).
% Explanation: 'A Room of One's Own' is a long-form essay
genre_of(mrs_dalloway, modernist_novel).
% Explanation: 'Mrs Dalloway' is a modernist novel
genre_of(to_the_lighthouse, modernist_novel).
% Explanation: 'To the Lighthouse' is a modernist novel
genre_of(orlando, biographyfantasy).
% Explanation: 'Orlando' is a fictional biography/fantasy
movement(virginia_woolf, modernism).
% Explanation: Virginia Woolf is one of the major authors of the Modernist movement
member_of(virginia_woolf, bloomsbury_group).
% Explanation: Woolf was a central figure in the Bloomsbury Group
includes(bloomsbury_group, vanessa_bell).
% Explanation: Vanessa Bell, Woolf's sister, was part of the Bloomsbury Group
includes(bloomsbury_group, lytton_strachey).
% Explanation: Lytton Strachey was part of the Bloomsbury Group
includes(bloomsbury_group, virginia_woolf).
% Explanation: Virginia Woolf was a major member of the Bloomsbury Group
includes(bloomsbury_group, e_m_forster).
% Explanation: E. M. Forster was a member of the Bloomsbury Group
married_to(virginia_woolf, leonard_woolf).
% Explanation: Virginia Woolf married Leonard Woolf in 1912
co_founder_of(leonard_woolf, hogarth_press).
% Explanation: Leonard and Virginia Woolf together founded Hogarth Press
co_founder_of(virginia_woolf, hogarth_press).
% Explanation: Virginia and Leonard Woolf founded Hogarth Press, publishing major Modernist works
published_work(hogarth_press, mrs_dalloway).
% Explanation: 'Mrs Dalloway' was published by Hogarth Press
protagonist_of(mrs_dalloway, clarissa_dalloway).
% Explanation: Clarissa Dalloway is the protagonist of 'Mrs Dalloway'
protagonist_of(orlando, orlando).
% Explanation: The eponymous character Orlando is the protagonist of 'Orlando'
birth_name(virginia_woolf, virginia_stephen).
% Explanation: Virginia Woolf was born Virginia Stephen
born_in(virginia_woolf, london).
% Explanation: Virginia Woolf was born and lived much of her life in London
lived_in(virginia_woolf, sussex).
% Explanation: Virginia Woolf lived in Sussex later in her life
active_in_period(virginia_woolf, early_20th_century).
% Explanation: Woolf was active as a writer mainly in the early 20th century
addresses_theme(virginia_woolf, feminism).
% Explanation: Many of Woolf's essays and novels, especially 'A Room of One's Own', address feminist themes
addresses_theme(a_room_of_ones_own, womens_rights).
% Explanation: 'A Room of One's Own' is concerned with advocating women's independence in intellectual and financial terms
uses_technique(mrs_dalloway, stream_of_consciousness).
% Explanation: 'Mrs Dalloway' applies the stream of consciousness narrative technique
uses_technique(to_the_lighthouse, stream_of_consciousness).
% Explanation: 'To the Lighthouse' applies stream of consciousness
uses_technique(the_waves, stream_of_consciousness).
% Explanation: 'The Waves' is well known for its stream of consciousness technique
influenced_by(virginia_woolf, james_joyce).
% Explanation: James Joyce's experimentation influenced Virginia Woolf
influenced_by(virginia_woolf, shakespeare).
% Explanation: Shakespeare is cited as a major influence by Virginia Woolf
influenced(virginia_woolf, michael_cunningham).
% Explanation: Michael Cunningham, author of 'The Hours', was influenced by Woolf
influenced(virginia_woolf, samuel_beckett).
% Explanation: Woolf's modernist style influenced Samuel Beckett
inspired_by(the_hours, mrs_dalloway).
% Explanation: Michael Cunningham's novel 'The Hours' is explicitly inspired by 'Mrs Dalloway'
written_by(the_hours, michael_cunningham).
% Explanation: Michael Cunningham is the author of 'The Hours'
adapted_into(the_hours, the_hours_film).
% Explanation: 'The Hours' was adapted into a film in 2002
features_actor_as(the_hours_film, nicole_kidman_as_virginia_woolf).
% Explanation: Nicole Kidman portrayed Virginia Woolf in 'The Hours (film)'
subject_of(virginia_woolf, literary_criticism).
% Explanation: Woolf is the subject of extensive literary criticism and analysis
influences(virginia_woolfs_legacy, feminism).
% Explanation: Woolf's work continues to influence feminist theory and practice
written_by(woolfs_diaries, virginia_woolf).
% Explanation: Virginia Woolf wrote extensive diaries, which are important literary documents
died_in(virginia_woolf, x1941).
% Explanation: Woolf died by suicide in 1941
suffered_from(virginia_woolf, mental_illness).
% Explanation: Woolf suffered from mental illness throughout her life
concept(stream_of_consciousness_narrative).
related_to(stream_of_consciousness_narrative, stream_of_consciousness_narrative).
concept(interior_monologue).
related_to(interior_monologue, stream_of_consciousness_narrative).
concept(free_indirect_discourse).
related_to(free_indirect_discourse, stream_of_consciousness_narrative).
related_to(modernism, stream_of_consciousness_narrative).
related_to(psychological_realism, stream_of_consciousness_narrative).
related_to(james_joyce, stream_of_consciousness_narrative).
related_to(virginia_woolf, stream_of_consciousness_narrative).
concept(william_faulkner).
related_to(william_faulkner, stream_of_consciousness_narrative).
concept(marcel_proust).
related_to(marcel_proust, stream_of_consciousness_narrative).
concept(dorothy_richardson).
related_to(dorothy_richardson, stream_of_consciousness_narrative).
concept(ulysses).
related_to(ulysses, stream_of_consciousness_narrative).
related_to(mrs_dalloway, stream_of_consciousness_narrative).
related_to(to_the_lighthouse, stream_of_consciousness_narrative).
concept(the_sound_and_the_fury).
related_to(the_sound_and_the_fury, stream_of_consciousness_narrative).
concept(in_search_of_lost_time).
related_to(in_search_of_lost_time, stream_of_consciousness_narrative).
concept(pilgrimage).
related_to(pilgrimage, stream_of_consciousness_narrative).
related_to(early_20th_century, stream_of_consciousness_narrative).
concept(europe).
related_to(europe, stream_of_consciousness_narrative).
concept(united_states).
related_to(united_states, stream_of_consciousness_narrative).
concept(narrative_technique).
related_to(narrative_technique, stream_of_consciousness_narrative).
concept(literary_style).
related_to(literary_style, stream_of_consciousness_narrative).
concept(firstperson_narrative).
related_to(firstperson_narrative, stream_of_consciousness_narrative).
concept(consciousness).
related_to(consciousness, stream_of_consciousness_narrative).
concept(subjectivity).
related_to(subjectivity, stream_of_consciousness_narrative).
concept(experimental_novel).
related_to(experimental_novel, stream_of_consciousness_narrative).
concept(postmodernism).
related_to(postmodernism, stream_of_consciousness_narrative).
related_to(samuel_beckett, stream_of_consciousness_narrative).
concept(influence_in_film_eg_alain_resnais).
related_to(influence_in_film_eg_alain_resnais, stream_of_consciousness_narrative).
concept(influence_in_contemporary_literature).
related_to(influence_in_contemporary_literature, stream_of_consciousness_narrative).
concept(modernist_movement).
related_to(modernist_movement, stream_of_consciousness_narrative).
concept(streams_of_consciousness_in_psychology).
related_to(streams_of_consciousness_in_psychology, stream_of_consciousness_narrative).
is_a(stream_of_consciousness_narrative, narrative_technique).
% Explanation: Stream of consciousness is a specific kind of narrative technique.
associated_with(stream_of_consciousness_narrative, interior_monologue).
% Explanation: One narrative strategy used in stream of consciousness writing.
associated_with(stream_of_consciousness_narrative, free_indirect_discourse).
% Explanation: Another technique closely related to stream of consciousness.
part_of(stream_of_consciousness_narrative, modernism).
% Explanation: Stream of consciousness narrative was a hallmark of literary modernism.
influenced_by(stream_of_consciousness_narrative, streams_of_consciousness_in_psychology).
% Explanation: The literary technique was influenced by psychological theories, especially William James's.
movement_of(modernism, james_joyce).
% Explanation: Joyce is one of the main figures of literary modernism.
movement_of(modernism, virginia_woolf).
% Explanation: Woolf is a key modernist writer who used stream of consciousness.
movement_of(modernism, william_faulkner).
% Explanation: Faulkner adapted stream of consciousness to American modernism.
movement_of(modernism, marcel_proust).
% Explanation: Proust was an early adopter of introspective narrative techniques.
movement_of(modernism, dorothy_richardson).
% Explanation: Richardson was a pioneer of stream of consciousness in English literature.
written_by(ulysses, james_joyce).
% Explanation: Joyce authored Ulysses, a landmark stream of consciousness text.
published_in(ulysses, x1922).
% Explanation: Ulysses was published in 1922.
genre_of(ulysses, experimental_novel).
% Explanation: Ulysses is an experimental novel using stream of consciousness extensively.
part_of(ulysses, modernism).
% Explanation: Ulysses is a key modernist work.
set_in(mrs_dalloway, london1923).
% Explanation: Mrs Dalloway is set in London post-WWI.
written_by(the_sound_and_the_fury, william_faulkner).
% Explanation: The Sound and the Fury is an American modernist stream of consciousness novel.
published_in(the_sound_and_the_fury, x1929).
% Explanation: The Sound and the Fury was published in 1929.
set_in(the_sound_and_the_fury, mississippisouth_early_20th_century).
% Explanation: The novel is set in the American South.
written_by(in_search_of_lost_time, marcel_proust).
% Explanation: Proust's magnum opus uses introspective, stream-of-consciousness techniques.
published_in(in_search_of_lost_time, x19131927).
% Explanation: Published in seven volumes over this period.
written_by(pilgrimage, dorothy_richardson).
% Explanation: Pilgrimage is an experimental novel cycle employing stream of consciousness.
published_in(pilgrimage, x19151967).
% Explanation: Richardson's series was published across decades.
influenced_by(james_joyce, marcel_proust).
% Explanation: While not directly documented, Joyce and Proust are seen as contemporaries who influenced the development of stream of consciousness.
influenced_by(william_faulkner, james_joyce).
% Explanation: Faulkner built on Joyce's innovations, applying them to Southern American contexts.
prevalent_in(stream_of_consciousness_narrative, early_20th_century).
% Explanation: Became prominent in the early 1900s.
prevalent_in(stream_of_consciousness_narrative, europe).
% Explanation: Developed in Europe (Britain, Ireland, France).
prevalent_in(stream_of_consciousness_narrative, united_states).
% Explanation: Developed in parallel in the US.
characterized_by(stream_of_consciousness_narrative, subjectivity).
% Explanation: Focuses on individual's subjective thoughts.
characterized_by(stream_of_consciousness_narrative, firstperson_narrative).
% Explanation: Often employs first-person or very close third-person perspectives.
characterized_by(stream_of_consciousness_narrative, psychological_realism).
% Explanation: Aims to depict mental and emotional realities.
influenced(stream_of_consciousness_narrative, postmodernism).
% Explanation: Its techniques influenced later postmodern writers.
influenced(stream_of_consciousness_narrative, samuel_beckett).
% Explanation: Beckett continued and transformed stream of consciousness in his works.
influenced(stream_of_consciousness_narrative, influence_in_film_eg_alain_resnais).
% Explanation: Stream of consciousness influenced experimental cinema.
influenced(stream_of_consciousness_narrative, influence_in_contemporary_literature).
% Explanation: It continues to impact modern literary styles.
adapted_into(mrs_dalloway, the_hours_2002_film).
% Explanation: The film adapts and is inspired by Woolf's Mrs Dalloway.
