% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: World War II
% Max depth: 1, Max related topics per node: 1

concept(world_war_ii).
related_to(world_war_ii, world_war_ii).
concept(allies).
related_to(allies, world_war_ii).
concept(axis_powers).
related_to(axis_powers, world_war_ii).
concept(united_states).
related_to(united_states, world_war_ii).
concept(united_kingdom).
related_to(united_kingdom, world_war_ii).
concept(soviet_union).
related_to(soviet_union, world_war_ii).
concept(france).
related_to(france, world_war_ii).
concept(germany).
related_to(germany, world_war_ii).
concept(italy).
related_to(italy, world_war_ii).
concept(japan).
related_to(japan, world_war_ii).
concept(adolf_hitler).
related_to(adolf_hitler, world_war_ii).
concept(joseph_stalin).
related_to(joseph_stalin, world_war_ii).
concept(winston_churchill).
related_to(winston_churchill, world_war_ii).
concept(franklin_d_roosevelt).
related_to(franklin_d_roosevelt, world_war_ii).
concept(benito_mussolini).
related_to(benito_mussolini, world_war_ii).
concept(pearl_harbor_attack).
related_to(pearl_harbor_attack, world_war_ii).
concept(dday).
related_to(dday, world_war_ii).
concept(battle_of_stalingrad).
related_to(battle_of_stalingrad, world_war_ii).
concept(holocaust).
related_to(holocaust, world_war_ii).
concept(blitzkrieg).
related_to(blitzkrieg, world_war_ii).
concept(manhattan_project).
related_to(manhattan_project, world_war_ii).
concept(hiroshima).
related_to(hiroshima, world_war_ii).
concept(nagasaki).
related_to(nagasaki, world_war_ii).
concept(united_nations).
related_to(united_nations, world_war_ii).
concept(treaty_of_versailles).
related_to(treaty_of_versailles, world_war_ii).
concept(league_of_nations).
related_to(league_of_nations, world_war_ii).
concept(operation_barbarossa).
related_to(operation_barbarossa, world_war_ii).
concept(ve_day).
related_to(ve_day, world_war_ii).
concept(vj_day).
related_to(vj_day, world_war_ii).
concept(yalta_conference).
related_to(yalta_conference, world_war_ii).
concept(potsdam_conference).
related_to(potsdam_conference, world_war_ii).
concept(munich_agreement).
related_to(munich_agreement, world_war_ii).
concept(sudetenland).
related_to(sudetenland, world_war_ii).
concept(poland).
related_to(poland, world_war_ii).
concept(pacific_theater).
related_to(pacific_theater, world_war_ii).
concept(european_theater).
related_to(european_theater, world_war_ii).
concept(holocaust_victims).
related_to(holocaust_victims, world_war_ii).
concept(chiang_kaishek).
related_to(chiang_kaishek, world_war_ii).
concept(charles_de_gaulle).
related_to(charles_de_gaulle, world_war_ii).
concept(anne_frank).
related_to(anne_frank, world_war_ii).
concept(holocaust_survivors).
related_to(holocaust_survivors, world_war_ii).
occurred_in(world_war_ii, x19391945).
% Explanation: World War II was fought from 1939 to 1945.
preceded(world_war_ii, cold_war).
% Explanation: The end of World War II led directly to the start of the Cold War.
preceded(world_war_ii, united_nations).
% Explanation: The United Nations was established after World War II.
involved(world_war_ii, allies).
% Explanation: The Allies were one of the two major military alliances in World War II.
involved(world_war_ii, axis_powers).
% Explanation: The Axis Powers opposed the Allies in World War II.
includes(allies, united_states).
% Explanation: The United States was a key member of the Allies.
includes(allies, united_kingdom).
% Explanation: The United Kingdom was a key member of the Allies.
includes(allies, soviet_union).
% Explanation: The Soviet Union was a key member of the Allies.
includes(allies, france).
% Explanation: France was a founding member of the Allies.
includes(axis_powers, germany).
% Explanation: Germany was the principal Axis power.
includes(axis_powers, italy).
% Explanation: Italy was one of the main Axis powers.
includes(axis_powers, japan).
% Explanation: Japan was a major Axis power.
ruled_during(adolf_hitler, germany_19331945).
% Explanation: Hitler was the leader of Germany during the Nazi era and World War II.
ruled_during(joseph_stalin, soviet_union_19241953).
% Explanation: Stalin was the leader of the Soviet Union during the war.
ruled_during(winston_churchill, united_kingdom_19401945).
% Explanation: Churchill was Prime Minister during most of World War II.
ruled_during(franklin_d_roosevelt, united_states_19331945).
% Explanation: FDR was President of the United States for most of World War II.
ruled_during(benito_mussolini, italy_19221943).
% Explanation: Mussolini led Italy during its involvement in World War II.
occurred_in(pearl_harbor_attack, x19411207).
% Explanation: Japan attacked Pearl Harbor on December 7, 1941.
located_in(pearl_harbor_attack, hawaii).
% Explanation: The attack took place at Pearl Harbor, Hawaii.
preceded(pearl_harbor_attack, us_entry_into_world_war_ii).
% Explanation: The attack led to the United States declaring war on Japan.
occurred_in(dday, x19440606).
% Explanation: D-Day, the Allied landing in Normandy, happened on June 6, 1944.
located_in(dday, normandy_france).
% Explanation: The Normandy landings took place on the coast of France.
occurred_in(battle_of_stalingrad, x19421943).
% Explanation: The Battle of Stalingrad was a turning point on the Eastern Front.
located_in(battle_of_stalingrad, stalingrad_soviet_union).
% Explanation: This battle was fought in Stalingrad (now Volgograd), USSR.
occurred_in(holocaust, x19411945).
% Explanation: The Holocaust took place during World War II.
targeted(holocaust, holocaust_victims).
% Explanation: Millions, including Jews and minorities, were targeted by the Nazi regime.
organized_by(holocaust, nazi_germany).
% Explanation: The Holocaust was perpetrated by the Nazi regime.
initiated_by(manhattan_project, united_states).
% Explanation: The Manhattan Project was a US-led nuclear weapon development project.
produced(manhattan_project, atomic_bomb).
% Explanation: Project developed the first atomic bombs.
detonated_in(atomic_bomb, hiroshima).
% Explanation: The first atomic bomb was used at Hiroshima.
detonated_in(atomic_bomb, nagasaki).
% Explanation: A second atomic bomb was dropped on Nagasaki.
occurred_in(hiroshima, x19450806).
% Explanation: Hiroshima bombing happened on August 6, 1945.
occurred_in(nagasaki, x19450809).
% Explanation: Nagasaki bombing happened on August 9, 1945.
occurred_in(ve_day, x19450508).
% Explanation: VE Day marks victory in Europe on May 8, 1945.
occurred_in(vj_day, x19450815).
% Explanation: VJ Day marks victory over Japan on August 15, 1945.
preceded(treaty_of_versailles, world_war_ii).
% Explanation: The Treaty of Versailles ended WWI and contributed to causes of WWII.
preceded(league_of_nations, united_nations).
% Explanation: The League failed after WWII and was replaced by the United Nations.
occurred_in(munich_agreement, x1938).
% Explanation: The Munich Agreement was signed in 1938.
resulted_in(munich_agreement, annexation_of_sudetenland).
% Explanation: Allowed Nazi Germany to annex Sudetenland.
occurred_in(operation_barbarossa, x19410622).
% Explanation: Germany invaded the Soviet Union on June 22, 1941.
launched_by(operation_barbarossa, germany).
% Explanation: Operation Barbarossa was Germany's code name for attack on USSR.
occurred_in(yalta_conference, x194502).
% Explanation: The Yalta Conference took place in February 1945.
attended_by(yalta_conference, churchill_roosevelt_stalin).
% Explanation: The main Allied leaders attended Yalta.
occurred_in(potsdam_conference, x194507).
% Explanation: The Potsdam Conference was held in July 1945.
attended_by(potsdam_conference, truman_churchillattlee_stalin).
% Explanation: Potsdam was attended by the new US president, and Churchill/Attlee, and Stalin.
occurred_in(european_theater, europe).
% Explanation: European Theater was main area of conflict in Europe.
occurred_in(pacific_theater, asia_and_pacific_islands).
% Explanation: Pacific Theater refers to conflict in the Asia-Pacific region.
invaded_on(poland, x19390901).
% Explanation: Germany invaded Poland on September 1, 1939, starting WWII.
started_by(world_war_ii, invasion_of_poland).
% Explanation: World War II began with Germany's invasion of Poland.
born_in(adolf_hitler, x1889).
% Explanation: Adolf Hitler was born in 1889.
died_in(adolf_hitler, x1945).
% Explanation: Adolf Hitler died in 1945.
born_in(joseph_stalin, x1878).
% Explanation: Joseph Stalin was born in 1878.
died_in(joseph_stalin, x1953).
% Explanation: Joseph Stalin died in 1953.
born_in(winston_churchill, x1874).
% Explanation: Churchill was born in 1874.
died_in(winston_churchill, x1965).
% Explanation: Churchill died in 1965.
born_in(franklin_d_roosevelt, x1882).
% Explanation: FDR was born in 1882.
died_in(franklin_d_roosevelt, x1945).
% Explanation: FDR died in office in 1945.
born_in(benito_mussolini, x1883).
% Explanation: Mussolini was born in 1883.
died_in(benito_mussolini, x1945).
% Explanation: Mussolini was executed in 1945.
ruled_during(chiang_kaishek, china_19281949).
% Explanation: Chiang Kai-shek was leader of China during WWII.
ruled_during(charles_de_gaulle, free_france_19401944).
% Explanation: Charles de Gaulle led Free French Forces.
born_in(anne_frank, x1929).
% Explanation: Anne Frank was born in 1929.
died_in(anne_frank, x1945).
% Explanation: Anne Frank died in a concentration camp in 1945.
is_a(anne_frank, holocaust_victim).
% Explanation: Anne Frank was a victim of the Holocaust.
survived(holocaust_survivors, holocaust).
% Explanation: Holocaust survivors are those who lived through the Holocaust.
contemporary_of(adolf_hitler, joseph_stalin).
% Explanation: Both ruled major WWII powers at the same time.
contemporary_of(winston_churchill, franklin_d_roosevelt).
% Explanation: Both led Allied powers and worked closely during WWII.
contemporary_of(adolf_hitler, winston_churchill).
% Explanation: Both were leaders during the same historical period.
concept(the_holocaust).
related_to(the_holocaust, the_holocaust).
concept(shoah).
related_to(shoah, the_holocaust).
concept(final_solution).
related_to(final_solution, the_holocaust).
concept(nazi_germany).
related_to(nazi_germany, the_holocaust).
related_to(adolf_hitler, the_holocaust).
concept(heinrich_himmler).
related_to(heinrich_himmler, the_holocaust).
concept(reinhard_heydrich).
related_to(reinhard_heydrich, the_holocaust).
concept(adolf_eichmann).
related_to(adolf_eichmann, the_holocaust).
related_to(world_war_ii, the_holocaust).
concept(genocide).
related_to(genocide, the_holocaust).
concept(jews).
related_to(jews, the_holocaust).
concept(roma_gypsies).
related_to(roma_gypsies, the_holocaust).
concept(sinti).
related_to(sinti, the_holocaust).
concept(disabled_persons).
related_to(disabled_persons, the_holocaust).
concept(polish_intelligentsia).
related_to(polish_intelligentsia, the_holocaust).
concept(lgbtq_individuals).
related_to(lgbtq_individuals, the_holocaust).
concept(jehovahs_witnesses).
related_to(jehovahs_witnesses, the_holocaust).
concept(concentration_camps).
related_to(concentration_camps, the_holocaust).
concept(extermination_camps).
related_to(extermination_camps, the_holocaust).
concept(auschwitzbirkenau).
related_to(auschwitzbirkenau, the_holocaust).
concept(treblinka).
related_to(treblinka, the_holocaust).
concept(sobibor).
related_to(sobibor, the_holocaust).
concept(belzec).
related_to(belzec, the_holocaust).
concept(chelmno).
related_to(chelmno, the_holocaust).
concept(majdanek).
related_to(majdanek, the_holocaust).
concept(buchenwald).
related_to(buchenwald, the_holocaust).
concept(dachau).
related_to(dachau, the_holocaust).
concept(ghettos).
related_to(ghettos, the_holocaust).
concept(warsaw_ghetto).
related_to(warsaw_ghetto, the_holocaust).
concept(ghetto_uprisings).
related_to(ghetto_uprisings, the_holocaust).
concept(warsaw_ghetto_uprising).
related_to(warsaw_ghetto_uprising, the_holocaust).
concept(nuremberg_laws).
related_to(nuremberg_laws, the_holocaust).
concept(kristallnacht).
related_to(kristallnacht, the_holocaust).
concept(wannsee_conference).
related_to(wannsee_conference, the_holocaust).
concept(liberation_of_camps).
related_to(liberation_of_camps, the_holocaust).
related_to(allies, the_holocaust).
concept(soviet_army).
related_to(soviet_army, the_holocaust).
concept(nuremberg_trials).
related_to(nuremberg_trials, the_holocaust).
concept(einsatzgruppen).
related_to(einsatzgruppen, the_holocaust).
concept(judenrat).
related_to(judenrat, the_holocaust).
concept(zyklon_b).
related_to(zyklon_b, the_holocaust).
concept(gas_chambers).
related_to(gas_chambers, the_holocaust).
concept(ss_schutzstaffel).
related_to(ss_schutzstaffel, the_holocaust).
concept(gestapo).
related_to(gestapo, the_holocaust).
related_to(holocaust_survivors, the_holocaust).
related_to(anne_frank, the_holocaust).
concept(oskar_schindler).
related_to(oskar_schindler, the_holocaust).
concept(raoul_wallenberg).
related_to(raoul_wallenberg, the_holocaust).
concept(elie_wiesel).
related_to(elie_wiesel, the_holocaust).
concept(united_states_holocaust_memorial_museum).
related_to(united_states_holocaust_memorial_museum, the_holocaust).
concept(yad_vashem).
related_to(yad_vashem, the_holocaust).
concept(israel).
related_to(israel, the_holocaust).
related_to(germany, the_holocaust).
related_to(poland, the_holocaust).
concept(eastern_europe).
related_to(eastern_europe, the_holocaust).
concept(occupied_territories).
related_to(occupied_territories, the_holocaust).
concept(righteous_among_the_nations).
related_to(righteous_among_the_nations, the_holocaust).
synonym_of(the_holocaust, shoah).
% Explanation: Shoah is the Hebrew term for The Holocaust
occurred_in(the_holocaust, x19331945).
% Explanation: The Holocaust took place from 1933, when Hitler rose to power, to 1945, the end of WWII
occurred_within(the_holocaust, world_war_ii).
% Explanation: The Holocaust happened during World War II
included(the_holocaust, final_solution).
% Explanation: The Final Solution was the Nazi plan for the extermination of Jews, a central part of the Holocaust
decided_at(final_solution, wannsee_conference).
% Explanation: The details of the Final Solution were determined at the Wannsee Conference
occurred_in(wannsee_conference, x1942).
% Explanation: The Wannsee Conference took place in January 1942
targeted(the_holocaust, jews).
% Explanation: Jews were the principal targets of the Holocaust
targeted(the_holocaust, roma_gypsies).
% Explanation: Roma were targets of Nazi genocide
targeted(the_holocaust, disabled_persons).
% Explanation: The disabled were victims of Nazi persecution and euthanasia programs
targeted(the_holocaust, polish_intelligentsia).
% Explanation: Nazi occupiers targeted Polish elites for murder
targeted(the_holocaust, lgbtq_individuals).
% Explanation: LGBTQ people were persecuted under the Nazi regime
targeted(the_holocaust, jehovahs_witnesses).
% Explanation: Jehovah's Witnesses were persecuted for their beliefs
led_by(nazi_germany, adolf_hitler).
% Explanation: Adolf Hitler was the German leader during the Holocaust
head_of(heinrich_himmler, ss_schutzstaffel).
% Explanation: Heinrich Himmler led the SS, responsible for many crimes during the Holocaust
chaired(reinhard_heydrich, wannsee_conference).
% Explanation: Heydrich chaired the Wannsee Conference
implemented(adolf_eichmann, final_solution).
% Explanation: Eichmann organized the logistics of mass deportations
included(concentration_camps, auschwitzbirkenau).
% Explanation: Auschwitz-Birkenau was one of many Nazi concentration camps
included(extermination_camps, treblinka).
% Explanation: Treblinka was a Nazi extermination camp
located_in(extermination_camps, poland).
% Explanation: Most extermination camps were located in occupied Poland
located_in(auschwitzbirkenau, poland).
% Explanation: Auschwitz-Birkenau was situated in Nazi-occupied Poland
enacted_in(nuremberg_laws, x1935).
% Explanation: The Nuremberg Laws, restricting Jewish rights, were passed in 1935
enforced_by(nuremberg_laws, nazi_germany).
% Explanation: The Nuremberg Laws were Nazi legislation
occurred_in(kristallnacht, x1938).
% Explanation: Kristallnacht, a violent pogrom against Jews, happened in November 1938
preceded(kristallnacht, the_holocaust).
% Explanation: Kristallnacht marked an escalation toward the Holocaust
used_for(concentration_camps, genocide).
% Explanation: Concentration camps were tools of genocide in the Holocaust
used_in(gas_chambers, extermination_camps).
% Explanation: Gas chambers were a method of mass execution in extermination camps
used_in(zyklon_b, gas_chambers).
% Explanation: Zyklon B was the chemical used for mass killings
liberated_by(auschwitzbirkenau, soviet_army).
% Explanation: The Soviet Army liberated Auschwitz-Birkenau in 1945
occurred_in(liberation_of_camps, x19441945).
% Explanation: Camps were liberated by Allies towards the end of WWII
occurred_in(nuremberg_trials, x19451946).
% Explanation: Major Nazi criminals were prosecuted after WWII
conducted(einsatzgruppen, mass_shootings).
% Explanation: Einsatzgruppen executed mass shootings of Jews and others
located_in(warsaw_ghetto, warsaw).
% Explanation: The Warsaw Ghetto was in the city of Warsaw, Poland
occurred_in(warsaw_ghetto_uprising, x1943).
% Explanation: The uprising happened in April-May 1943
occurred_in(warsaw_ghetto_uprising, warsaw_ghetto).
% Explanation: The uprising took place inside the Warsaw Ghetto
operated_in(judenrat, ghettos).
% Explanation: Jewish councils administered daily life in the ghettos under Nazi direction
saved(oskar_schindler, jews).
% Explanation: Schindler saved about 1,200 Jews by employing them in his factory
recognized_as(oskar_schindler, righteous_among_the_nations).
% Explanation: Oskar Schindler was recognized by Israel as 'Righteous Among the Nations'
rescued(raoul_wallenberg, jews).
% Explanation: Wallenberg saved thousands of Jews in Hungary
recognized_as(raoul_wallenberg, righteous_among_the_nations).
% Explanation: Raoul Wallenberg is honored as 'Righteous Among the Nations'
survivor_of(elie_wiesel, the_holocaust).
% Explanation: Elie Wiesel was a survivor and writer about the Holocaust
born_in(elie_wiesel, x1928).
% Explanation: Elie Wiesel was born in 1928
located_in(united_states_holocaust_memorial_museum, usa).
% Explanation: This major museum on the Holocaust is in Washington, D.C., USA
located_in(yad_vashem, israel).
% Explanation: Yad Vashem is Israel's Holocaust memorial
recognized_as(yad_vashem, righteous_among_the_nations).
% Explanation: Yad Vashem confers the title 'Righteous Among the Nations'
occupied(nazi_germany, poland).
% Explanation: Nazi Germany occupied Poland beginning in 1939
located_in(poland, eastern_europe).
% Explanation: Poland is a country in Eastern Europe where much of the Holocaust took place
contemporary_of(anne_frank, elie_wiesel).
% Explanation: Both experienced the Holocaust as teenagers
ruled_during(nazi_germany, x19331945).
% Explanation: Nazi Germany ruled under Hitler from 1933 to 1945
succeeded(nuremberg_trials, the_holocaust).
% Explanation: The Nuremberg Trials were held after the end of the Holocaust
occurred_in(ghetto_uprisings, x19431944).
% Explanation: Various uprisings by Jews in ghettos happened from 1943 to 1944
