% Knowledge Base generated by AdvancedGPTToProlog
% Discontiguous directives to allow predicates to be defined non-consecutively
:- discontiguous concept/1.
:- discontiguous related_to/2.
:- discontiguous causes/2.
:- discontiguous implies/2.
:- discontiguous relates_to/2.
:- discontiguous part_of/2.
:- discontiguous has/2.
:- discontiguous member_of/2.
:- discontiguous influenced_by/2.
:- discontiguous influenced/2.
:- discontiguous contributed_to/2.
:- discontiguous developed/2.
:- discontiguous example_of/2.
:- discontiguous created_by/2.
:- discontiguous born_in/2.
:- discontiguous died_in/2.
:- discontiguous occurred_in/2.
:- discontiguous during/2.
:- discontiguous before/2.
:- discontiguous after/2.
:- discontiguous began_in/2.
:- discontiguous ended_in/2.
:- discontiguous lasted_from/3.
:- discontiguous contemporary_of/2.
:- discontiguous preceded/2.
:- discontiguous succeeded/2.
:- discontiguous published_in/2.
:- discontiguous created_in/2.
:- discontiguous located_in/2.
:- discontiguous originated_in/2.
:- discontiguous moved_to/2.
:- discontiguous near/2.
:- discontiguous capital_of/2.
:- discontiguous region_of/2.
:- discontiguous housed_in/2.
:- discontiguous founded_by/2.
:- discontiguous written_by/2.
:- discontiguous discovered_by/2.
:- discontiguous invented_by/2.
:- discontiguous ruled_by/2.
:- discontiguous developed_by/2.
:- discontiguous friend_of/2.
:- discontiguous enemy_of/2.
:- discontiguous teacher_of/2.
:- discontiguous student_of/2.
:- discontiguous married_to/2.
:- discontiguous parent_of/2.
:- discontiguous child_of/2.
:- discontiguous successor_of/2.
:- discontiguous predecessor_of/2.
:- discontiguous colleague_of/2.
:- discontiguous rival_of/2.
:- discontiguous inspired/2.
:- discontiguous criticized/2.
:- discontiguous translated_by/2.
:- discontiguous school_of_thought/2.
:- discontiguous main_work/2.
:- discontiguous protagonist_of/2.
:- discontiguous genre_of/2.
:- discontiguous movement/2.
:- discontiguous adapted_into/2.
:- discontiguous technique_used/2.
:- discontiguous commissioned_by/2.
:- discontiguous trained_under/2.
:- discontiguous response_to/2.
:- discontiguous argued_against/2.
:- discontiguous expanded_on/2.
:- discontiguous similar_to/2.
:- discontiguous different_from/2.
:- discontiguous influenced_work/2.
:- discontiguous reaction_to/2.
:- discontiguous set_in/2.
:- discontiguous represents/2.
:- discontiguous symbolizes/2.

% Knowledge network for main topic: World War I
% Max depth: 1, Max related topics per node: 1

concept(world_war_i).
related_to(world_war_i, world_war_i).
concept(triple_entente).
related_to(triple_entente, world_war_i).
concept(central_powers).
related_to(central_powers, world_war_i).
concept(assassination_of_archduke_franz_ferdinand).
related_to(assassination_of_archduke_franz_ferdinand, world_war_i).
concept(treaty_of_versailles).
related_to(treaty_of_versailles, world_war_i).
concept(western_front).
related_to(western_front, world_war_i).
concept(eastern_front).
related_to(eastern_front, world_war_i).
concept(gallipoli_campaign).
related_to(gallipoli_campaign, world_war_i).
concept(battle_of_the_somme).
related_to(battle_of_the_somme, world_war_i).
concept(battle_of_verdun).
related_to(battle_of_verdun, world_war_i).
concept(russian_revolution).
related_to(russian_revolution, world_war_i).
concept(fourteen_points).
related_to(fourteen_points, world_war_i).
concept(league_of_nations).
related_to(league_of_nations, world_war_i).
concept(united_kingdom).
related_to(united_kingdom, world_war_i).
concept(france).
related_to(france, world_war_i).
concept(russia).
related_to(russia, world_war_i).
concept(germany).
related_to(germany, world_war_i).
concept(austriahungary).
related_to(austriahungary, world_war_i).
concept(ottoman_empire).
related_to(ottoman_empire, world_war_i).
concept(united_states).
related_to(united_states, world_war_i).
concept(italy).
related_to(italy, world_war_i).
concept(belgium).
related_to(belgium, world_war_i).
concept(serbia).
related_to(serbia, world_war_i).
concept(woodrow_wilson).
related_to(woodrow_wilson, world_war_i).
concept(kaiser_wilhelm_ii).
related_to(kaiser_wilhelm_ii, world_war_i).
concept(david_lloyd_george).
related_to(david_lloyd_george, world_war_i).
concept(georges_clemenceau).
related_to(georges_clemenceau, world_war_i).
concept(vladimir_lenin).
related_to(vladimir_lenin, world_war_i).
concept(tsar_nicholas_ii).
related_to(tsar_nicholas_ii, world_war_i).
concept(gavrilo_princip).
related_to(gavrilo_princip, world_war_i).
concept(archduke_franz_ferdinand).
related_to(archduke_franz_ferdinand, world_war_i).
concept(armistice_of_11_november_1918).
related_to(armistice_of_11_november_1918, world_war_i).
concept(no_mans_land).
related_to(no_mans_land, world_war_i).
concept(trench_warfare).
related_to(trench_warfare, world_war_i).
concept(war_guilt_clause).
related_to(war_guilt_clause, world_war_i).
concept(weimar_republic).
related_to(weimar_republic, world_war_i).
concept(mustard_gas).
related_to(mustard_gas, world_war_i).
concept(zimmermann_telegram).
related_to(zimmermann_telegram, world_war_i).
occurred_in(world_war_i, x19141918).
% Explanation: World War I took place from July 28, 1914 to November 11, 1918.
occurred_in(assassination_of_archduke_franz_ferdinand, x1914).
% Explanation: The assassination occurred in Sarajevo in June 1914.
preceded(assassination_of_archduke_franz_ferdinand, world_war_i).
% Explanation: The assassination triggered a chain of events that started World War I.
died_in(archduke_franz_ferdinand, x1914).
% Explanation: He was assassinated in 1914.
killed(gavrilo_princip, archduke_franz_ferdinand).
% Explanation: Gavrilo Princip assassinated Archduke Franz Ferdinand.
comprised_of(triple_entente, united_kingdom).
% Explanation: The UK was a member of the Triple Entente.
comprised_of(triple_entente, france).
% Explanation: France was a member of the Triple Entente.
comprised_of(triple_entente, russia).
% Explanation: Russia was a member of the Triple Entente.
opposed_to(triple_entente, central_powers).
% Explanation: The two alliances fought against each other in the war.
comprised_of(central_powers, germany).
% Explanation: Germany was a member of the Central Powers.
comprised_of(central_powers, austriahungary).
% Explanation: Austria-Hungary was a member of the Central Powers.
comprised_of(central_powers, ottoman_empire).
% Explanation: Ottoman Empire was part of the Central Powers.
comprised_of(central_powers, bulgaria).
% Explanation: Bulgaria was a late member of the Central Powers.
joined_war(united_states, x1917).
% Explanation: The US joined World War I in 1917 on the side of the Allies.
ended_with(world_war_i, armistice_of_11_november_1918).
% Explanation: WWI ended with the armistice signed on November 11, 1918.
occurred_in(armistice_of_11_november_1918, x1918).
% Explanation: The armistice ended the fighting on the Western Front.
signed_in(treaty_of_versailles, x1919).
% Explanation: The peace treaty ending the war was signed in 1919.
preceded(world_war_i, treaty_of_versailles).
% Explanation: The war ended and the treaty was then signed.
preceded(world_war_i, russian_revolution).
% Explanation: The stresses of WWI contributed to the outbreak of the Russian Revolution in 1917.
occurred_in(russian_revolution, x1917).
% Explanation: The Russian Revolution broke out during WWI, leading to Russia withdrawing from the war.
led(vladimir_lenin, russian_revolution).
% Explanation: Lenin was the leader of the Bolsheviks during the 1917 revolution.
ruled_during(tsar_nicholas_ii, world_war_i).
% Explanation: Nicholas II was the Tsar of Russia during WWI.
ruled_during(kaiser_wilhelm_ii, germany_world_war_i).
% Explanation: Kaiser Wilhelm II was emperor of Germany during WWI.
prime_minister_during(david_lloyd_george, united_kingdom_world_war_i).
% Explanation: Lloyd George was the UK Prime Minister during the last years of WWI.
prime_minister_during(georges_clemenceau, france_world_war_i).
% Explanation: Clemenceau was the French Premier towards the end of the war.
president_during(woodrow_wilson, united_states_world_war_i).
% Explanation: Wilson was US President from 1913–1921, throughout US involvement in WWI.
proposed(woodrow_wilson, fourteen_points).
% Explanation: Wilson presented his plan for postwar peace in 1918.
influenced(fourteen_points, league_of_nations).
% Explanation: The Fourteen Points called for the creation of the League of Nations.
founded_by(league_of_nations, treaty_of_versailles).
% Explanation: The League of Nations was established as part of the Treaty of Versailles.
succeeded(weimar_republic, german_empire).
% Explanation: The Weimar Republic was established in Germany after WWI.
occurred_in(battle_of_the_somme, x1916).
% Explanation: One of the largest battles of WWI occurred in 1916.
occurred_in(battle_of_verdun, x1916).
% Explanation: The battle lasted from February to December 1916.
occurred_in(gallipoli_campaign, x19151916).
% Explanation: The campaign took place on the Gallipoli Peninsula from 1915 to 1916.
located_in(western_front, france).
% Explanation: Most of the Western Front ran through France and Belgium.
located_in(western_front, belgium).
% Explanation: Parts of the Western Front were in Belgium.
located_in(eastern_front, russia).
% Explanation: The Eastern Front comprised battles in Eastern Europe including Russia.
located_in(gallipoli_campaign, ottoman_empire).
% Explanation: Gallipoli is part of modern Turkey, which was then the Ottoman Empire.
used_during(mustard_gas, world_war_i).
% Explanation: Mustard gas was introduced as a chemical weapon during WWI.
prevalent_in(trench_warfare, western_front).
% Explanation: Trench warfare characterized the Western Front in WWI.
between(no_mans_land, opposing_trenches).
% Explanation: No Man's Land referred to the area between enemy trenches.
contained_in(war_guilt_clause, treaty_of_versailles).
% Explanation: Article 231 of the treaty assigned war guilt to Germany.
occurred_in(zimmermann_telegram, x1917).
% Explanation: The telegram was sent in 1917, urging Mexico to join the war against the US.
influenced(zimmermann_telegram, united_states).
% Explanation: The telegram contributed to the US decision to join WWI.
preceded(world_war_i, world_war_ii).
% Explanation: World War I was followed by World War II.
born_in(gavrilo_princip, x1894).
% Explanation: Gavrilo Princip was born in 1894.
died_in(gavrilo_princip, x1918).
% Explanation: Gavrilo Princip died in 1918.
born_in(kaiser_wilhelm_ii, x1859).
% Explanation: Kaiser Wilhelm II was born in 1859.
died_in(kaiser_wilhelm_ii, x1941).
% Explanation: Kaiser Wilhelm II died in 1941.
born_in(woodrow_wilson, x1856).
% Explanation: Woodrow Wilson was born in 1856.
died_in(woodrow_wilson, x1924).
% Explanation: Woodrow Wilson died in 1924.
born_in(david_lloyd_george, x1863).
% Explanation: Lloyd George was born in 1863.
died_in(david_lloyd_george, x1945).
% Explanation: Lloyd George died in 1945.
born_in(georges_clemenceau, x1841).
% Explanation: Clemenceau was born in 1841.
died_in(georges_clemenceau, x1929).
% Explanation: Clemenceau died in 1929.
born_in(vladimir_lenin, x1870).
% Explanation: Lenin was born in 1870.
died_in(vladimir_lenin, x1924).
% Explanation: Lenin died in 1924.
born_in(tsar_nicholas_ii, x1868).
% Explanation: Nicholas II was born in 1868.
died_in(tsar_nicholas_ii, x1918).
% Explanation: Nicholas II was executed in 1918.
contemporary_of(woodrow_wilson, david_lloyd_george).
% Explanation: Both were leaders of their countries during WWI.
contemporary_of(woodrow_wilson, georges_clemenceau).
% Explanation: Both were leaders during WWI and key figures at the Versailles negotiations.
contemporary_of(david_lloyd_george, georges_clemenceau).
% Explanation: Both were Allied leaders during WWI and at Versailles.
contemporary_of(vladimir_lenin, tsar_nicholas_ii).
% Explanation: Both played key roles in Russia during WWI and 1917 Revolution.
related_to(trench_warfare, trench_warfare).
related_to(no_mans_land, trench_warfare).
concept(barbed_wire).
related_to(barbed_wire, trench_warfare).
concept(machine_gun).
related_to(machine_gun, trench_warfare).
concept(artillery).
related_to(artillery, trench_warfare).
concept(gas_warfare).
related_to(gas_warfare, trench_warfare).
concept(stalemate).
related_to(stalemate, trench_warfare).
concept(over_the_top).
related_to(over_the_top, trench_warfare).
concept(duckboards).
related_to(duckboards, trench_warfare).
concept(trench_foot).
related_to(trench_foot, trench_warfare).
related_to(western_front, trench_warfare).
related_to(eastern_front, trench_warfare).
related_to(world_war_i, trench_warfare).
concept(world_war_ii).
related_to(world_war_ii, trench_warfare).
related_to(battle_of_the_somme, trench_warfare).
related_to(battle_of_verdun, trench_warfare).
concept(battle_of_passchendaele).
related_to(battle_of_passchendaele, trench_warfare).
concept(christmas_truce).
related_to(christmas_truce, trench_warfare).
concept(douglas_haig).
related_to(douglas_haig, trench_warfare).
concept(erich_ludendorff).
related_to(erich_ludendorff, trench_warfare).
concept(ferdinand_foch).
related_to(ferdinand_foch, trench_warfare).
concept(john_j_pershing).
related_to(john_j_pershing, trench_warfare).
concept(british_expeditionary_force).
related_to(british_expeditionary_force, trench_warfare).
concept(french_army).
related_to(french_army, trench_warfare).
concept(german_army).
related_to(german_army, trench_warfare).
related_to(central_powers, trench_warfare).
concept(allied_powers).
related_to(allied_powers, trench_warfare).
concept(shell_shock).
related_to(shell_shock, trench_warfare).
concept(first_battle_of_ypres).
related_to(first_battle_of_ypres, trench_warfare).
concept(second_battle_of_ypres).
related_to(second_battle_of_ypres, trench_warfare).
concept(trench_raid).
related_to(trench_raid, trench_warfare).
occurred_in(trench_warfare, world_war_i).
% Explanation: Trench warfare was the dominant form of combat during World War I.
occurred_in(trench_warfare, western_front).
% Explanation: Trench warfare was most prominently practiced on the Western Front during WWI.
involved(trench_warfare, barbed_wire).
% Explanation: Barbed wire was widely used in trench defenses.
involved(trench_warfare, no_mans_land).
% Explanation: No Man's Land referred to the area between opposing trenches.
involved(trench_warfare, machine_gun).
% Explanation: Machine guns made attacking trenches deadly and led to stalemate.
involved(trench_warfare, artillery).
% Explanation: Artillery bombardment was pervasive in trench warfare.
involved(trench_warfare, gas_warfare).
% Explanation: Chemical weapons were used in the trenches starting in 1915.
caused(trench_warfare, stalemate).
% Explanation: The structure of trench warfare led to long periods of deadlock.
occurred_in(trench_warfare, eastern_front).
% Explanation: Trench warfare was less common but still present on the Eastern Front.
teaches_risk_of(trench_warfare, over_the_top).
% Explanation: Going 'over the top' involved attacking across No Man's Land, resulting in massive casualties.
caused(trench_warfare, trench_foot).
% Explanation: Trench foot was a common medical problem caused by wet trench conditions.
resulted_in(trench_warfare, shell_shock).
% Explanation: Prolonged exposure to bombardment and anxiety led to 'shell shock' (PTSD).
required_equipment(trench_warfare, duckboards).
% Explanation: Duckboards were used to line trench floors to prevent soldiers from standing in water and mud.
occurred_in(battle_of_passchendaele, x1917).
% Explanation: The Battle of Passchendaele (Third Battle of Ypres) was fought in 1917.
occurred_in(first_battle_of_ypres, x1914).
% Explanation: The First Battle of Ypres took place in 1914, marking the start of trench warfare.
occurred_in(second_battle_of_ypres, x1915).
% Explanation: The Second Battle of Ypres was fought in 1915 and saw the first use of poison gas on the Western Front.
occurred_in(trench_warfare, world_war_ii).
% Explanation: Trench warfare featured in limited form in WW2, particularly in the early stages.
employed_by(trench_warfare, british_expeditionary_force).
% Explanation: The BEF established and fought in trenches on the Western Front.
employed_by(trench_warfare, french_army).
% Explanation: The French Army was a major participant in trench warfare.
employed_by(trench_warfare, german_army).
% Explanation: German military engineers pioneered many trench systems.
took_place_in(battle_of_the_somme, france).
% Explanation: The Somme battlefields were in northern France.
took_place_in(battle_of_verdun, france).
% Explanation: The Battle of Verdun was fought in northeastern France.
took_place_in(battle_of_passchendaele, belgium).
% Explanation: Passchendaele, or Third Battle of Ypres, was fought in Flanders, Belgium.
commanded_during(douglas_haig, battle_of_the_somme).
% Explanation: General Douglas Haig was the British commander at the Somme.
commanded_during(erich_ludendorff, battle_of_verdun).
% Explanation: Ludendorff was a key German leader during trench battles including Verdun.
commanded_during(ferdinand_foch, battle_of_the_somme).
% Explanation: Marshal Foch led French forces at the Somme and other Western Front battles.
commanded(john_j_pershing, allied_powers).
% Explanation: General Pershing led the American Expeditionary Force on the Western Front.
part_of(british_expeditionary_force, allied_powers).
% Explanation: BEF fought as part of the Allies.
part_of(french_army, allied_powers).
% Explanation: The French Army was a major Allied power.
part_of(german_army, central_powers).
% Explanation: The German Army led the Central Powers.
famous_event(trench_warfare, christmas_truce).
% Explanation: The Christmas Truce of 1914 was a spontaneous ceasefire among trench soldiers.
preceded(battle_of_the_somme, battle_of_passchendaele).
% Explanation: Somme occurred in 1916, Passchendaele in 1917.
concurrent_with(battle_of_verdun, battle_of_the_somme).
% Explanation: Both major battles took place in 1916.
common_tactic_in(trench_raid, trench_warfare).
% Explanation: Trench raids were nighttime attacks on enemy trenches.
reached_apex(trench_warfare, x19151917).
% Explanation: This period saw the highest intensity and deadlock of trench warfare.
born_in(douglas_haig, x1861).
% Explanation: Haig was born in 1861.
died_in(douglas_haig, x1928).
% Explanation: Haig died in 1928.
born_in(erich_ludendorff, x1865).
% Explanation: Ludendorff was born in 1865.
died_in(erich_ludendorff, x1937).
% Explanation: Ludendorff died in 1937.
born_in(ferdinand_foch, x1851).
% Explanation: Foch was born in 1851.
died_in(ferdinand_foch, x1929).
% Explanation: Foch died in 1929.
born_in(john_j_pershing, x1860).
% Explanation: Pershing was born in 1860.
died_in(john_j_pershing, x1948).
% Explanation: Pershing died in 1948.
contemporary_of(douglas_haig, ferdinand_foch).
% Explanation: Both were commanding generals on the Western Front during WWI.
contemporary_of(douglas_haig, erich_ludendorff).
% Explanation: Haig and Ludendorff were opposing generals during trench warfare.
contemporary_of(ferdinand_foch, erich_ludendorff).
% Explanation: Commanded opposing armies during Western Front trench battles.
